import type { TimelineProject } from "./video-timeline-editor.types";

export function createDefaultVideoTimelineProject(): TimelineProject {
  return {
    id: crypto.randomUUID(),
    name: "New Project",
    duration: 120,
    frameRate: 30,
    resolution: { width: 1920, height: 1080 },
    tracks: [
      {
        id: "v1",
        name: "Video 1",
        type: "video",
        height: 60,
        visible: true,
        locked: false,
        muted: false,
        solo: false,
        color: "var(--aethel-primary)",
        volume: 1,
        pan: 0,
        clips: [],
      },
      {
        id: "v2",
        name: "Video 2",
        type: "video",
        height: 60,
        visible: true,
        locked: false,
        muted: false,
        solo: false,
        color: "var(--aethel-accent)",
        volume: 1,
        pan: 0,
        clips: [],
      },
      {
        id: "a1",
        name: "Audio 1",
        type: "audio",
        height: 50,
        visible: true,
        locked: false,
        muted: false,
        solo: false,
        color: "var(--aethel-success)",
        volume: 1,
        pan: 0,
        clips: [],
      },
      {
        id: "a2",
        name: "Audio 2",
        type: "audio",
        height: 50,
        visible: true,
        locked: false,
        muted: false,
        solo: false,
        color: "var(--aethel-success)",
        volume: 1,
        pan: 0,
        clips: [],
      },
    ],
    clips: new Map([
      [
        "clip1",
        {
          id: "clip1",
          name: "Scene 01",
          type: "video",
          trackId: "v1",
          startTime: 0,
          duration: 10,
          sourceIn: 0,
          sourceOut: 10,
          sourceDuration: 15,
          sourceUrl: "/media/scene01.mp4",
          audioLevel: 1,
          opacity: 1,
          speed: 1,
          keyframes: [],
          effects: [],
          transitions: {},
          color: "var(--aethel-primary)",
          locked: false,
          muted: false,
        },
      ],
      [
        "clip2",
        {
          id: "clip2",
          name: "Scene 02",
          type: "video",
          trackId: "v1",
          startTime: 10,
          duration: 15,
          sourceIn: 0,
          sourceOut: 15,
          sourceDuration: 20,
          sourceUrl: "/media/scene02.mp4",
          audioLevel: 1,
          opacity: 1,
          speed: 1,
          keyframes: [],
          effects: [],
          transitions: {},
          color: "var(--aethel-primary)",
          locked: false,
          muted: false,
        },
      ],
      [
        "clip3",
        {
          id: "clip3",
          name: "Background Music",
          type: "audio",
          trackId: "a1",
          startTime: 0,
          duration: 30,
          sourceIn: 0,
          sourceOut: 30,
          sourceDuration: 180,
          sourceUrl: "/media/music.mp3",
          audioLevel: 0.7,
          opacity: 1,
          speed: 1,
          keyframes: [],
          effects: [],
          transitions: {},
          color: "var(--aethel-success)",
          locked: false,
          muted: false,
        },
      ],
    ]),
    markers: [],
    regions: [],
    workAreaIn: 0,
    workAreaOut: 120,
  };
}
