name: CI — Jest and Playwright

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ infra/playwright-ci-ensemble ]

jobs:
  test:
    name: Run Jest unit tests and Playwright E2E
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install repo dependencies
        run: |
          npm ci

      - name: Run syntax check (repo)
        run: |
          powershell -NoProfile -Command "pwsh -c 'echo running syntax check not on Windows in CI' || true"

      - name: Run Jest tests for mock package
        working-directory: tools/llm-mock
        run: npm test --silent

      - name: Setup Playwright browsers and deps
        uses: microsoft/playwright-github-action@v1
        with:
          install-deps: true

      - name: Run Playwright tests
        run: |
          npx playwright test --project=chromium --reporter=github
name: CI - Jest + Playwright

on:
  push:
    branches: [ 'infra/playwright-ci-ensemble', 'infra/playwright-ci', 'main' ]
  pull_request:
    branches: [ 'infra/playwright-ci', 'main' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci

      - name: Install Playwright browsers
        run: |
          npx playwright install --with-deps

      - name: TypeScript check (ai-ide)
        run: |
          npx -y tsc --noEmit -p cloud-ide-desktop/aethel_theia_fork/packages/ai-ide/tsconfig.json

      - name: Run Jest unit tests (ai-ide)
        run: |
          cd cloud-ide-desktop/aethel_theia_fork/packages/ai-ide
          npx jest --config jest.config.js --runInBand

      - name: Run Playwright E2E (ensemble tests)
        run: |
          npx playwright test examples/playwright/tests/ensemble.spec.ts --config=playwright.config.ts --reporter=list
          npx playwright test examples/playwright/tests/ensemble-runtime.spec.ts --config=playwright.config.ts --reporter=list

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
