name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      run_e2e:
        description: 'Run Playwright E2E job (set to "true" to run)'
        required: false
        default: 'false'
      run_proxy_tests:
        description: 'Start proxy shim for proxy-related tests (set to "true" to start).'
        required: false
        default: 'false'

jobs:
  windows-check:
    name: Windows checks (syntax, tsc, ai-ide tests)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Repo syntax check (PowerShell)
        shell: pwsh
        run: powershell -ExecutionPolicy Bypass -File build/check_syntax.ps1

      - name: TypeScript check (ai-ide package)
        run: npx -y tsc --noEmit -p cloud-ide-desktop/aethel_theia_fork/packages/ai-ide/tsconfig.json

      - name: Run ai-ide unit tests
        shell: pwsh
        run: |
          Push-Location cloud-ide-desktop/aethel_theia_fork/packages/ai-ide
          node ./test/run-mocha.js
          Pop-Location

  e2e:
    name: Playwright E2E (optional)
    runs-on: ubuntu-latest
    needs: windows-check
    if: ${{ github.event.inputs.run_e2e == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npm run playwright:install

      - name: Determine Playwright config
        id: playwright-config
        run: |
          if [ -f playwright.config.ts ]; then
            echo "config=playwright.config.ts" >> "$GITHUB_OUTPUT"
          elif [ -f playwright.config.js ]; then
            echo "config=playwright.config.js" >> "$GITHUB_OUTPUT"
          else
            echo "config=" >> "$GITHUB_OUTPUT"
          fi

      - name: Start dev mock backend + proxy shim
        run: |
          # Start dev mock backend always; start proxy shim only if input run_proxy_tests == "true"
          if [ "${{ github.event.inputs.run_proxy_tests }}" = "true" ]; then
            nohup env PORT=8011 node tools/dev-mock-backend/server.js > dev-mock.log 2>&1 &
            nohup env LISTEN_PORT=8010 TARGET_PORT=8011 node tools/ci/proxy-shim.js > proxy-shim.log 2>&1 &
          else
            nohup env PORT=8011 node tools/dev-mock-backend/server.js > dev-mock.log 2>&1 &
          fi

      - name: Wait for backend (health check)
        run: |
          chmod +x tools/ci/dev-mock-health.sh || true
          tools/ci/dev-mock-health.sh

      - name: Run Playwright tests
        env:
          PLAYWRIGHT_CONFIG: ${{ steps.playwright-config.outputs.config }}
        run: |
          if [ -z "$PLAYWRIGHT_CONFIG" ]; then
            echo "::warning::No Playwright config found; skipping tests."
            exit 0
          fi
          mkdir -p test-results
          npx playwright test --config="$PLAYWRIGHT_CONFIG" --retries=1 --reporter="line,json=test-results/playwright.json,html"

      - name: Summarize Playwright diagnostics
        if: always()
        run: |
          node tools/ci/write-playwright-summary.mjs --json test-results/playwright.json --out diagnostics/PLAYWRIGHT_SUMMARY.txt

      - name: Comment Playwright summary on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const core = require('@actions/core');
            const summaryPath = 'diagnostics/PLAYWRIGHT_SUMMARY.txt';
            if (!fs.existsSync(summaryPath)) {
              core.info('Summary file not found; skipping PR comment');
              return;
            }
            const summary = fs.readFileSync(summaryPath, 'utf8').trim();
            if (!summary) {
              core.info('Summary file empty; skipping PR comment');
              return;
            }
            const runUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            const body = [
              '### Playwright Summary',
              '',
              '```',
              summary,
              '```',
              '',
              `[View workflow run](${runUrl})`,
              '',
              'Artifacts: Playwright report + diagnostics attached to this run.'
            ].join('\n');
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.payload.pull_request.number,
              body
            });

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: warn

      - name: Upload Playwright diagnostics
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-diagnostics
          path: |
            diagnostics/PLAYWRIGHT_SUMMARY.txt
            test-results/playwright.json
          if-no-files-found: warn

      - name: Upload dev mock logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dev-mock-log
          path: |
            dev-mock.log
            proxy-shim.log
          if-no-files-found: warn
