'use client';

import { useState } from 'react';

type DeletionScope = 'prompts' | 'embeddings' | 'generated_assets' | 'account';

const SCOPE_OPTIONS: { key: DeletionScope; label: string; description: string; destructive?: boolean }[] = [
  {
    key: 'prompts',
    label: 'Generation Prompts',
    description: 'Removes all stored text prompts and their hashes from our databases.',
  },
  {
    key: 'embeddings',
    label: 'Style Embeddings',
    description: 'Removes all style vectors generated from your creative sessions.',
  },
  {
    key: 'generated_assets',
    label: 'Generated Assets',
    description: 'Permanently deletes all 3D meshes, textures, and worlds generated by your account.',
    destructive: true,
  },
  {
    key: 'account',
    label: 'Full Account Deletion',
    description: 'Deletes your account, projects, and all associated data. Irreversible.',
    destructive: true,
  },
];

export default function PrivacySettingsPage() {
  const [selectedScopes, setSelectedScopes] = useState<Set<DeletionScope>>(new Set());
  const [confirm, setConfirm] = useState('');
  const [status, setStatus] = useState<'idle' | 'pending' | 'success' | 'error'>('idle');
  const [message, setMessage] = useState('');

  const toggleScope = (key: DeletionScope) => {
    setSelectedScopes(prev => {
      const next = new Set(prev);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });
  };

  const handleSubmit = async () => {
    if (confirm.toLowerCase() !== 'delete my data') return;
    setStatus('pending');
    try {
      const res = await fetch('/api/gdpr/delete', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ scope: Array.from(selectedScopes) }),
      });
      const data = await res.json() as { message?: string; error?: string };
      if (!res.ok) throw new Error(data.error ?? 'Deletion failed');
      setStatus('success');
      setMessage(data.message ?? 'Deletion complete.');
    } catch (err) {
      setStatus('error');
      setMessage(err instanceof Error ? err.message : 'An error occurred.');
    }
  };

  return (
    <div className="mx-auto max-w-2xl space-y-10 px-6 py-12">
      <header>
        <h1 className="text-2xl font-bold text-[var(--aethel-text-primary)]">Privacy & Data</h1>
        <p className="mt-2 text-sm text-[var(--aethel-text-secondary)]">
          Request deletion of your personal data under GDPR Article 17 / CCPA right to delete.
        </p>
      </header>

      {status === 'success' ? (
        <div className="rounded-xl border border-green-700/40 bg-green-900/20 p-6 text-sm text-green-400">
          {message}
        </div>
      ) : (
        <>
          <div className="space-y-3">
            <p className="text-xs font-semibold uppercase tracking-wider text-[var(--aethel-text-tertiary)]">
              Select data to delete
            </p>
            {SCOPE_OPTIONS.map(opt => (
              <label
                key={opt.key}
                className={`flex cursor-pointer items-start gap-4 rounded-xl border p-4 transition-colors ${
                  selectedScopes.has(opt.key)
                    ? opt.destructive
                      ? 'border-red-500/40 bg-red-900/10'
                      : 'border-[var(--aethel-neon-cyan)]/40 bg-[var(--aethel-surface-secondary)]'
                    : 'border-[var(--aethel-border-subtle)] bg-[var(--aethel-surface-secondary)]'
                }`}
              >
                <input
                  type="checkbox"
                  className="mt-0.5 accent-[var(--aethel-neon-cyan)]"
                  checked={selectedScopes.has(opt.key)}
                  onChange={() => toggleScope(opt.key)}
                />
                <div>
                  <p className={`text-sm font-medium ${opt.destructive ? 'text-red-400' : 'text-[var(--aethel-text-primary)]'}`}>
                    {opt.label}
                  </p>
                  <p className="mt-0.5 text-xs text-[var(--aethel-text-tertiary)]">{opt.description}</p>
                </div>
              </label>
            ))}
          </div>

          {selectedScopes.size > 0 && (
            <div className="space-y-3">
              <p className="text-xs text-[var(--aethel-text-secondary)]">
                Type <span className="font-mono font-semibold text-red-400">delete my data</span> to confirm
              </p>
              <input
                type="text"
                className="w-full rounded-lg border border-[var(--aethel-border-subtle)] bg-[var(--aethel-surface-secondary)] px-3 py-2 text-sm text-[var(--aethel-text-primary)] outline-none focus:border-red-500"
                value={confirm}
                onChange={e => setConfirm(e.target.value)}
                placeholder="delete my data"
              />
              {status === 'error' && (
                <p className="text-xs text-red-400">{message}</p>
              )}
              <button
                onClick={handleSubmit}
                disabled={confirm.toLowerCase() !== 'delete my data' || status === 'pending'}
                className="w-full rounded-lg bg-red-600 px-4 py-2.5 text-sm font-semibold text-white transition-opacity disabled:opacity-40 hover:bg-red-500"
              >
                {status === 'pending' ? 'Processing…' : 'Submit Deletion Request'}
              </button>
            </div>
          )}
        </>
      )}

      <p className="text-xs text-[var(--aethel-text-tertiary)]">
        Questions? Email{' '}
        <a href="mailto:privacy@aethel.gg" className="text-[var(--aethel-neon-cyan)] underline underline-offset-2">
          privacy@aethel.gg
        </a>
      </p>
    </div>
  );
}
