import type React from 'react'
import {
  Activity,
  AlertTriangle,
  Bell,
  Brain,
  CreditCard,
  Database,
  FileText,
  Flag,
  Gauge,
  LayoutDashboard,
  Lock,
  MessageSquare,
  Package,
  Server,
  Settings,
  Shield,
  TrendingUp,
  Users,
  Zap,
  Boxes,
} from 'lucide-react'
import {
  ADMIN_CONSOLIDATED_SECTIONS,
  getAdminRouteCoverage,
  getAdminRouteLabel,
  getAdminRouteNavigationHref,
} from '@/lib/admin/admin-consolidation'
import type { NavGroup } from './admin-ops-layout.types'

export const sectionIconById = {
  people: Users,
  money: CreditCard,
  ai: Brain,
  platform: Server,
  trust: Shield,
  product: Boxes,
} satisfies Record<string, React.ElementType>

export const routeIconByHref: Record<string, React.ElementType> = {
  '/admin/people': Users,
  '/admin/users': Users,
  '/admin/roles': Lock,
  '/admin/support': MessageSquare,
  '/admin/feedback': MessageSquare,
  '/admin/onboarding': Zap,
  '/admin/money': CreditCard,
  '/admin/finance': TrendingUp,
  '/admin/payments': CreditCard,
  '/admin/subscriptions': CreditCard,
  '/admin/cost-optimization': Gauge,
  '/admin/arpu-churn': TrendingUp,
  '/admin/promotions': CreditCard,
  '/admin/platform': Server,
  '/admin/monitoring': Activity,
  '/admin/infrastructure': Server,
  '/admin/deploy': Package,
  '/admin/emergency': AlertTriangle,
  '/admin/backup': Database,
  '/admin/scalability': Gauge,
  '/admin/updates': Package,
  '/admin/real-time': Activity,
  '/admin/trust': Shield,
  '/admin/security': Lock,
  '/admin/audit-logs': FileText,
  '/admin/compliance': FileText,
  '/admin/rate-limiting': Gauge,
  '/admin/moderation': Shield,
  '/admin/ip-registry': Shield,
  '/admin/god-view': Gauge,
  '/admin/ai': Brain,
  '/admin/ai-monitor': Brain,
  '/admin/ai-agents': Boxes,
  '/admin/ai-training': Gauge,
  '/admin/fine-tuning': Gauge,
  '/admin/indexing': Database,
  '/admin/ai-enhancements': Brain,
  '/admin/ai-upgrades': Brain,
  '/admin/bias-detection': Shield,
  '/admin/automation': Zap,
  '/admin/product': LayoutDashboard,
  '/admin/marketplace': Boxes,
  '/admin/feature-flags': Flag,
  '/admin/ide-settings': Settings,
  '/admin/apis': Package,
  '/admin/collaboration': MessageSquare,
  '/admin/chat': MessageSquare,
  '/admin/multi-tenancy': Users,
  '/admin/notifications': Bell,
}

export const navGroups: NavGroup[] = ADMIN_CONSOLIDATED_SECTIONS.map((section) => ({
  label: section.label,
  href: section.href,
  description: section.operatorQuestion,
  owner: section.owner,
  intent: section.intent,
  riskLane: section.riskLane,
  evidenceStatus: section.evidenceStatus,
  routeCount: section.routes.length,
  icon: sectionIconById[section.id],
  items: section.routes.map((route) => ({
    title: getAdminRouteLabel(route),
    href: getAdminRouteNavigationHref(route),
    icon: routeIconByHref[route] || sectionIconById[section.id],
    badge: section.primaryLinks.find((link) => link.href === route)?.badge,
  })),
  primaryItems: section.primaryLinks.map((link) => ({
    title: link.label,
    href: link.href,
    icon: routeIconByHref[link.href] || sectionIconById[section.id],
    badge: link.badge,
  })),
  legacyItems: section.routes
    .filter((route) => route !== section.href && !section.primaryLinks.some((link) => link.href === route))
    .map((route) => ({
      title: getAdminRouteLabel(route),
      href: getAdminRouteNavigationHref(route),
      icon: routeIconByHref[route] || sectionIconById[section.id],
    })),
}))

export const adminCoverage = getAdminRouteCoverage()
