import { ChatAgent, ChatHierarchyBranch, ChatModel, ChatRequestModel, ChatService } from '@theia/ai-chat';
import { ChangeSetDecoratorService } from '@theia/ai-chat/lib/browser/change-set-decorator-service';
import { AIVariableResolutionRequest } from '@theia/ai-core';
import { AgentCompletionNotificationService, FrontendVariableService, AIActivationService } from '@theia/ai-core/lib/browser';
import { DisposableCollection, Emitter, InMemoryResources, URI } from '@theia/core';
import { ContextMenuRenderer, LabelProvider, Message, OpenerService, ReactWidget } from '@theia/core/lib/browser';
import { ContextKey, ContextKeyService } from '@theia/core/lib/browser/context-key-service';
import { Deferred } from '@theia/core/lib/common/promise-util';
import * as React from '@theia/core/shared/react';
import { IMouseEvent } from '@theia/monaco-editor-core';
import { MonacoEditorProvider } from '@theia/monaco/lib/browser/monaco-editor-provider';
import { SimpleMonacoEditor } from '@theia/monaco/lib/browser/simple-monaco-editor';
import { ChangeSetActionService } from './change-set-actions/change-set-action-service';
import { ContextVariablePicker } from './context-variable-picker';
import { ChatInputHistoryService, ChatInputNavigationState } from './chat-input-history';
type Query = (query: string) => Promise<void>;
type Unpin = () => void;
type Cancel = (requestModel: ChatRequestModel) => void;
type DeleteChangeSet = (requestModel: ChatRequestModel) => void;
type DeleteChangeSetElement = (requestModel: ChatRequestModel, index: number) => void;
export declare const AIChatInputConfiguration: unique symbol;
export interface AIChatInputConfiguration {
    showContext?: boolean;
    showPinnedAgent?: boolean;
    showChangeSet?: boolean;
    showSuggestions?: boolean;
    enablePromptHistory?: boolean;
}
export declare class AIChatInputWidget extends ReactWidget {
    static ID: string;
    static readonly CONTEXT_MENU: string[];
    protected readonly editorProvider: MonacoEditorProvider;
    protected readonly resources: InMemoryResources;
    protected readonly contextMenuRenderer: ContextMenuRenderer;
    protected readonly configuration: AIChatInputConfiguration | undefined;
    protected readonly variableService: FrontendVariableService;
    protected readonly labelProvider: LabelProvider;
    protected readonly contextVariablePicker: ContextVariablePicker;
    protected readonly changeSetActionService: ChangeSetActionService;
    protected readonly agentNotificationService: AgentCompletionNotificationService;
    protected readonly changeSetDecoratorService: ChangeSetDecoratorService;
    protected readonly openerService: OpenerService;
    protected readonly chatService: ChatService;
    protected readonly aiActivationService: AIActivationService;
    protected readonly historyService: ChatInputHistoryService;
    protected navigationState: ChatInputNavigationState;
    protected readonly contextKeyService: ContextKeyService;
    protected editorRef: SimpleMonacoEditor | undefined;
    protected readonly editorReady: Deferred<void>;
    get editor(): SimpleMonacoEditor | undefined;
    get inputConfiguration(): AIChatInputConfiguration | undefined;
    getPreviousPrompt(currentInput: string): string | undefined;
    getNextPrompt(): string | undefined;
    protected chatInputFocusKey: ContextKey<boolean>;
    protected chatInputFirstLineKey: ContextKey<boolean>;
    protected chatInputLastLineKey: ContextKey<boolean>;
    protected isEnabled: boolean;
    protected heightInLines: number;
    protected _branch?: ChatHierarchyBranch;
    set branch(branch: ChatHierarchyBranch | undefined);
    protected _onQuery: Query;
    set onQuery(query: Query);
    protected _onUnpin: Unpin;
    set onUnpin(unpin: Unpin);
    protected _onCancel: Cancel;
    set onCancel(cancel: Cancel);
    protected _onDeleteChangeSet: DeleteChangeSet;
    set onDeleteChangeSet(deleteChangeSet: DeleteChangeSet);
    protected _onDeleteChangeSetElement: DeleteChangeSetElement;
    set onDeleteChangeSetElement(deleteChangeSetElement: DeleteChangeSetElement);
    protected _initialValue?: string;
    set initialValue(value: string | undefined);
    protected onDisposeForChatModel: DisposableCollection;
    protected _chatModel: ChatModel;
    set chatModel(chatModel: ChatModel);
    protected _pinnedAgent: ChatAgent | undefined;
    set pinnedAgent(pinnedAgent: ChatAgent | undefined);
    protected onDidResizeEmitter: Emitter<void>;
    readonly onDidResize: import("@theia/core").Event<void>;
    protected init(): void;
    protected initializeContextKeys(): void;
    updateCursorPositionKeys(): void;
    protected setupEditorEventListeners(): void;
    protected onActivateRequest(msg: Message): void;
    protected handleAgentCompletion(request: ChatRequestModel): Promise<void>;
    protected getResourceUri(): URI;
    protected render(): React.ReactNode;
    protected onDragOver(event: React.DragEvent): void;
    protected onDrop(event: React.DragEvent): void;
    protected onPaste(event: ClipboardEvent): void;
    protected onEscape(): void;
    protected openContextElement(request: AIVariableResolutionRequest): Promise<void>;
    setEnabled(enabled: boolean): void;
    protected addContextElement(): void;
    protected deleteContextElement(index: number): void;
    protected handleContextMenu(event: IMouseEvent): void;
    addContext(variable: AIVariableResolutionRequest): void;
    protected getContext(): readonly AIVariableResolutionRequest[];
}
export {};
//# sourceMappingURL=chat-input-widget.d.ts.map