'use client'

import { createComponentLogger } from '@/lib/observability/logger'

import type { CommandDefinition } from './command-registry'

const logger = createComponentLogger('command-registry-defaults')

function logCommandIntent(label: string) {
  return () => logger.info(`Command triggered: ${label}`)
}

export const DEFAULT_COMMANDS: CommandDefinition[] = [
  {
    id: 'file.new',
    label: 'New File',
    description: 'Create a new file',
    category: 'file',
    shortcut: 'Cmd+N',
    icon: 'file-plus',
    priority: 100,
    tags: ['create', 'new', 'file'],
    handler: logCommandIntent('New file'),
  },
  {
    id: 'file.newFolder',
    label: 'New Folder',
    description: 'Create a new folder',
    category: 'file',
    shortcut: 'Cmd+Shift+N',
    icon: 'folder-plus',
    priority: 99,
    tags: ['create', 'folder', 'directory'],
    handler: logCommandIntent('New folder'),
  },
  {
    id: 'file.open',
    label: 'Open File',
    description: 'Open an existing file',
    category: 'file',
    shortcut: 'Cmd+O',
    icon: 'folder-open',
    priority: 98,
    tags: ['open', 'file'],
    handler: logCommandIntent('Open file'),
  },
  {
    id: 'file.save',
    label: 'Save',
    description: 'Save the current file',
    category: 'file',
    shortcut: 'Cmd+S',
    icon: 'save',
    priority: 97,
    tags: ['save', 'write'],
    handler: logCommandIntent('Save file'),
  },
  {
    id: 'file.saveAll',
    label: 'Save All',
    description: 'Save all open files',
    category: 'file',
    shortcut: 'Alt+Cmd+S',
    icon: 'save-all',
    priority: 96,
    tags: ['save', 'all'],
    handler: logCommandIntent('Save all'),
  },
  {
    id: 'edit.undo',
    label: 'Undo',
    description: 'Undo the last action',
    category: 'edit',
    shortcut: 'Cmd+Z',
    icon: 'undo',
    priority: 100,
    tags: ['undo'],
    handler: logCommandIntent('Undo'),
  },
  {
    id: 'edit.redo',
    label: 'Redo',
    description: 'Redo the previous action',
    category: 'edit',
    shortcut: 'Cmd+Shift+Z',
    icon: 'redo',
    priority: 99,
    tags: ['redo'],
    handler: logCommandIntent('Redo'),
  },
  {
    id: 'edit.cut',
    label: 'Cut',
    description: 'Cut selection',
    category: 'edit',
    shortcut: 'Cmd+X',
    icon: 'scissors',
    priority: 98,
    tags: ['cut'],
    handler: logCommandIntent('Cut'),
  },
  {
    id: 'edit.copy',
    label: 'Copy',
    description: 'Copy selection',
    category: 'edit',
    shortcut: 'Cmd+C',
    icon: 'copy',
    priority: 97,
    tags: ['copy'],
    handler: logCommandIntent('Copy'),
  },
  {
    id: 'edit.paste',
    label: 'Paste',
    description: 'Paste from clipboard',
    category: 'edit',
    shortcut: 'Cmd+V',
    icon: 'clipboard',
    priority: 96,
    tags: ['paste'],
    handler: logCommandIntent('Paste'),
  },
  {
    id: 'edit.find',
    label: 'Find',
    description: 'Find in the current file',
    category: 'edit',
    shortcut: 'Cmd+F',
    icon: 'search',
    priority: 95,
    tags: ['find', 'search'],
    handler: logCommandIntent('Find'),
  },
  {
    id: 'edit.replace',
    label: 'Replace',
    description: 'Find and replace',
    category: 'edit',
    shortcut: 'Alt+Cmd+F',
    icon: 'replace',
    priority: 94,
    tags: ['replace', 'find'],
    handler: logCommandIntent('Replace'),
  },
  {
    id: 'view.commandPalette',
    label: 'Command Palette',
    description: 'Open the command palette',
    category: 'view',
    shortcut: 'Cmd+Shift+P',
    icon: 'command',
    priority: 100,
    tags: ['command', 'palette', 'actions'],
    handler: logCommandIntent('Command palette'),
  },
  {
    id: 'view.explorer',
    label: 'Explorer',
    description: 'Show file explorer',
    category: 'view',
    shortcut: 'Cmd+Shift+E',
    icon: 'files',
    priority: 99,
    tags: ['explorer', 'files'],
    handler: logCommandIntent('Explorer'),
  },
  {
    id: 'view.search',
    label: 'Search Files',
    description: 'Search across files',
    category: 'view',
    shortcut: 'Cmd+Shift+F',
    icon: 'search',
    priority: 98,
    tags: ['search', 'files'],
    handler: logCommandIntent('Search'),
  },
  {
    id: 'view.git',
    label: 'Source Control',
    description: 'Show source control panel',
    category: 'view',
    shortcut: 'Ctrl+Shift+G',
    icon: 'git-branch',
    priority: 97,
    tags: ['git', 'source', 'control'],
    handler: logCommandIntent('Git'),
  },
  {
    id: 'view.terminal',
    label: 'Terminal',
    description: 'Open integrated terminal',
    category: 'view',
    shortcut: 'Ctrl+`',
    icon: 'terminal',
    priority: 96,
    tags: ['terminal', 'console', 'shell'],
    handler: logCommandIntent('Terminal'),
  },
  {
    id: 'view.toggleSidebar',
    label: 'Toggle Sidebar',
    description: 'Show or hide sidebar',
    category: 'view',
    shortcut: 'Cmd+B',
    icon: 'panel-left',
    priority: 95,
    tags: ['sidebar', 'toggle'],
    handler: logCommandIntent('Toggle sidebar'),
  },
  {
    id: 'view.togglePanel',
    label: 'Toggle Panel',
    description: 'Show or hide bottom panel',
    category: 'view',
    shortcut: 'Cmd+J',
    icon: 'panel-bottom',
    priority: 94,
    tags: ['panel', 'bottom'],
    handler: logCommandIntent('Toggle panel'),
  },
  {
    id: 'view.zoomIn',
    label: 'Zoom In',
    description: 'Increase editor zoom',
    category: 'view',
    shortcut: 'Cmd+=',
    icon: 'zoom-in',
    priority: 93,
    tags: ['zoom', 'in'],
    handler: logCommandIntent('Zoom in'),
  },
  {
    id: 'view.zoomOut',
    label: 'Zoom Out',
    description: 'Decrease editor zoom',
    category: 'view',
    shortcut: 'Cmd+-',
    icon: 'zoom-out',
    priority: 92,
    tags: ['zoom', 'out'],
    handler: logCommandIntent('Zoom out'),
  },
  {
    id: 'run.start',
    label: 'Run Project',
    description: 'Run the project',
    category: 'run',
    shortcut: 'F5',
    icon: 'play',
    priority: 100,
    tags: ['run', 'start', 'play'],
    handler: logCommandIntent('Run'),
  },
  {
    id: 'run.debug',
    label: 'Start Debugging',
    description: 'Start debugging',
    category: 'run',
    shortcut: 'Shift+F5',
    icon: 'bug',
    priority: 99,
    tags: ['debug'],
    handler: logCommandIntent('Debug'),
  },
  {
    id: 'run.stop',
    label: 'Stop',
    description: 'Stop execution',
    category: 'run',
    shortcut: 'Shift+F5',
    icon: 'square',
    priority: 98,
    tags: ['stop'],
    handler: logCommandIntent('Stop'),
  },
  {
    id: 'run.restart',
    label: 'Restart',
    description: 'Restart execution',
    category: 'run',
    shortcut: 'Cmd+Shift+F5',
    icon: 'refresh-cw',
    priority: 97,
    tags: ['restart'],
    handler: logCommandIntent('Restart'),
  },
  {
    id: 'run.build',
    label: 'Build',
    description: 'Build the project',
    category: 'run',
    shortcut: 'Cmd+Shift+B',
    icon: 'package',
    priority: 96,
    tags: ['build', 'compile'],
    handler: logCommandIntent('Build'),
  },
  {
    id: 'ai.chat',
    label: 'AI Chat',
    description: 'Open AI chat',
    category: 'ai',
    shortcut: 'Cmd+I',
    icon: 'message-square',
    priority: 100,
    tags: ['ai', 'chat', 'copilot', 'assistant'],
    handler: logCommandIntent('AI Chat'),
  },
  {
    id: 'ai.generateCode',
    label: 'Generate Code with AI',
    description: 'Generate code with AI',
    category: 'ai',
    shortcut: 'Ctrl+Cmd+I',
    icon: 'sparkles',
    priority: 99,
    tags: ['ai', 'generate', 'code'],
    handler: logCommandIntent('Generate code'),
  },
  {
    id: 'ai.explain',
    label: 'Explain with AI',
    description: 'Explain selected code with AI',
    category: 'ai',
    icon: 'help-circle',
    priority: 98,
    tags: ['ai', 'explain'],
    handler: logCommandIntent('Explain'),
  },
  {
    id: 'ai.refactor',
    label: 'Refactor with AI',
    description: 'Suggest a refactor with AI',
    category: 'ai',
    icon: 'wand',
    priority: 97,
    tags: ['ai', 'refactor'],
    handler: logCommandIntent('Refactor'),
  },
  {
    id: 'engine.viewport3d',
    label: '3D Viewport',
    description: 'Open the 3D viewport',
    category: 'engine',
    icon: 'box',
    priority: 100,
    tags: ['3d', 'viewport', 'scene'],
    handler: logCommandIntent('3D Viewport'),
  },
  {
    id: 'engine.visualScripting',
    label: 'Visual Scripting',
    description: 'Open visual scripting editor',
    category: 'engine',
    icon: 'workflow',
    priority: 99,
    tags: ['visual', 'scripting', 'blueprint', 'node'],
    handler: logCommandIntent('Visual Scripting'),
  },
  {
    id: 'engine.materials',
    label: 'Material Editor',
    description: 'Open material editor',
    category: 'engine',
    icon: 'palette',
    priority: 98,
    tags: ['material', 'shader', 'texture'],
    handler: logCommandIntent('Materials'),
  },
  {
    id: 'engine.animation',
    label: 'Animation Editor',
    description: 'Open animation timeline',
    category: 'engine',
    icon: 'clapperboard',
    priority: 97,
    tags: ['animation', 'timeline'],
    handler: logCommandIntent('Animation'),
  },
  {
    id: 'engine.particles',
    label: 'Particle Editor',
    description: 'Open particle system editor',
    category: 'engine',
    icon: 'sparkles',
    priority: 96,
    tags: ['particles', 'vfx'],
    handler: logCommandIntent('Particles'),
  },
  {
    id: 'preferences.settings',
    label: 'Settings',
    description: 'Open settings',
    category: 'preferences',
    shortcut: 'Cmd+,',
    icon: 'settings',
    priority: 100,
    tags: ['settings', 'preferences'],
    handler: logCommandIntent('Settings'),
  },
  {
    id: 'preferences.keyboardShortcuts',
    label: 'Keyboard Shortcuts',
    description: 'Configure keyboard shortcuts',
    category: 'preferences',
    icon: 'keyboard',
    priority: 99,
    tags: ['keyboard', 'shortcuts'],
    handler: logCommandIntent('Keyboard shortcuts'),
  },
  {
    id: 'preferences.themes',
    label: 'Themes',
    description: 'Choose color theme',
    category: 'preferences',
    icon: 'palette',
    priority: 98,
    tags: ['theme', 'colors'],
    handler: logCommandIntent('Themes'),
  },
  {
    id: 'help.documentation',
    label: 'Documentation',
    description: 'Open documentation',
    category: 'help',
    icon: 'book',
    priority: 100,
    tags: ['docs', 'documentation', 'help'],
    handler: () => window.open('/docs', '_blank'),
  },
  {
    id: 'help.shortcuts',
    label: 'Keyboard Shortcut Reference',
    description: 'View all keyboard shortcuts',
    category: 'help',
    shortcut: 'Ctrl+Shift+/',
    icon: 'keyboard',
    priority: 99,
    tags: ['shortcuts', 'reference'],
    handler: logCommandIntent('Shortcuts reference'),
  },
  {
    id: 'help.about',
    label: 'About',
    description: 'Show Aethel Engine information',
    category: 'help',
    icon: 'info',
    priority: 98,
    tags: ['about', 'version'],
    handler: logCommandIntent('About'),
  },
]
