import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'AI Content License — Aethel Engine',
  description: 'Aethel Engine AI Content License — rights for AI-generated assets.',
};

export default function AIContentLicensePage() {
  return (
    <div className="min-h-screen bg-[var(--aethel-surface-primary)] text-[var(--aethel-text-primary)]">
      <div className="mx-auto max-w-3xl px-6 py-16">
        <header className="mb-12">
          <p className="mb-2 text-xs font-semibold uppercase tracking-widest text-[var(--aethel-neon-cyan)]">Legal</p>
          <h1 className="text-3xl font-bold">Aethel AI Content License</h1>
          <p className="mt-3 text-sm text-[var(--aethel-text-tertiary)]">Version 1.0 · Effective June 27, 2026</p>
        </header>

        <div className="space-y-10 text-sm leading-7 text-[var(--aethel-text-secondary)]">
          <section>
            <h2 className="mb-3 text-base font-semibold text-[var(--aethel-text-primary)]">1. What This License Covers</h2>
            <p>This license governs all 3D meshes, textures, audio, animations, scripts, and world structures ("AI Outputs") generated by you using Aethel Engine.</p>
          </section>

          <section>
            <h2 className="mb-3 text-base font-semibold text-[var(--aethel-text-primary)]">2. Your Rights</h2>
            <p>Subject to these terms, you are granted a non-exclusive, worldwide, royalty-free license to:</p>
            <ul className="mt-2 list-disc space-y-1 pl-5">
              <li>Use AI Outputs in personal and commercial projects</li>
              <li>Sell products and games containing AI Outputs</li>
              <li>Publish AI Outputs on the Aethel Marketplace</li>
              <li>Modify and adapt AI Outputs</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-base font-semibold text-[var(--aethel-text-primary)]">3. Restrictions</h2>
            <ul className="list-disc space-y-1 pl-5">
              <li>You may not claim AI Outputs as entirely human-made in contexts where that distinction is legally material</li>
              <li>You may not use AI Outputs to train competing AI models without written permission</li>
              <li>You may not use AI Outputs to generate content that violates our Terms of Service</li>
              <li>AI Outputs published to the Marketplace must include the Aethel Provenance Certificate</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-base font-semibold text-[var(--aethel-text-primary)]">4. Provenance & Attribution</h2>
            <p>All AI Outputs include a cryptographic Provenance Certificate (ECDSA P-256 signature) that records:</p>
            <ul className="mt-2 list-disc space-y-1 pl-5">
              <li>The prompt hash (SHA-256, one-way — original prompt is not disclosed)</li>
              <li>The AI model used for generation</li>
              <li>Creation timestamp</li>
              <li>Creator ID</li>
            </ul>
            <p className="mt-2">This certificate is embedded in exported assets and verifiable by third parties using the creator's public key.</p>
          </section>

          <section>
            <h2 className="mb-3 text-base font-semibold text-[var(--aethel-text-primary)]">5. IP Indemnification</h2>
            <p>Aethel Engine makes no warranty that AI Outputs are free from third-party IP claims. You are responsible for ensuring that your prompts and outputs do not infringe existing copyrights, trademarks, or trade dress.</p>
          </section>

          <section>
            <h2 className="mb-3 text-base font-semibold text-[var(--aethel-text-primary)]">6. Contact</h2>
            <p>Licensing questions: <a href="mailto:legal@aethel.gg" className="text-[var(--aethel-neon-cyan)] underline underline-offset-2">legal@aethel.gg</a></p>
          </section>
        </div>
      </div>
    </div>
  );
}
