import type { FoliageType } from './FoliagePainter.types';

const DEFAULT_FOLIAGE_TYPES: FoliageType[] = [
  {
    id: 'oak_tree',
    name: 'Oak Tree',
    meshPath: '/meshes/trees/oak.glb',
    thumbnail: '/thumbnails/oak.png',
    category: 'tree',
    densityMin: 0.1,
    densityMax: 0.3,
    scaleMin: 0.8,
    scaleMax: 1.2,
    rotationYRandom: true,
    alignToNormal: true,
    normalAlignmentStrength: 0.3,
    minSlope: 0,
    maxSlope: 30,
    minHeight: -100,
    maxHeight: 500,
    castShadow: true,
    receiveShadow: true,
    cullDistance: 500,
    lodBias: 0,
    hasCollision: true,
    collisionType: 'box',
    windEnabled: true,
    windStrength: 0.3,
    windFrequency: 1.5,
  },
  {
    id: 'pine_tree',
    name: 'Pine Tree',
    meshPath: '/meshes/trees/pine.glb',
    thumbnail: '/thumbnails/pine.png',
    category: 'tree',
    densityMin: 0.15,
    densityMax: 0.4,
    scaleMin: 0.7,
    scaleMax: 1.3,
    rotationYRandom: true,
    alignToNormal: true,
    normalAlignmentStrength: 0.2,
    minSlope: 0,
    maxSlope: 40,
    minHeight: 100,
    maxHeight: 800,
    castShadow: true,
    receiveShadow: true,
    cullDistance: 600,
    lodBias: 0,
    hasCollision: true,
    collisionType: 'box',
    windEnabled: true,
    windStrength: 0.2,
    windFrequency: 1.2,
  },
  {
    id: 'bush_green',
    name: 'Green Bush',
    meshPath: '/meshes/bushes/green.glb',
    thumbnail: '/thumbnails/bush_green.png',
    category: 'bush',
    densityMin: 0.3,
    densityMax: 0.6,
    scaleMin: 0.6,
    scaleMax: 1.4,
    rotationYRandom: true,
    alignToNormal: true,
    normalAlignmentStrength: 0.5,
    minSlope: 0,
    maxSlope: 45,
    minHeight: -100,
    maxHeight: 600,
    castShadow: true,
    receiveShadow: true,
    cullDistance: 200,
    lodBias: 0,
    hasCollision: true,
    collisionType: 'sphere',
    windEnabled: true,
    windStrength: 0.5,
    windFrequency: 2.0,
  },
  {
    id: 'grass_tall',
    name: 'Tall Grass',
    meshPath: '/meshes/grass/tall.glb',
    thumbnail: '/thumbnails/grass_tall.png',
    category: 'grass',
    densityMin: 0.5,
    densityMax: 1.0,
    scaleMin: 0.7,
    scaleMax: 1.3,
    rotationYRandom: true,
    alignToNormal: true,
    normalAlignmentStrength: 0.8,
    minSlope: 0,
    maxSlope: 60,
    minHeight: -100,
    maxHeight: 1000,
    castShadow: false,
    receiveShadow: true,
    cullDistance: 100,
    lodBias: 1,
    hasCollision: false,
    collisionType: 'box',
    windEnabled: true,
    windStrength: 0.8,
    windFrequency: 3.0,
  },
  {
    id: 'flower_red',
    name: 'Red Flower',
    meshPath: '/meshes/flowers/red.glb',
    thumbnail: '/thumbnails/flower_red.png',
    category: 'flower',
    densityMin: 0.3,
    densityMax: 0.8,
    scaleMin: 0.5,
    scaleMax: 1.0,
    rotationYRandom: true,
    alignToNormal: true,
    normalAlignmentStrength: 0.9,
    minSlope: 0,
    maxSlope: 30,
    minHeight: -50,
    maxHeight: 400,
    castShadow: false,
    receiveShadow: true,
    cullDistance: 80,
    lodBias: 1,
    hasCollision: false,
    collisionType: 'box',
    windEnabled: true,
    windStrength: 0.6,
    windFrequency: 2.5,
  },
  {
    id: 'rock_small',
    name: 'Small Rock',
    meshPath: '/meshes/rocks/small.glb',
    thumbnail: '/thumbnails/rock_small.png',
    category: 'rock',
    densityMin: 0.1,
    densityMax: 0.3,
    scaleMin: 0.5,
    scaleMax: 2.0,
    rotationYRandom: true,
    alignToNormal: false,
    normalAlignmentStrength: 0,
    minSlope: 0,
    maxSlope: 90,
    minHeight: -100,
    maxHeight: 1000,
    castShadow: true,
    receiveShadow: true,
    cullDistance: 300,
    lodBias: 0,
    hasCollision: true,
    collisionType: 'mesh',
    windEnabled: false,
    windStrength: 0,
    windFrequency: 0,
  },
];

export { DEFAULT_FOLIAGE_TYPES };
