import type { WeatherPreset, WeatherType } from './weather-system.contracts';

export const DEFAULT_WEATHER_PRESETS: Record<WeatherType, WeatherPreset> = {
  clear: {
    name: 'Clear Sky',
    type: 'clear',
    intensity: 0,
    temperature: 22,
    humidity: 0.3,
    windSpeed: 2,
    cloudCover: 0.1,
    visibility: 20000,
    precipitation: 0,
    fogDensity: 0,
    transitions: ['partly_cloudy', 'fog'],
    duration: { min: 1800, max: 7200 },
  },
  partly_cloudy: {
    name: 'Partly Cloudy',
    type: 'partly_cloudy',
    intensity: 0.2,
    temperature: 20,
    humidity: 0.4,
    windSpeed: 5,
    cloudCover: 0.3,
    visibility: 15000,
    precipitation: 0,
    fogDensity: 0,
    transitions: ['clear', 'cloudy', 'light_rain'],
    duration: { min: 900, max: 3600 },
  },
  cloudy: {
    name: 'Cloudy',
    type: 'cloudy',
    intensity: 0.4,
    temperature: 18,
    humidity: 0.5,
    windSpeed: 8,
    cloudCover: 0.6,
    visibility: 10000,
    precipitation: 0,
    fogDensity: 0.1,
    transitions: ['partly_cloudy', 'overcast', 'light_rain'],
    duration: { min: 600, max: 2400 },
  },
  overcast: {
    name: 'Overcast',
    type: 'overcast',
    intensity: 0.6,
    temperature: 15,
    humidity: 0.7,
    windSpeed: 10,
    cloudCover: 0.9,
    visibility: 5000,
    precipitation: 0,
    fogDensity: 0.2,
    transitions: ['cloudy', 'rain', 'fog'],
    duration: { min: 600, max: 1800 },
  },
  light_rain: {
    name: 'Light Rain',
    type: 'light_rain',
    intensity: 0.3,
    temperature: 16,
    humidity: 0.8,
    windSpeed: 8,
    cloudCover: 0.7,
    visibility: 8000,
    precipitation: 2.5,
    fogDensity: 0.15,
    wetness: 0.3,
    transitions: ['cloudy', 'rain', 'clear'],
    duration: { min: 300, max: 1200 },
  },
  rain: {
    name: 'Rain',
    type: 'rain',
    intensity: 0.6,
    temperature: 14,
    humidity: 0.9,
    windSpeed: 12,
    cloudCover: 0.85,
    visibility: 4000,
    precipitation: 7.5,
    fogDensity: 0.25,
    wetness: 0.6,
    transitions: ['light_rain', 'heavy_rain', 'thunderstorm'],
    duration: { min: 300, max: 900 },
  },
  heavy_rain: {
    name: 'Heavy Rain',
    type: 'heavy_rain',
    intensity: 0.9,
    temperature: 13,
    humidity: 0.95,
    windSpeed: 18,
    cloudCover: 0.95,
    visibility: 1500,
    precipitation: 25,
    fogDensity: 0.4,
    wetness: 0.9,
    transitions: ['rain', 'thunderstorm'],
    duration: { min: 180, max: 600 },
  },
  thunderstorm: {
    name: 'Thunderstorm',
    type: 'thunderstorm',
    intensity: 1.0,
    temperature: 12,
    humidity: 0.98,
    windSpeed: 25,
    cloudCover: 1.0,
    visibility: 1000,
    precipitation: 30,
    fogDensity: 0.3,
    wetness: 1.0,
    lightning: true,
    transitions: ['heavy_rain', 'rain'],
    duration: { min: 120, max: 480 },
  },
  light_snow: {
    name: 'Light Snow',
    type: 'light_snow',
    intensity: 0.3,
    temperature: -2,
    humidity: 0.6,
    windSpeed: 5,
    cloudCover: 0.7,
    visibility: 6000,
    precipitation: 1,
    fogDensity: 0.1,
    transitions: ['cloudy', 'snow'],
    duration: { min: 600, max: 2400 },
  },
  snow: {
    name: 'Snow',
    type: 'snow',
    intensity: 0.6,
    temperature: -5,
    humidity: 0.75,
    windSpeed: 10,
    cloudCover: 0.85,
    visibility: 3000,
    precipitation: 5,
    fogDensity: 0.2,
    transitions: ['light_snow', 'blizzard'],
    duration: { min: 300, max: 1200 },
  },
  blizzard: {
    name: 'Blizzard',
    type: 'blizzard',
    intensity: 1.0,
    temperature: -10,
    humidity: 0.9,
    windSpeed: 35,
    cloudCover: 1.0,
    visibility: 200,
    precipitation: 15,
    fogDensity: 0.8,
    transitions: ['snow'],
    duration: { min: 120, max: 600 },
  },
  fog: {
    name: 'Fog',
    type: 'fog',
    intensity: 0.5,
    temperature: 12,
    humidity: 0.95,
    windSpeed: 2,
    cloudCover: 0.4,
    visibility: 500,
    precipitation: 0,
    fogDensity: 0.7,
    transitions: ['clear', 'dense_fog', 'light_rain'],
    duration: { min: 600, max: 3600 },
  },
  dense_fog: {
    name: 'Dense Fog',
    type: 'dense_fog',
    intensity: 0.8,
    temperature: 10,
    humidity: 0.98,
    windSpeed: 1,
    cloudCover: 0.5,
    visibility: 100,
    precipitation: 0,
    fogDensity: 0.95,
    transitions: ['fog'],
    duration: { min: 300, max: 1200 },
  },
  sandstorm: {
    name: 'Sandstorm',
    type: 'sandstorm',
    intensity: 0.9,
    temperature: 35,
    humidity: 0.1,
    windSpeed: 40,
    cloudCover: 0.2,
    visibility: 50,
    precipitation: 0,
    fogDensity: 0.9,
    transitions: ['clear'],
    duration: { min: 180, max: 900 },
  },
  hail: {
    name: 'Hail',
    type: 'hail',
    intensity: 0.8,
    temperature: 5,
    humidity: 0.85,
    windSpeed: 20,
    cloudCover: 0.9,
    visibility: 2000,
    precipitation: 10,
    fogDensity: 0.2,
    wetness: 0.7,
    transitions: ['thunderstorm', 'rain'],
    duration: { min: 60, max: 300 },
  },
};
