import type { ExportPreset } from './ExportSystem'

// Export presets extracted from ExportSystem to keep the main module focused.

export const EXPORT_PRESETS: ExportPreset[] = [
  // YouTube
  {
    id: 'youtube-4k',
    name: 'YouTube 4K',
    category: 'YouTube',
    description: 'Optimal settings for YouTube 4K upload',
    icon: '📺',
    settings: {
      container: 'mp4',
      videoCodec: 'h264',
      audioCodec: 'aac',
      resolution: { width: 3840, height: 2160 },
      frameRate: 30,
      bitrate: 35000,
      bitrateMode: 'vbr',
      maxBitrate: 40000,
      profile: 'high',
      sampleRate: 48000,
      channels: 2,
      audioBitrate: 384,
      useInOutPoints: false,
      twoPass: true,
      fastStart: true,
      hardwareAcceleration: true,
      deinterlace: false,
      includeMetadata: true
    }
  },
  {
    id: 'youtube-1080p',
    name: 'YouTube 1080p',
    category: 'YouTube',
    description: 'Optimal settings for YouTube HD upload',
    icon: '📺',
    settings: {
      container: 'mp4',
      videoCodec: 'h264',
      audioCodec: 'aac',
      resolution: { width: 1920, height: 1080 },
      frameRate: 30,
      bitrate: 8000,
      bitrateMode: 'vbr',
      maxBitrate: 12000,
      profile: 'high',
      sampleRate: 48000,
      channels: 2,
      audioBitrate: 320,
      useInOutPoints: false,
      twoPass: true,
      fastStart: true,
      hardwareAcceleration: true,
      deinterlace: false,
      includeMetadata: true
    }
  },
  {
    id: 'youtube-shorts',
    name: 'YouTube Shorts',
    category: 'YouTube',
    description: 'Vertical video for YouTube Shorts',
    icon: '📱',
    settings: {
      container: 'mp4',
      videoCodec: 'h264',
      audioCodec: 'aac',
      resolution: { width: 1080, height: 1920 },
      frameRate: 30,
      bitrate: 6000,
      bitrateMode: 'vbr',
      profile: 'high',
      sampleRate: 48000,
      channels: 2,
      audioBitrate: 256,
      useInOutPoints: false,
      twoPass: false,
      fastStart: true,
      hardwareAcceleration: true,
      deinterlace: false,
      includeMetadata: true
    }
  },
  
  // Social Media
  {
    id: 'instagram-feed',
    name: 'Instagram Feed',
    category: 'Social Media',
    description: 'Square video for Instagram feed',
    icon: '📷',
    settings: {
      container: 'mp4',
      videoCodec: 'h264',
      audioCodec: 'aac',
      resolution: { width: 1080, height: 1080 },
      frameRate: 30,
      bitrate: 5000,
      bitrateMode: 'vbr',
      profile: 'main',
      sampleRate: 44100,
      channels: 2,
      audioBitrate: 192,
      useInOutPoints: false,
      twoPass: false,
      fastStart: true,
      hardwareAcceleration: true,
      deinterlace: false,
      includeMetadata: false
    }
  },
  {
    id: 'instagram-reels',
    name: 'Instagram Reels',
    category: 'Social Media',
    description: 'Vertical video for Instagram Reels',
    icon: '📱',
    settings: {
      container: 'mp4',
      videoCodec: 'h264',
      audioCodec: 'aac',
      resolution: { width: 1080, height: 1920 },
      frameRate: 30,
      bitrate: 6000,
      bitrateMode: 'vbr',
      profile: 'main',
      sampleRate: 44100,
      channels: 2,
      audioBitrate: 192,
      useInOutPoints: false,
      twoPass: false,
      fastStart: true,
      hardwareAcceleration: true,
      deinterlace: false,
      includeMetadata: false
    }
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    category: 'Social Media',
    description: 'Optimized for TikTok upload',
    icon: '🎵',
    settings: {
      container: 'mp4',
      videoCodec: 'h264',
      audioCodec: 'aac',
      resolution: { width: 1080, height: 1920 },
      frameRate: 30,
      bitrate: 4000,
      bitrateMode: 'vbr',
      profile: 'main',
      sampleRate: 44100,
      channels: 2,
      audioBitrate: 192,
      useInOutPoints: false,
      twoPass: false,
      fastStart: true,
      hardwareAcceleration: true,
      deinterlace: false,
      includeMetadata: false
    }
  },
  {
    id: 'twitter',
    name: 'Twitter / X',
    category: 'Social Media',
    description: 'Optimized for Twitter video',
    icon: '🐦',
    settings: {
      container: 'mp4',
      videoCodec: 'h264',
      audioCodec: 'aac',
      resolution: { width: 1280, height: 720 },
      frameRate: 30,
      bitrate: 5000,
      bitrateMode: 'vbr',
      profile: 'main',
      sampleRate: 44100,
      channels: 2,
      audioBitrate: 192,
      useInOutPoints: false,
      twoPass: false,
      fastStart: true,
      hardwareAcceleration: true,
      deinterlace: false,
      includeMetadata: false
    }
  },
  
  // Web
  {
    id: 'web-vp9',
    name: 'Web VP9',
    category: 'Web',
    description: 'Modern web format with great compression',
    icon: '🌐',
    settings: {
      container: 'webm',
      videoCodec: 'vp9',
      audioCodec: 'opus',
      resolution: { width: 1920, height: 1080 },
      frameRate: 30,
      bitrate: 4000,
      bitrateMode: 'crf',
      crf: 31,
      sampleRate: 48000,
      channels: 2,
      audioBitrate: 128,
      useInOutPoints: false,
      twoPass: true,
      fastStart: false,
      hardwareAcceleration: false,
      deinterlace: false,
      includeMetadata: true
    }
  },
  {
    id: 'web-av1',
    name: 'Web AV1',
    category: 'Web',
    description: 'Next-gen web format (slower encoding)',
    icon: '🌐',
    settings: {
      container: 'webm',
      videoCodec: 'av1',
      audioCodec: 'opus',
      resolution: { width: 1920, height: 1080 },
      frameRate: 30,
      bitrate: 3000,
      bitrateMode: 'crf',
      crf: 30,
      sampleRate: 48000,
      channels: 2,
      audioBitrate: 128,
      useInOutPoints: false,
      twoPass: false,
      fastStart: false,
      hardwareAcceleration: false,
      deinterlace: false,
      includeMetadata: true
    }
  },
  
  // Professional
  {
    id: 'prores-422',
    name: 'Apple ProRes 422',
    category: 'Professional',
    description: 'High-quality intermediate codec',
    icon: '🎬',
    settings: {
      container: 'mov',
      videoCodec: 'prores',
      audioCodec: 'pcm',
      resolution: { width: 1920, height: 1080 },
      frameRate: 24,
      bitrate: 147000,
      bitrateMode: 'cbr',
      pixelFormat: 'yuv422p',
      sampleRate: 48000,
      channels: 2,
      audioBitrate: 1536,
      useInOutPoints: false,
      twoPass: false,
      fastStart: false,
      hardwareAcceleration: false,
      deinterlace: false,
      includeMetadata: true
    }
  },
  {
    id: 'dnxhd',
    name: 'DNxHD',
    category: 'Professional',
    description: 'Avid intermediate codec',
    icon: '🎬',
    settings: {
      container: 'mov',
      videoCodec: 'dnxhd',
      audioCodec: 'pcm',
      resolution: { width: 1920, height: 1080 },
      frameRate: 24,
      bitrate: 115000,
      bitrateMode: 'cbr',
      sampleRate: 48000,
      channels: 2,
      audioBitrate: 1536,
      useInOutPoints: false,
      twoPass: false,
      fastStart: false,
      hardwareAcceleration: false,
      deinterlace: false,
      includeMetadata: true
    }
  },
  
  // Archive
  {
    id: 'archive-high',
    name: 'Archive (High Quality)',
    category: 'Archive',
    description: 'Maximum quality for archival',
    icon: '📦',
    settings: {
      container: 'mkv',
      videoCodec: 'h265',
      audioCodec: 'flac',
      resolution: { width: 1920, height: 1080 },
      frameRate: 30,
      bitrate: 20000,
      bitrateMode: 'crf',
      crf: 18,
      profile: 'main',
      sampleRate: 48000,
      channels: 2,
      audioBitrate: 0,
      useInOutPoints: false,
      twoPass: false,
      fastStart: false,
      hardwareAcceleration: true,
      deinterlace: false,
      includeMetadata: true
    }
  },
  
  // GIF
  {
    id: 'gif-high',
    name: 'Animated GIF',
    category: 'Other',
    description: 'High quality animated GIF',
    icon: '🎞️',
    settings: {
      container: 'gif',
      videoCodec: null,
      audioCodec: null,
      resolution: { width: 480, height: 270 },
      frameRate: 15,
      bitrate: 0,
      bitrateMode: 'cbr',
      sampleRate: 0,
      channels: 1,
      audioBitrate: 0,
      useInOutPoints: false,
      twoPass: false,
      fastStart: false,
      hardwareAcceleration: false,
      deinterlace: false,
      includeMetadata: false
    }
  },
  
  // Audio Only
  {
    id: 'audio-mp3',
    name: 'MP3 Audio',
    category: 'Audio Only',
    description: 'Standard MP3 audio',
    icon: '🎵',
    settings: {
      container: 'mp4',
      videoCodec: null,
      audioCodec: 'mp3',
      resolution: { width: 0, height: 0 },
      frameRate: 0,
      bitrate: 0,
      bitrateMode: 'cbr',
      sampleRate: 44100,
      channels: 2,
      audioBitrate: 320,
      useInOutPoints: false,
      twoPass: false,
      fastStart: false,
      hardwareAcceleration: false,
      deinterlace: false,
      includeMetadata: true
    }
  },
  {
    id: 'audio-wav',
    name: 'WAV Audio',
    category: 'Audio Only',
    description: 'Uncompressed WAV audio',
    icon: '🎵',
    settings: {
      container: 'mov',
      videoCodec: null,
      audioCodec: 'pcm',
      resolution: { width: 0, height: 0 },
      frameRate: 0,
      bitrate: 0,
      bitrateMode: 'cbr',
      sampleRate: 48000,
      channels: 2,
      audioBitrate: 1536,
      useInOutPoints: false,
      twoPass: false,
      fastStart: false,
      hardwareAcceleration: false,
      deinterlace: false,
      includeMetadata: true
    }
  }
]
