/**
 * Instant Play — game-scripts-registry stage.
 *
 * Emits `generated/game-scripts.ts` with constructors + a
 * `buildGeneratedGameManifest()` factory that `runtime-main` / the browser
 * packer entry can call at boot. Transpile alone only writes per-script `.ts`.
 */

import type { GeneratedSourceFile } from '@/lib/production/visual-script-transpile-stage'

export const GAME_SCRIPTS_REGISTRY_PATH = 'generated/game-scripts.ts' as const

export interface GameScriptsRegistryEmitInput {
  projectId: string
  /** Visual-script / ability outputs from transpile (ability consts are skipped). */
  files: GeneratedSourceFile[]
  network: { enabled: boolean; relayUrl?: string }
  monetization: {
    enabled: boolean
    stripePublishableKey?: string
    checkoutEndpoint?: string
  }
}

export interface GameScriptsRegistryEmitResult {
  path: typeof GAME_SCRIPTS_REGISTRY_PATH
  content: string
  /** Entity count wired into the manifest factory (0 is valid — empty boot). */
  entityCount: number
  /** Class names included as GameScript constructors. */
  scriptClassNames: string[]
}

function isGameScriptSource(file: GeneratedSourceFile): boolean {
  if (!file.path.startsWith('generated/scripts/')) return false
  if (!file.exportedClassName || file.exportedClassName === 'GeneratedScript') return false
  return /export\s+class\s+\w+\s+extends\s+GameScript\b/.test(file.content)
}

function relativeImportFromRegistry(filePath: string): string {
  // Registry lives at generated/game-scripts.ts → scripts/Foo.ts becomes ./scripts/Foo
  const withoutPrefix = filePath.replace(/^generated\//, '')
  const withoutExt = withoutPrefix.replace(/\.tsx?$/, '')
  return `./${withoutExt}`
}

/**
 * Emit the registry module runtime-main expects at bundle/boot time.
 * Empty script sets still produce a valid module (empty entities[]).
 */
export function emitGameScriptsRegistry(
  input: GameScriptsRegistryEmitInput,
): GameScriptsRegistryEmitResult {
  const scriptFiles = input.files.filter(isGameScriptSource)
  const scriptClassNames = scriptFiles.map((f) => f.exportedClassName)

  const importLines = scriptFiles.map((file, index) => {
    const alias = `Script_${index}_${file.exportedClassName}`
    return `import { ${file.exportedClassName} as ${alias} } from '${relativeImportFromRegistry(file.path)}';`
  })

  const entityEntries = scriptFiles.map((file, index) => {
    const alias = `Script_${index}_${file.exportedClassName}`
    const entityId = file.sourceAssetId || `entity_${index}_${file.exportedClassName}`
    return [
      '  {',
      `    id: ${JSON.stringify(entityId)},`,
      `    name: ${JSON.stringify(file.exportedClassName)},`,
      `    scriptConstructors: [${alias}],`,
      '    replicated: false,',
      '  },',
    ].join('\n')
  })

  const defaultNetwork = {
    enabled: input.network.enabled,
    ...(input.network.relayUrl ? { relayUrl: input.network.relayUrl } : {}),
  }
  const defaultMonetization = {
    enabled: input.monetization.enabled,
    ...(input.monetization.stripePublishableKey
      ? { stripePublishableKey: input.monetization.stripePublishableKey }
      : {}),
    ...(input.monetization.checkoutEndpoint
      ? { checkoutEndpoint: input.monetization.checkoutEndpoint }
      : {}),
  }

  const content = [
    '// AUTO-GENERATED by Instant Play game-scripts-registry (Cook demo-web-slice).',
    '// Do not edit — re-cook to refresh.',
    '// Shape matches packages/engine/runtime-main GeneratedGameManifest (constructors included).',
    ...importLines,
    '',
    'export const INSTANT_PLAY_SCRIPT_CLASS_NAMES = ' +
      JSON.stringify(scriptClassNames, null, 2) +
      ' as const;',
    '',
    'export function buildGeneratedGameManifest(overrides) {',
    '  return {',
    '    entities: [',
    ...entityEntries,
    '    ],',
    `    network: (overrides && overrides.network) || ${JSON.stringify(defaultNetwork)},`,
    `    monetization: (overrides && overrides.monetization) || ${JSON.stringify(defaultMonetization)},`,
    '  };',
    '}',
    '',
    `export const INSTANT_PLAY_PROJECT_ID = ${JSON.stringify(input.projectId)};`,
    '',
  ].join('\n')

  return {
    path: GAME_SCRIPTS_REGISTRY_PATH,
    content,
    entityCount: scriptFiles.length,
    scriptClassNames,
  }
}
