import { PreferenceService } from '@theia/core';
import { Disposable, Event } from '@theia/core/lib/common';
import { LlmProviderConfig } from '../common/ai-llm-preferences';
export declare class LlmProviderRegistry implements Disposable {
    protected readonly preferenceService: PreferenceService;
    private readonly providersChangedEmitter;
    private readonly defaultProviderChangedEmitter;
    private providersRefreshPromise;
    private defaultRefreshPromise;
    constructor(preferenceService: PreferenceService);
    get onDidChangeProviders(): Event<LlmProviderConfig[]>;
    get onDidChangeDefaultProvider(): Event<string | undefined>;
    getAll(): LlmProviderConfig[];
    saveAll(providers: LlmProviderConfig[]): void;
    addProvider(cfg: LlmProviderConfig): void;
    removeProvider(id: string): void;
    getDefaultProviderId(): string | undefined;
    setDefaultProvider(id: string): void;
    protected fireProvidersChanged(providers?: LlmProviderConfig[]): void;
    protected fireDefaultProviderChanged(id?: string | undefined): void;
    protected scheduleProvidersRefresh(): void;
    protected scheduleDefaultProviderRefresh(): void;
    protected refreshProvidersFromBackend(): Promise<void>;
    protected persistProvidersRemotely(providers: LlmProviderConfig[]): Promise<boolean>;
    protected createProviderRemotely(cfg: LlmProviderConfig): Promise<boolean>;
    protected deleteProviderRemotely(id: string): Promise<boolean>;
    protected refreshDefaultProviderFromBackend(): Promise<void>;
    protected persistDefaultProviderRemotely(id: string): Promise<boolean>;
    protected getProvidersFromPreferences(): LlmProviderConfig[];
    protected getDefaultProviderFromPreferences(): string | undefined;
    protected normalizeProviders(providers: LlmProviderConfig[]): LlmProviderConfig[];
    protected areProvidersEqual(left: LlmProviderConfig[], right: LlmProviderConfig[]): boolean;
    protected orderProvidersForComparison(providers: LlmProviderConfig[]): LlmProviderConfig[];
    protected getPreference<T>(key: string, defaultValue: T): T;
    protected setPreference(key: string, value: unknown): void;
    protected static sanitizeProvider(provider: LlmProviderConfig): LlmProviderConfig;
    static readonly PROVIDERS_KEY = "ai.llm.providers";
    static readonly DEFAULT_PROVIDER_KEY = "ai.llm.defaultProvider";
    dispose(): void;
}
