import type { RuntimeEngineToolchainEntry } from './runtime-engine-spine'

export const RUNTIME_ENGINE_TOOLCHAIN_REGISTRY: RuntimeEngineToolchainEntry[] = [
  {
    id: 'gltf-transform',
    label: 'glTF Transform',
    category: 'asset',
    executable: 'gltf-transform',
    homepage: 'https://gltf-transform.dev/',
    license: 'MIT',
    licenseUrl: 'https://github.com/donmccurdy/glTF-Transform/blob/main/LICENSE',
    probe: { command: 'gltf-transform', args: ['--version'], expectedExitCode: 0 },
    versionArgs: ['--version'],
    checksumPolicy: 'sha256-required-before-execution',
    downloadPolicy: 'manual-consent-only',
    status: 'optional',
    provides: ['gltf-inspect', 'gltf-optimize', 'gltf-lod', 'meshopt', 'texture-transform'],
  },
  {
    id: 'meshoptimizer',
    label: 'meshoptimizer',
    category: 'asset',
    executable: 'meshopt',
    homepage: 'https://github.com/zeux/meshoptimizer',
    license: 'MIT',
    licenseUrl: 'https://github.com/zeux/meshoptimizer/blob/master/LICENSE.md',
    probe: { command: 'meshopt', args: ['--help'], expectedExitCode: 0 },
    versionArgs: ['--help'],
    checksumPolicy: 'sha256-required-before-execution',
    downloadPolicy: 'manual-consent-only',
    status: 'optional',
    provides: ['mesh-simplify', 'mesh-compress', 'vertex-cache-optimize'],
  },
  {
    id: 'ktx-software-basisu',
    label: 'KTX-Software / Basis Universal',
    category: 'asset',
    executable: 'toktx',
    homepage: 'https://github.com/KhronosGroup/KTX-Software',
    license: 'Apache-2.0',
    licenseUrl: 'https://github.com/KhronosGroup/KTX-Software/blob/main/LICENSE.md',
    probe: { command: 'toktx', args: ['--version'], expectedExitCode: 0 },
    versionArgs: ['--version'],
    checksumPolicy: 'sha256-required-before-execution',
    downloadPolicy: 'manual-consent-only',
    status: 'optional',
    provides: ['ktx2', 'basisu', 'gpu-texture-compression'],
  },
  {
    id: 'ffmpeg',
    label: 'FFmpeg / FFprobe',
    category: 'media',
    executable: 'ffmpeg',
    homepage: 'https://ffmpeg.org/',
    license: 'LGPL/GPL build dependent',
    licenseUrl: 'https://ffmpeg.org/legal.html',
    probe: { command: 'ffmpeg', args: ['-version'], expectedExitCode: 0 },
    versionArgs: ['-version'],
    checksumPolicy: 'sha256-required-before-execution',
    downloadPolicy: 'manual-consent-only',
    status: 'required-for-final',
    provides: ['video-transcode', 'audio-mux', 'frame-extract', 'ffprobe'],
  },
  {
    id: 'openusd-tools',
    label: 'OpenUSD tools',
    category: 'dcc',
    executable: 'usdcat',
    homepage: 'https://openusd.org/',
    license: 'Apache-2.0',
    licenseUrl: 'https://github.com/PixarAnimationStudios/OpenUSD/blob/release/LICENSE.txt',
    probe: { command: 'usdcat', args: ['--help'], expectedExitCode: 0 },
    versionArgs: ['--help'],
    checksumPolicy: 'sha256-required-before-execution',
    downloadPolicy: 'manual-consent-only',
    status: 'optional',
    provides: ['usd-metadata', 'usd-layer-inspect', 'usd-scene-flatten-preview'],
  },
  {
    id: 'blender-headless',
    label: 'Blender headless',
    category: 'renderer',
    executable: 'blender',
    homepage: 'https://www.blender.org/',
    license: 'GPL-3.0-or-later',
    licenseUrl: 'https://www.blender.org/about/license/',
    probe: { command: 'blender', args: ['--version'], expectedExitCode: 0 },
    versionArgs: ['--version'],
    checksumPolicy: 'sha256-required-before-execution',
    downloadPolicy: 'manual-consent-only',
    status: 'optional',
    provides: ['offline-render', 'thumbnail-render', 'asset-convert'],
  },
  {
    id: 'recast-detour',
    label: 'Recast / Detour navmesh adapter',
    category: 'navmesh',
    executable: 'recast-cli',
    homepage: 'https://github.com/recastnavigation/recastnavigation',
    license: 'Zlib',
    licenseUrl: 'https://github.com/recastnavigation/recastnavigation/blob/main/License.txt',
    probe: { command: 'recast-cli', args: ['--version'], expectedExitCode: 0 },
    versionArgs: ['--version'],
    checksumPolicy: 'sha256-required-before-execution',
    downloadPolicy: 'manual-consent-only',
    status: 'optional',
    provides: ['navmesh-build', 'pathfinding-query', 'crowd-navigation'],
  },
  {
    id: 'rapier-physics',
    label: 'Rapier physics adapter',
    category: 'physics',
    executable: 'rapier',
    homepage: 'https://rapier.rs/',
    license: 'Apache-2.0',
    licenseUrl: 'https://github.com/dimforge/rapier/blob/master/LICENSE',
    probe: { command: 'rapier', args: ['--version'], expectedExitCode: 0 },
    versionArgs: ['--version'],
    checksumPolicy: 'sha256-required-before-execution',
    downloadPolicy: 'manual-consent-only',
    status: 'optional',
    provides: ['rigid-body-physics', 'collider-validation', 'playtest-physics-replay'],
  },
  {
    id: 'zig-toolchain',
    label: 'Zig native build toolchain',
    category: 'native-build',
    executable: 'zig',
    homepage: 'https://ziglang.org/',
    license: 'MIT',
    licenseUrl: 'https://github.com/ziglang/zig/blob/master/LICENSE',
    probe: { command: 'zig', args: ['version'], expectedExitCode: 0 },
    versionArgs: ['version'],
    checksumPolicy: 'sha256-required-before-execution',
    downloadPolicy: 'manual-consent-only',
    status: 'optional',
    provides: ['native-adapter-build', 'cross-compile', 'c-cpp-toolchain'],
  },
  {
    id: 'zig-c-compiler',
    label: 'Zig cc / c++ compiler wrapper',
    category: 'native-build',
    executable: 'zig-cc',
    homepage: 'https://ziglang.org/',
    license: 'MIT',
    licenseUrl: 'https://github.com/ziglang/zig/blob/master/LICENSE',
    probe: { command: 'zig-cc', args: ['--version'], expectedExitCode: 0 },
    versionArgs: ['--version'],
    checksumPolicy: 'sha256-required-before-execution',
    downloadPolicy: 'manual-consent-only',
    status: 'optional',
    provides: ['c-adapter-build', 'cpp-adapter-build', 'native-runtime-smoke-tests'],
  },
  {
    id: 'ozz-animation',
    label: 'Ozz Animation runtime adapter',
    category: 'animation',
    executable: 'ozz-animation-adapter',
    homepage: 'https://github.com/guillaumeblanc/ozz-animation',
    license: 'MIT',
    licenseUrl: 'https://github.com/guillaumeblanc/ozz-animation/blob/master/LICENSE.md',
    probe: { command: 'ozz-animation-adapter', args: ['--version'], expectedExitCode: 0 },
    versionArgs: ['--version'],
    checksumPolicy: 'sha256-required-before-execution',
    downloadPolicy: 'manual-consent-only',
    status: 'optional',
    provides: ['skeleton-runtime', 'animation-retarget', 'clip-validation'],
  },
  {
    id: 'unreal-export-bridge',
    label: 'Unreal export bridge',
    category: 'export',
    executable: 'aethel-unreal-bridge',
    homepage: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/exporting-unreal-engine-content-to-gltf',
    license: 'Engine/EULA dependent',
    licenseUrl: 'https://www.unrealengine.com/en-US/eula/unreal',
    probe: { command: 'aethel-unreal-bridge', args: ['--version'], expectedExitCode: 0 },
    versionArgs: ['--version'],
    checksumPolicy: 'sha256-required-before-execution',
    downloadPolicy: 'manual-consent-only',
    status: 'optional',
    provides: ['unreal-gltf-export', 'unreal-python-bridge', 'unreal-import-manifest'],
  },
  {
    id: 'unity-export-bridge',
    label: 'Unity export bridge',
    category: 'export',
    executable: 'aethel-unity-bridge',
    homepage: 'https://github.com/atteneder/glTFast',
    license: 'Apache-2.0 bridge / Unity license dependent',
    licenseUrl: 'https://github.com/atteneder/glTFast/blob/main/LICENSE.md',
    probe: { command: 'aethel-unity-bridge', args: ['--version'], expectedExitCode: 0 },
    versionArgs: ['--version'],
    checksumPolicy: 'sha256-required-before-execution',
    downloadPolicy: 'manual-consent-only',
    status: 'optional',
    provides: ['unity-gltf-export', 'unity-import-manifest', 'material-variant-report'],
  },
  {
    id: 'godot-export-bridge',
    label: 'Godot export bridge',
    category: 'export',
    executable: 'godot',
    homepage: 'https://docs.godotengine.org/en/stable/tutorials/assets_pipeline/exporting_3d_scenes.html',
    license: 'MIT',
    licenseUrl: 'https://github.com/godotengine/godot/blob/master/LICENSE.txt',
    probe: { command: 'godot', args: ['--version'], expectedExitCode: 0 },
    versionArgs: ['--version'],
    checksumPolicy: 'sha256-required-before-execution',
    downloadPolicy: 'manual-consent-only',
    status: 'optional',
    provides: ['godot-glb-export', 'godot-import-manifest', 'scene-roundtrip-check'],
  },
]
