import { DEFAULT_OPENROUTER_MODEL_ID, OPENROUTER_MODEL_OPTIONS } from '@/lib/ai/openrouter-models';
import type { SettingDefinition } from './settings-types';

export const DEFAULT_SETTINGS: SettingDefinition[] = [
  {
    key: 'editor.fontSize',
    type: 'number',
    default: 14,
    description: 'Controls the font size in pixels.',
    category: ['Text Editor', 'Font'],
    minimum: 6,
    maximum: 100,
  },
  {
    key: 'editor.fontFamily',
    type: 'string',
    default: "'Fira Code', 'Cascadia Code', Consolas, monospace",
    description: 'Controls the font family.',
    category: ['Text Editor', 'Font'],
  },
  {
    key: 'editor.fontWeight',
    type: 'enum',
    default: '400',
    description: 'Controls the font weight.',
    category: ['Text Editor', 'Font'],
    enum: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  },
  {
    key: 'editor.fontLigatures',
    type: 'boolean',
    default: true,
    description: 'Enables/Disables font ligatures.',
    category: ['Text Editor', 'Font'],
  },
  {
    key: 'editor.lineHeight',
    type: 'number',
    default: 0,
    description: 'Controls the line height. 0 uses the font size.',
    category: ['Text Editor', 'Font'],
    minimum: 0,
    maximum: 150,
  },
  {
    key: 'editor.tabSize',
    type: 'number',
    default: 4,
    description: 'The number of spaces a tab is equal to.',
    category: ['Text Editor'],
    minimum: 1,
    maximum: 8,
  },
  {
    key: 'editor.insertSpaces',
    type: 'boolean',
    default: true,
    description: 'Insert spaces when pressing Tab.',
    category: ['Text Editor'],
  },
  {
    key: 'editor.wordWrap',
    type: 'enum',
    default: 'off',
    description: 'Controls how lines should wrap.',
    category: ['Text Editor'],
    enum: ['off', 'on', 'wordWrapColumn', 'bounded'],
    enumDescriptions: [
      'Lines will never wrap.',
      'Lines will wrap at the viewport width.',
      'Lines will wrap at wordWrapColumn.',
      'Lines will wrap at the minimum of viewport and wordWrapColumn.',
    ],
  },
  {
    key: 'editor.minimap.enabled',
    type: 'boolean',
    default: true,
    description: 'Controls whether the minimap is shown.',
    category: ['Text Editor', 'Minimap'],
  },
  {
    key: 'editor.minimap.side',
    type: 'enum',
    default: 'right',
    description: 'Controls the side where to render the minimap.',
    category: ['Text Editor', 'Minimap'],
    enum: ['left', 'right'],
  },
  {
    key: 'editor.minimap.scale',
    type: 'number',
    default: 1,
    description: 'Scale of content drawn in the minimap.',
    category: ['Text Editor', 'Minimap'],
    minimum: 1,
    maximum: 3,
  },
  {
    key: 'editor.cursorStyle',
    type: 'enum',
    default: 'line',
    description: 'Controls the cursor style.',
    category: ['Text Editor', 'Cursor'],
    enum: ['block', 'block-outline', 'line', 'line-thin', 'underline', 'underline-thin'],
  },
  {
    key: 'editor.cursorBlinking',
    type: 'enum',
    default: 'blink',
    description: 'Controls the cursor animation style.',
    category: ['Text Editor', 'Cursor'],
    enum: ['blink', 'smooth', 'phase', 'expand', 'solid'],
  },
  {
    key: 'editor.renderWhitespace',
    type: 'enum',
    default: 'selection',
    description: 'Controls how whitespace characters are rendered.',
    category: ['Text Editor'],
    enum: ['none', 'boundary', 'selection', 'trailing', 'all'],
  },
  {
    key: 'editor.bracketPairColorization.enabled',
    type: 'boolean',
    default: true,
    description: 'Controls whether bracket pair colorization is enabled.',
    category: ['Text Editor'],
  },
  {
    key: 'editor.autoIndent',
    type: 'enum',
    default: 'full',
    description: 'Controls whether the editor should automatically adjust the indentation.',
    category: ['Text Editor'],
    enum: ['none', 'keep', 'brackets', 'advanced', 'full'],
  },
  {
    key: 'workbench.colorTheme',
    type: 'enum',
    default: 'Aethel Dark',
    description: 'Specifies the color theme used in the workbench.',
    category: ['Workbench', 'Appearance'],
    enum: ['Aethel Dark', 'Aethel Light', 'Unreal Dark', 'VS Code Dark+', 'One Dark Pro'],
  },
  {
    key: 'workbench.iconTheme',
    type: 'enum',
    default: 'icons',
    description: 'Specifies the icon theme used in the workbench.',
    category: ['Workbench', 'Appearance'],
    enum: ['icons', 'material-icons', 'seti', 'none'],
  },
  {
    key: 'workbench.sideBar.location',
    type: 'enum',
    default: 'left',
    description: 'Controls the location of the sidebar.',
    category: ['Workbench', 'Appearance'],
    enum: ['left', 'right'],
  },
  {
    key: 'workbench.activityBar.visible',
    type: 'boolean',
    default: true,
    description: 'Controls whether the activity bar is visible.',
    category: ['Workbench', 'Appearance'],
  },
  {
    key: 'workbench.statusBar.visible',
    type: 'boolean',
    default: true,
    description: 'Controls whether the status bar is visible.',
    category: ['Workbench', 'Appearance'],
  },
  {
    key: 'workbench.editor.tabCloseButton',
    type: 'enum',
    default: 'right',
    description: 'Controls the position of the editor tab close buttons.',
    category: ['Workbench', 'Editor Management'],
    enum: ['off', 'left', 'right'],
  },
  {
    key: 'workbench.editor.showTabs',
    type: 'boolean',
    default: true,
    description: 'Controls whether tabs are shown in the editor.',
    category: ['Workbench', 'Editor Management'],
  },
  {
    key: 'workbench.startupEditor',
    type: 'enum',
    default: 'welcomePage',
    description: 'Controls which editor is shown at startup.',
    category: ['Workbench'],
    enum: ['none', 'welcomePage', 'readme', 'newUntitledFile', 'welcomePageInEmptyWorkbench'],
  },
  {
    key: 'terminal.integrated.fontSize',
    type: 'number',
    default: 14,
    description: 'Controls the font size in pixels of the terminal.',
    category: ['Features', 'Terminal'],
    minimum: 6,
    maximum: 100,
  },
  {
    key: 'terminal.integrated.fontFamily',
    type: 'string',
    default: '',
    description: 'Controls the font family of the terminal. Defaults to editor.fontFamily.',
    category: ['Features', 'Terminal'],
  },
  {
    key: 'terminal.integrated.cursorStyle',
    type: 'enum',
    default: 'block',
    description: 'Controls the style of terminal cursor.',
    category: ['Features', 'Terminal'],
    enum: ['block', 'underline', 'line'],
  },
  {
    key: 'terminal.integrated.scrollback',
    type: 'number',
    default: 1000,
    description: 'Controls the maximum amount of lines the terminal keeps.',
    category: ['Features', 'Terminal'],
    minimum: 0,
    maximum: 100000,
  },
  {
    key: 'files.autoSave',
    type: 'enum',
    default: 'off',
    description: 'Controls auto save of dirty editors.',
    category: ['Text Editor', 'Files'],
    enum: ['off', 'afterDelay', 'onFocusChange', 'onWindowChange'],
  },
  {
    key: 'files.autoSaveDelay',
    type: 'number',
    default: 1000,
    description: 'Controls the delay in milliseconds after which an editor is auto saved.',
    category: ['Text Editor', 'Files'],
    minimum: 0,
  },
  {
    key: 'files.encoding',
    type: 'enum',
    default: 'utf8',
    description: 'The default character set encoding to use.',
    category: ['Text Editor', 'Files'],
    enum: ['utf8', 'utf16le', 'utf16be', 'windows1252', 'iso88591'],
  },
  {
    key: 'files.eol',
    type: 'enum',
    default: 'auto',
    description: 'The default end of line character.',
    category: ['Text Editor', 'Files'],
    enum: ['\\n', '\\r\\n', 'auto'],
    enumDescriptions: ['LF', 'CRLF', 'OS specific'],
  },
  {
    key: 'files.trimTrailingWhitespace',
    type: 'boolean',
    default: false,
    description: 'Trim trailing whitespace when saving a file.',
    category: ['Text Editor', 'Files'],
  },
  {
    key: 'files.insertFinalNewline',
    type: 'boolean',
    default: false,
    description: 'Insert a final newline at the end of the file when saving.',
    category: ['Text Editor', 'Files'],
  },
  {
    key: 'aethel.ai.enabled',
    type: 'boolean',
    default: true,
    description: 'Enable AI-powered features.',
    category: ['Aethel Engine', 'AI'],
  },
  {
    key: 'aethel.ai.inlineCompletion',
    type: 'boolean',
    default: true,
    description: 'Enable inline AI code completion (ghost text).',
    category: ['Aethel Engine', 'AI'],
  },
  {
    key: 'aethel.ai.chatPanel',
    type: 'boolean',
    default: true,
    description: 'Show AI chat panel in the sidebar.',
    category: ['Aethel Engine', 'AI'],
  },
  {
    key: 'aethel.ai.model',
    type: 'enum',
    default: DEFAULT_OPENROUTER_MODEL_ID,
    description: 'The AI model to use for code completion.',
    category: ['Aethel Engine', 'AI'],
    enum: OPENROUTER_MODEL_OPTIONS.map((option) => option.value),
  },
  {
    key: 'aethel.ai.temperature',
    type: 'number',
    default: 0.7,
    description: 'Controls randomness in AI responses (0-1).',
    category: ['Aethel Engine', 'AI'],
    minimum: 0,
    maximum: 1,
  },
  {
    key: 'aethel.blueprint.gridSize',
    type: 'number',
    default: 20,
    description: 'Grid size for blueprint node alignment.',
    category: ['Aethel Engine', 'Blueprint'],
    minimum: 5,
    maximum: 50,
  },
  {
    key: 'aethel.blueprint.snapToGrid',
    type: 'boolean',
    default: true,
    description: 'Snap nodes to grid when moving.',
    category: ['Aethel Engine', 'Blueprint'],
  },
  {
    key: 'aethel.blueprint.showMinimap',
    type: 'boolean',
    default: true,
    description: 'Show minimap in blueprint editor.',
    category: ['Aethel Engine', 'Blueprint'],
  },
  {
    key: 'aethel.blueprint.curveStyle',
    type: 'enum',
    default: 'bezier',
    description: 'Connection wire curve style.',
    category: ['Aethel Engine', 'Blueprint'],
    enum: ['bezier', 'linear', 'step'],
  },
  {
    key: 'aethel.material.previewSize',
    type: 'number',
    default: 256,
    description: 'Preview sphere size in pixels.',
    category: ['Aethel Engine', 'Material Editor'],
    minimum: 64,
    maximum: 512,
  },
  {
    key: 'aethel.material.realTimePreview',
    type: 'boolean',
    default: true,
    description: 'Update preview in real-time while editing.',
    category: ['Aethel Engine', 'Material Editor'],
  },

  // ── Engine: Viewport Fidelity (Block 3A.5 — single control) ───────────────
  {
    key: 'engine.viewport.fidelity',
    type: 'string',
    default: 'balanced',
    description:
      'Preview fidelity: auto | performance | balanced | quality | ultra. Real WebGL2 knobs only — final AAA render remains [HELD].',
    category: ['Engine', 'Rendering'],
  },

  // ── Engine: Simulation ───────────────────────────────────────────────────
  {
    key: 'engine.simulation.gravity',
    type: 'number',
    default: -9.81,
    description: 'Gravity constant applied to Rapier physics world (m/s²).',
    category: ['Engine', 'Simulation'],
    minimum: -50,
    maximum: 0,
  },
  {
    key: 'engine.simulation.enabled',
    type: 'boolean',
    default: false,
    description: 'Run physics simulation in the editor viewport.',
    category: ['Engine', 'Simulation'],
  },
  {
    key: 'engine.simulation.fixedTimestep',
    type: 'number',
    default: 60,
    description: 'Physics tick rate in Hz.',
    category: ['Engine', 'Simulation'],
    minimum: 30,
    maximum: 120,
  },

  // ── Engine: Controls ─────────────────────────────────────────────────────
  {
    key: 'engine.controls.flySpeed',
    type: 'number',
    default: 5,
    description: 'Fly-camera speed (units/sec).',
    category: ['Engine', 'Controls'],
    minimum: 0.5,
    maximum: 100,
  },
  {
    key: 'engine.controls.orbitSensitivity',
    type: 'number',
    default: 1.0,
    description: 'Orbit camera mouse sensitivity multiplier.',
    category: ['Engine', 'Controls'],
    minimum: 0.1,
    maximum: 5,
  },
  {
    key: 'engine.controls.invertY',
    type: 'boolean',
    default: false,
    description: 'Invert vertical look axis in fly-camera mode.',
    category: ['Engine', 'Controls'],
  },

  // ── Engine: Audio ────────────────────────────────────────────────────────
  {
    key: 'engine.audio.masterVolume',
    type: 'number',
    default: 1.0,
    description: 'Master audio volume in editor (0–1).',
    category: ['Engine', 'Audio'],
    minimum: 0,
    maximum: 1,
  },
  {
    key: 'engine.audio.spatialEnabled',
    type: 'boolean',
    default: true,
    description: 'Enable Web Audio API spatial sound in editor playback.',
    category: ['Engine', 'Audio'],
  },

  // ── Engine: VR ──────────────────────────────────────────────────────────
  {
    key: 'engine.vr.enabled',
    type: 'boolean',
    default: false,
    description: 'Enable WebXR VR mode in viewport.',
    category: ['Engine', 'VR'],
  },
  {
    key: 'engine.vr.roomScale',
    type: 'boolean',
    default: true,
    description: 'Use room-scale tracking (standing VR) when available.',
    category: ['Engine', 'VR'],
  },
];
