import type { FluidParams, FluidPreset } from './fluid-simulation.types';

export const DEFAULT_FLUID_PARAMS: FluidParams = {
  particleCount: 500,
  viscosity: 0.01,
  surfaceTension: 0.07,
  restDensity: 1000,
  stiffness: 200,
  particleRadius: 0.05,
  smoothingRadius: 0.2,
  color: '#3b82f6',
  opacity: 0.7,
  gravity: { x: 0, y: -9.81, z: 0 },
  boundarySize: { x: 3, y: 3, z: 3 },
  boundaryPosition: { x: 0, y: 1.5, z: 0 },
  flowDirection: { x: 1, y: 0, z: 0 },
  flowStrength: 0,
  temperature: 20,
  enableSurfaceMeshing: false,
  meshResolution: 32,
};

export const FLUID_PRESETS: FluidPreset[] = [
  {
    id: 'water',
    name: 'Water',
    description: 'Clear liquid with low viscosity',
    params: {
      viscosity: 0.01,
      surfaceTension: 0.07,
      restDensity: 1000,
      stiffness: 200,
      color: '#3b82f6',
      opacity: 0.7,
      temperature: 20,
    },
  },
  {
    id: 'oil',
    name: 'Oil',
    description: 'Viscous liquid with smooth flow',
    params: {
      viscosity: 0.3,
      surfaceTension: 0.03,
      restDensity: 920,
      stiffness: 150,
      color: '#854d0e',
      opacity: 0.85,
      temperature: 25,
    },
  },
  {
    id: 'honey',
    name: 'Honey',
    description: 'Very thick and slow flowing',
    params: {
      viscosity: 0.9,
      surfaceTension: 0.08,
      restDensity: 1400,
      stiffness: 100,
      color: '#f59e0b',
      opacity: 0.9,
      temperature: 20,
    },
  },
  {
    id: 'lava',
    name: 'Lava',
    description: 'Molten rock with high viscosity',
    params: {
      viscosity: 0.7,
      surfaceTension: 0.05,
      restDensity: 2700,
      stiffness: 80,
      color: '#dc2626',
      opacity: 1,
      temperature: 1200,
    },
  },
  {
    id: 'blood',
    name: 'Blood',
    description: 'Biological fluid simulation',
    params: {
      viscosity: 0.04,
      surfaceTension: 0.06,
      restDensity: 1060,
      stiffness: 180,
      color: '#991b1b',
      opacity: 0.95,
      temperature: 37,
    },
  },
  {
    id: 'mercury',
    name: 'Mercury',
    description: 'Dense metallic liquid',
    params: {
      viscosity: 0.02,
      surfaceTension: 0.5,
      restDensity: 13500,
      stiffness: 300,
      color: '#94a3b8',
      opacity: 1,
      temperature: 25,
    },
  },
  {
    id: 'slime',
    name: 'Slime',
    description: 'Non-newtonian goo',
    params: {
      viscosity: 0.5,
      surfaceTension: 0.15,
      restDensity: 1200,
      stiffness: 50,
      color: '#22c55e',
      opacity: 0.8,
      temperature: 20,
    },
  },
  {
    id: 'milk',
    name: 'Milk',
    description: 'Opaque liquid with low viscosity',
    params: {
      viscosity: 0.02,
      surfaceTension: 0.05,
      restDensity: 1030,
      stiffness: 180,
      color: '#f8fafc',
      opacity: 1,
      temperature: 4,
    },
  },
];
