import type { EngineSpineModule } from './engine-spine-modules.types';

export const ENGINE_SPINE_CORE_MODULES = [
  {
    id: 'aaa-render-system',
    label: 'AAA render pipeline',
    domain: 'render',
    status: 'adapter-needed',
    modulePath: 'lib/aaa-render-system.ts',
    targetSurface: 'Viewport render backend',
    userValue: 'Deferred WebGL, HDR, G-buffer evidence, and post-FX become visible in review/final render modes.',
    nextAction: 'Wrap behind a viewport backend adapter before replacing the current renderer.',
    limitation: 'Do not import directly into public or dashboard routes; route through viewport/render readiness.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 1051, risk: 'medium',
  },
  {
    id: 'post-processing-system',
    label: 'Post-processing stack',
    domain: 'render',
    status: 'ready-to-wire',
    modulePath: 'lib/postprocessing/post-processing-system.ts',
    targetSurface: 'Viewport quality controls',
    userValue: 'Bloom, AO, tone mapping, and tasteful cinematic passes move from hidden code to explicit quality toggles.',
    nextAction: 'Expose as review-quality toggles and keep chromatic aberration off by default.',
    limitation: 'Keep expensive passes off until the user selects review/final quality.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 1180, risk: 'low',
  },
  {
    id: 'pixel-streaming',
    label: 'Pixel Streaming cloud lane',
    domain: 'render',
    status: 'visible',
    modulePath: 'lib/pixel-streaming.ts',
    targetSurface: 'Viewport Cloud Stream',
    userValue: 'Unreal/cloud GPU review becomes an optional, cost-aware lane instead of a default browser burden.',
    nextAction: 'Keep Cloud Stream behind explicit user selection and maintain the split signaling/session/codec/cost boundaries.',
    limitation: 'Cloud stream is not free: show cost/status and never promise Unreal quality without a configured backend.',
    loadStrategy: 'dynamic-client-only',
    estimatedLoc: 1244, risk: 'medium',
  },
  {
    id: 'ray-tracing',
    label: 'Ray tracing readiness',
    domain: 'render',
    status: 'adapter-needed',
    modulePath: 'lib/ray-tracing.ts',
    targetSurface: 'Scene Studio render evidence',
    userValue: 'Ray tracing becomes an explicit review lane with p95 frame, denoiser, and human visual evidence.',
    nextAction: 'Expose summary readiness first; require WebGPU/Cloud/Studio Local trace before enabling render claims.',
    limitation: 'Do not call this AAA or final quality from browser evidence alone.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 997, risk: 'high',
  },
  {
    id: 'nanite-virtualized-geometry',
    label: 'Virtualized geometry',
    domain: 'render',
    status: 'adapter-needed',
    modulePath: 'lib/nanite-virtualized-geometry.ts',
    targetSurface: 'Scene Studio geometry budget',
    userValue: 'Meshlet, culling, triangle, and memory budgets become visible before users ask for large worlds.',
    nextAction: 'Keep as a summary adapter until WebGPU or native culling traces exist.',
    limitation: 'Virtualized geometry is not an Unreal Nanite claim; it is an Aethel evidence lane.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 990, risk: 'high',
  },
  {
    id: 'volumetric-clouds',
    label: 'Volumetric atmosphere',
    domain: 'render',
    status: 'adapter-needed',
    modulePath: 'lib/volumetric-clouds.ts',
    targetSurface: 'Scene Studio atmosphere',
    userValue: 'Cloud coverage, raymarch budget, god rays, and shadow cost become reviewable instead of hidden shader work.',
    nextAction: 'Expose atmosphere summary only; route heavy rendering through trace-gated render paths.',
    limitation: 'Cloud raymarching can dominate GPU time; keep it off default preview bundles.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 984, risk: 'high',
  },
  {
    id: 'studio-local-runtime',
    label: 'Studio Local runtime',
    domain: 'native',
    status: 'visible',
    modulePath: 'apps/studio-local/src-tauri/src/lib.rs',
    targetSurface: 'Studio Local capsule',
    userValue: 'Heavy native work can move to Tauri/sidecars instead of slowing browser sessions.',
    nextAction: 'Expose capability probes and handoff state before routing destructive or high-cost jobs locally.',
    limitation: 'Local runtime is capability-gated; browser remains the fallback when probes are absent or stale.',
    loadStrategy: 'native-or-cloud',
    estimatedLoc: 1200, risk: 'medium',
  },
  {
    id: 'behavior-tree-system',
    label: 'Behavior tree runtime',
    domain: 'world',
    status: 'ready-to-wire',
    modulePath: 'lib/ai/behavior-tree-system.tsx',
    targetSurface: 'Scene Studio AI panel',
    userValue: 'NPC logic becomes inspectable instead of living as unconnected engine code.',
    nextAction: 'Add an AI tab in Scene Studio with read-only tree preview first.',
    limitation: 'Start read-only; agent mutations need playtest evidence and scope locks.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 1083, risk: 'medium',
  },
  {
    id: 'world-streaming',
    label: 'World streaming',
    domain: 'world',
    status: 'worker-held',
    modulePath: 'lib/world/world-streaming.tsx',
    targetSurface: 'Level Studio open-world mode',
    userValue: 'Large worlds get chunk visibility, LOD, and held-state controls without blocking the browser main thread.',
    nextAction: 'Keep heavy scan/stream work in worker or sidecar; expose chunk readiness in Level Studio.',
    limitation: 'World scans can freeze the main thread if wired directly.',
    loadStrategy: 'worker-or-sidecar',
    estimatedLoc: 1160, risk: 'high',
  },
  {
    id: 'terrain-system',
    label: 'Terrain generation',
    domain: 'world',
    status: 'worker-held',
    modulePath: 'lib/terrain/terrain-system.ts',
    targetSurface: 'Terrain Studio',
    userValue: 'Heightmap, LOD, brush, foliage, and collider readiness become visible before world generation.',
    nextAction: 'Expose read-only terrain/noise/brush summary and keep generation worker/sidecar held.',
    limitation: 'Large terrain jobs can freeze the UI if imported directly.',
    loadStrategy: 'worker-or-sidecar',
    estimatedLoc: 973, risk: 'high',
  },
  {
    id: 'quest-system',
    label: 'Quest system',
    domain: 'world',
    status: 'ready-to-wire',
    modulePath: 'lib/quests/quest-system.tsx',
    targetSurface: 'Quest Studio',
    userValue: 'Branching mission authoring gets surfaced as a real production system, not only a route label.',
    nextAction: 'Connect existing Quest Studio cards to quest validation and reward previews.',
    limitation: 'Gameplay writes stay disabled until validation packets and rollback are visible.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 1152, risk: 'low',
  },
  {
    id: 'save-manager',
    label: 'Save manager',
    domain: 'systems',
    status: 'ready-to-wire',
    modulePath: 'lib/save/save-manager.tsx',
    targetSurface: 'Level Studio save slots',
    userValue: 'Playable prototypes can expose save/load evidence and rollback-friendly state snapshots.',
    nextAction: 'Add save-slot preview and route all writes through evidence ledger.',
    limitation: 'Save mutations must be project-scoped and reversible.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 1143, risk: 'low',
  },
  {
    id: 'inventory-system',
    label: 'Inventory system',
    domain: 'systems',
    status: 'ready-to-wire',
    modulePath: 'lib/inventory/inventory-system.tsx',
    targetSurface: 'Level Studio gameplay systems',
    userValue: 'Loot, equipment, and item evidence can become testable inside game prototypes.',
    nextAction: 'Surface as read-only inventory model before enabling mutations.',
    limitation: 'Inventory edits need economy/balance evidence before agent writes are allowed.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 1190, risk: 'medium',
  },
  {
    id: 'physics-system',
    label: 'Physics runtime',
    domain: 'systems',
    status: 'ready-to-wire',
    modulePath: 'lib/physics/physics-system.ts',
    targetSurface: 'Level Studio playtest readiness',
    userValue: 'Fixed timestep, solver, collider, and rigid-body evidence can gate playable claims.',
    nextAction: 'Expose physics summary and require replay/playtest evidence before agent mutations.',
    limitation: 'Physics edits can break feel quickly; keep rollback and playtest receipts mandatory.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 973, risk: 'medium',
  },
  {
    id: 'audio-manager',
    label: 'Audio mix runtime',
    domain: 'systems',
    status: 'ready-to-wire',
    modulePath: 'lib/engine/audio-manager.ts',
    targetSurface: 'Film Studio audio mix evidence',
    userValue: 'Sources, groups, snapshots, and peak-level evidence become part of game/film release quality.',
    nextAction: 'Expose mix summary and hold final export until human audio review.',
    limitation: 'Do not autoplay or mutate browser audio graphs from a dashboard surface.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 970, risk: 'medium',
  },
  {
    id: 'spatial-audio-system',
    label: 'Spatial audio',
    domain: 'systems',
    status: 'ready-to-wire',
    modulePath: 'lib/audio/spatial-audio-system.ts',
    targetSurface: 'Film Studio spatial review',
    userValue: 'Listener position, reverb zones, and headset review can be audited before cinematic/game claims.',
    nextAction: 'Expose spatial readiness and require headphone review evidence before final release.',
    limitation: 'Spatial quality depends on device and mix context; agents can prepare evidence, not replace taste.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 926, risk: 'medium',
  },
] satisfies EngineSpineModule[]
