import type { EngineSpineModule } from './engine-spine-modules.types';

export const ENGINE_SPINE_PRODUCTION_MODULES = [
  {
    id: 'multiplayer-system',
    label: 'Multiplayer runtime',
    domain: 'network',
    status: 'adapter-needed',
    modulePath: 'lib/networking/multiplayer-system.tsx',
    targetSurface: 'Creative Hub multiplayer card',
    userValue: 'Collaboration and gameplay networking get a visible readiness model for creators.',
    nextAction: 'Expose readiness, room state, and constraints before adding live mutation controls.',
    limitation: 'Networking is high-risk for reliability; show readiness before live rooms.',
    loadStrategy: 'worker-or-sidecar',
    estimatedLoc: 1170, risk: 'high',
  },
  {
    id: 'cutscene-system',
    label: 'Cutscene system',
    domain: 'film',
    status: 'ready-to-wire',
    modulePath: 'lib/cutscene/cutscene-system.tsx',
    targetSurface: 'Film Studio timeline',
    userValue: 'Shot sequencing, camera moves, and continuity checks become discoverable in Film Studio.',
    nextAction: 'Add a Film Studio tab for cutscene packets and keep export behind review gates.',
    limitation: 'Exports remain review-gated until continuity and render evidence pass.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 1194, risk: 'medium',
  },
  {
    id: 'dialogue-cutscene-system',
    label: 'Dialogue cutscenes',
    domain: 'film',
    status: 'ready-to-wire',
    modulePath: 'lib/dialogue-cutscene-system.ts',
    targetSurface: 'Film Studio dialogue tab',
    userValue: 'Branching dialogue and cinematic beats can be inspected with evidence instead of hidden claims.',
    nextAction: 'Wire read-only dialogue graph preview before voice/lip-sync generation.',
    limitation: 'Voice/lip-sync generation requires license and actor-consent evidence.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 1200, risk: 'medium',
  },
  {
    id: 'capture-system',
    label: 'Capture system',
    domain: 'film',
    status: 'worker-held',
    modulePath: 'lib/capture/capture-system.tsx',
    targetSurface: 'Film Studio review capture',
    userValue: 'Review captures can be recorded as evidence without freezing authoring surfaces.',
    nextAction: 'Keep recording off the main thread and expose capture readiness first.',
    limitation: 'Capture can be CPU/GPU heavy; keep it worker-held until a target is chosen.',
    loadStrategy: 'worker-or-sidecar',
    estimatedLoc: 1192, risk: 'high',
  },
  {
    id: 'aaa-asset-pipeline',
    label: 'AAA asset pipeline',
    domain: 'assets',
    status: 'adapter-needed',
    modulePath: 'lib/aaa-asset-pipeline.ts',
    targetSurface: 'Asset import and marketplace trust',
    userValue: 'GLTF/FBX/USD processing gets tied to license, provenance, and validation evidence.',
    nextAction: 'Expose dependency graph and validation before enabling new importer writes.',
    limitation: 'Asset processing must respect licensing, storage limits, and provenance gates.',
    loadStrategy: 'worker-or-sidecar',
    estimatedLoc: 1147, risk: 'medium',
  },
  {
    id: 'asset-importer',
    label: 'Asset importer',
    domain: 'assets',
    status: 'worker-held',
    modulePath: 'lib/assets/asset-importer.ts',
    targetSurface: 'Level Studio asset intake',
    userValue: 'Models, textures, HDRI, audio, and video imports become governed by provenance, checksum, and quality evidence.',
    nextAction: 'Expose accepted formats and option summary; run heavy import/optimization only in worker or Studio Local.',
    limitation: 'Raw imported assets are not final; LOD, PBR, collision/navmesh, perf, license, and review remain required.',
    loadStrategy: 'worker-or-sidecar',
    estimatedLoc: 984, risk: 'high',
  },
  {
    id: 'dialogue-system',
    label: 'Dialogue runtime',
    domain: 'film',
    status: 'ready-to-wire',
    modulePath: 'lib/dialogue/dialogue-system.tsx',
    targetSurface: 'Film Studio narrative review',
    userValue: 'Dialogue branches, variables, events, localization, and consent evidence become reviewable.',
    nextAction: 'Expose read-only conversation summary before voice/lip-sync generation.',
    limitation: 'Narrative quality and consent stay human-reviewed before final media claims.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 986, risk: 'medium',
  },
  {
    id: 'webxr-vr-system',
    label: 'Immersive XR readiness',
    domain: 'render',
    status: 'worker-held',
    modulePath: 'lib/webxr-vr-system.ts',
    targetSurface: 'Scene Studio XR review',
    userValue: 'VR/AR capability, hand tracking, controller input, teleport, and comfort evidence become explicit.',
    nextAction: 'Keep XR execution device-held; expose capability summary and comfort blockers first.',
    limitation: 'XR can cause comfort/input issues and cannot be implied available without device evidence.',
    loadStrategy: 'worker-or-sidecar',
    estimatedLoc: 982, risk: 'high',
  },
  {
    id: 'motion-matching-system',
    label: 'Motion matching',
    domain: 'systems',
    status: 'worker-held',
    modulePath: 'lib/motion-matching-system.ts',
    targetSurface: 'Animation Studio movement quality',
    userValue: 'Pose database, trajectory, foot locking, and locomotion evidence become part of character quality.',
    nextAction: 'Expose config/database summary; keep pose search worker-held until playtest evidence exists.',
    limitation: 'Animation feel cannot be claimed from config alone; it needs playtest and human review.',
    loadStrategy: 'worker-or-sidecar',
    estimatedLoc: 980, risk: 'high',
  },
  {
    id: 'haptics-system',
    label: 'Haptics feedback',
    domain: 'systems',
    status: 'ready-to-wire',
    modulePath: 'lib/input/haptics-system.tsx',
    targetSurface: 'Level Studio game feel',
    userValue: 'Gamepad/mobile haptics become accessibility-aware evidence, not hidden feedback magic.',
    nextAction: 'Expose haptic profile summary with accessibility toggles and device support state.',
    limitation: 'Haptics must remain optional, device-gated, and accessibility-reviewed.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 974, risk: 'medium',
  },
  {
    id: 'weather-system',
    label: 'Weather runtime',
    domain: 'world',
    status: 'adapter-needed',
    modulePath: 'lib/environment/weather-system.tsx',
    targetSurface: 'Scene Studio environment review',
    userValue: 'Weather, wind, lightning, visibility, and lighting impact become governed scene evidence.',
    nextAction: 'Expose state/transition summary and require lighting/perf evidence before world claims.',
    limitation: 'Weather affects gameplay and rendering; keep heavy effects off until reviewed.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 970, risk: 'medium',
  },
  {
    id: 'camera-system',
    label: 'Camera runtime',
    domain: 'film',
    status: 'ready-to-wire',
    modulePath: 'lib/camera/camera-system.tsx',
    targetSurface: 'Scene Studio camera review',
    userValue: 'Camera mode, follow, orbit, shake, and path evidence become central to game/film quality.',
    nextAction: 'Expose camera summary and require continuity/comfort review before final camera claims.',
    limitation: 'Camera feel is taste-sensitive and must stay human-reviewed.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 969, risk: 'medium',
  },
  {
    id: 'command-handlers',
    label: 'Command handlers',
    domain: 'systems',
    status: 'adapter-needed',
    modulePath: 'lib/commands/command-handlers.tsx',
    targetSurface: 'IDE command bus',
    userValue: 'Clipboard, undo/redo, file ops, search, navigation, and command events get one visible authority.',
    nextAction: 'Split command domains before adding more IDE actions.',
    limitation: 'Do not create parallel command buses or import command handlers into unrelated surfaces.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 995, risk: 'high',
  },
  {
    id: 'theia-systems-hooks',
    label: 'Theia compatibility hooks',
    domain: 'systems',
    status: 'adapter-needed',
    modulePath: 'lib/hooks/useTheiaSystemsHooks.ts',
    targetSurface: 'IDE compatibility boundary',
    userValue: 'Search, theme, keybindings, notifications, command palette, and AI hooks stay explicitly scoped.',
    nextAction: 'Split hooks by concern before wiring them into premium IDE surfaces.',
    limitation: 'Compatibility hooks must not leak into public/dashboard/default Studio bundles.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 989, risk: 'high',
  },
  {
    id: 'workspace-service',
    label: 'Workspace service',
    domain: 'systems',
    status: 'adapter-needed',
    modulePath: 'lib/workspace/workspace-service.ts',
    targetSurface: 'IDE workspace runtime',
    userValue: 'File IO, watchers, search, dirty files, and configuration become one governed workspace boundary.',
    nextAction: 'Split workspace IO/watch/search/configuration before expanding filesystem features.',
    limitation: 'Workspace state must not compete with Project Brain, Yjs, or mission ledger state.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 985, risk: 'high',
  },
  {
    id: 'event-bus-system',
    label: 'Runtime event bus',
    domain: 'systems',
    status: 'adapter-needed',
    modulePath: 'lib/events/event-bus-system.tsx',
    targetSurface: 'Runtime event governance',
    userValue: 'Events, channels, signals, and decorators become governed instead of hidden app-wide coupling.',
    nextAction: 'Split bus/channels/signals/hooks and require channel ownership before new events.',
    limitation: 'Unowned event buses create invisible coupling and parallel runtime risk.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 985, risk: 'high',
  },
  {
    id: 'health-check',
    label: 'Platform health runtime',
    domain: 'native',
    status: 'ready-to-wire',
    modulePath: 'lib/health-check.ts',
    targetSurface: 'Admin/platform health',
    userValue: 'Liveness, metrics, uptime, alerts, and redacted health evidence become operationally trustworthy.',
    nextAction: 'Keep health logic server/platform-owned and split UI hooks from runtime checks.',
    limitation: 'Health details must be redacted in user/admin screenshots and evidence exports.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 970, risk: 'medium',
  },
  {
    id: 'legacy-physics-engine',
    label: 'Legacy physics engine boundary',
    domain: 'systems',
    status: 'adapter-needed',
    modulePath: 'lib/engine/physics-engine.ts',
    targetSurface: 'Level Studio physics compatibility',
    userValue: 'Existing physics world, bodies, and collider code becomes a migration-safe compatibility lane instead of a hidden parallel runtime.',
    nextAction: 'Keep read-only readiness and migrate writes through the canonical physics-system adapter.',
    limitation: 'Legacy physics must not compete with the canonical physics contract or ship playable claims without replay evidence.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 970, risk: 'high',
  },
  {
    id: 'quest-mission-system',
    label: 'Quest mission runtime',
    domain: 'world',
    status: 'ready-to-wire',
    modulePath: 'lib/quest-mission-system.ts',
    targetSurface: 'Quest Studio mission validation',
    userValue: 'Quest branches, rewards, markers, and UI packets become governed production evidence for game prototypes and vertical slices.',
    nextAction: 'Expose branch/reward/localization summaries and require rollback before agent quest writes.',
    limitation: 'Quest generation is not final gameplay until branch coverage, balance, localization, and playtest evidence pass.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 963, risk: 'medium',
  },
  {
    id: 'ecs-dots-system',
    label: 'DOTS-style ECS runtime',
    domain: 'systems',
    status: 'worker-held',
    modulePath: 'lib/ecs-dots-system.ts',
    targetSurface: 'Level Studio systems readiness',
    userValue: 'World, component registry, scheduler, and job system readiness can support serious game simulation without browser-thread surprises.',
    nextAction: 'Expose scheduler/component summaries; keep job execution worker-held until traces and playtests are recorded.',
    limitation: 'Broad ECS jobs can silently freeze sessions; never run them in public/dashboard/default Studio bundles.',
    loadStrategy: 'worker-or-sidecar',
    estimatedLoc: 960, risk: 'high',
  },
  {
    id: 'level-streaming-system',
    label: 'Level streaming runtime',
    domain: 'world',
    status: 'worker-held',
    modulePath: 'lib/streaming/level-streaming-system.tsx',
    targetSurface: 'Level Studio streaming readiness',
    userValue: 'Loaded levels, memory pressure, transitions, and cache state become visible before users build larger worlds.',
    nextAction: 'Expose streaming readiness and keep load/unload execution worker or sidecar held.',
    limitation: 'Streaming claims require chunk budgets, memory pressure evidence, transition traces, and rollback readiness.',
    loadStrategy: 'worker-or-sidecar',
    estimatedLoc: 959, risk: 'high',
  },
  {
    id: 'networking-multiplayer',
    label: 'Multiplayer netcode runtime',
    domain: 'network',
    status: 'worker-held',
    modulePath: 'lib/networking-multiplayer.ts',
    targetSurface: 'Level Studio multiplayer readiness',
    userValue: 'Network client, prediction, rollback, WebRTC, and matchmaking become auditable before any live gameplay promise.',
    nextAction: 'Expose latency, authority, and rollback readiness; keep live rooms sandbox or staging held.',
    limitation: 'Multiplayer quality depends on server authority, latency traces, rollback evidence, and abuse controls.',
    loadStrategy: 'worker-or-sidecar',
    estimatedLoc: 958, risk: 'high',
  },
  {
    id: 'foliage-system',
    label: 'Foliage density runtime',
    domain: 'world',
    status: 'adapter-needed',
    modulePath: 'lib/foliage-system.ts',
    targetSurface: 'Foliage Studio density evidence',
    userValue: 'Instanced foliage, grass, trees, clusters, and painting become quality-controlled instead of just decorative code.',
    nextAction: 'Expose instance, LOD, culling, and frame-trace readiness before dense foliage applies to scenes.',
    limitation: 'Dense foliage can dominate GPU cost; keep it render-gated until culling and performance evidence exist.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 947, risk: 'high',
  },
  {
    id: 'virtual-texture-system',
    label: 'Virtual texture runtime',
    domain: 'render',
    status: 'worker-held',
    modulePath: 'lib/virtual-texture-system.ts',
    targetSurface: 'Material Studio texture budget',
    userValue: 'Large material sets can expose tile cache, feedback buffer, and memory budget evidence before heavy texture work runs.',
    nextAction: 'Expose tile/cache summaries and keep streaming/feedback execution worker-held.',
    limitation: 'Virtual textures require cache-hit, memory, and render-trace evidence before high-resolution material claims.',
    loadStrategy: 'worker-or-sidecar',
    estimatedLoc: 926, risk: 'high',
  },
  {
    id: 'ai-audio-engine',
    label: 'AI emotional audio runtime',
    domain: 'film',
    status: 'ready-to-wire',
    modulePath: 'lib/ai-audio-engine.ts',
    targetSurface: 'Audio Studio emotion review',
    userValue: 'Emotional score, context, and adaptive audio logic become evidence-backed instead of hidden generation magic.',
    nextAction: 'Expose emotion/context summaries and hold output until consent, mix, and human audio review exist.',
    limitation: 'AI audio is taste and consent sensitive; agents prepare evidence, humans approve final use.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 899, risk: 'medium',
  },
  {
    id: 'day-night-cycle',
    label: 'Day/night cycle runtime',
    domain: 'world',
    status: 'ready-to-wire',
    modulePath: 'lib/environment/day-night-cycle.tsx',
    targetSurface: 'Scene Studio environment timeline',
    userValue: 'Time of day, season, sky, sun direction, and lighting transitions become auditable world-building evidence.',
    nextAction: 'Expose time/sky summaries and require lighting/performance/playtest evidence before world claims.',
    limitation: 'Time-based state affects gameplay and rendering; keep transitions reviewed and trace-backed.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 894, risk: 'medium',
  },
  {
    id: 'asset-import-pipeline-legacy',
    label: 'Asset import pipeline boundary',
    domain: 'assets',
    status: 'worker-held',
    modulePath: 'lib/asset-import-pipeline.ts',
    targetSurface: 'Level Studio import governance',
    userValue: 'Legacy format support and import progress can feed the same provenance, checksum, and quality ledger as the canonical importer.',
    nextAction: 'Expose supported formats and option summaries; route heavy conversion through worker or Studio Local.',
    limitation: 'Raw imports are never final; license, LOD, PBR, collision/navmesh, performance, and review evidence are mandatory.',
    loadStrategy: 'worker-or-sidecar',
    estimatedLoc: 882, risk: 'high',
  },
  {
    id: 'browser-audio-engine',
    label: 'Browser audio engine',
    domain: 'systems',
    status: 'ready-to-wire',
    modulePath: 'lib/audio-engine.ts',
    targetSurface: 'Audio Studio playback boundary',
    userValue: 'Tracks, channels, effects, and playback state become mix evidence without surprising autoplay behavior.',
    nextAction: 'Expose channel/mix summaries and keep playback user-initiated with peak-level review.',
    limitation: 'Browser audio must respect autoplay, accessibility, and human mix review before final claims.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 849, risk: 'medium',
  },
  {
    id: 'post-process-volume',
    label: 'Post-process volume runtime',
    domain: 'render',
    status: 'adapter-needed',
    modulePath: 'lib/post-process-volume.ts',
    targetSurface: 'Scene Studio shot volumes',
    userValue: 'Shot and zone-specific post-processing can be reviewed as a governed quality layer for games and films.',
    nextAction: 'Expose volume priority/blend summaries and require shot performance traces before final render claims.',
    limitation: 'Post-process volumes can hide GPU cost; keep them review-quality until trace and human visual review pass.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 845, risk: 'medium',
  },
  {
    id: 'aaa-material-system',
    label: 'AAA material system',
    domain: 'assets',
    status: 'adapter-needed',
    modulePath: 'lib/aaa-material-system.ts',
    targetSurface: 'Material Studio PBR evidence',
    userValue: 'Advanced PBR, material library, and shader graph compilation become visible quality gates for assets and scenes.',
    nextAction: 'Expose PBR completeness, texture license, shader preview, and performance evidence before material finalization.',
    limitation: 'Material quality is not final without texture provenance, PBR completeness, shader preview, and performance traces.',
    loadStrategy: 'summary-adapter',
    estimatedLoc: 844, risk: 'high',
  },
] satisfies EngineSpineModule[]
