import type { Asset } from './content-browser-core'

export function createInitialContentBrowserAssets(): Asset[] {
  return [
    {
      id: "1",
      name: "Characters",
      type: "folder",
      path: "/Characters",
      size: 0,
      createdAt: new Date(),
      modifiedAt: new Date(),
      children: [],
    },
    {
      id: "2",
      name: "Environments",
      type: "folder",
      path: "/Environments",
      size: 0,
      createdAt: new Date(),
      modifiedAt: new Date(),
      children: [],
    },
    {
      id: "3",
      name: "Materials",
      type: "folder",
      path: "/Materials",
      size: 0,
      createdAt: new Date(),
      modifiedAt: new Date(),
      children: [],
    },
    {
      id: "4",
      name: "Audio",
      type: "folder",
      path: "/Audio",
      size: 0,
      createdAt: new Date(),
      modifiedAt: new Date(),
      children: [],
    },
    {
      id: "5",
      name: "Blueprints",
      type: "folder",
      path: "/Blueprints",
      size: 0,
      createdAt: new Date(),
      modifiedAt: new Date(),
      children: [],
    },
    {
      id: "6",
      name: "PlayerCharacter.fbx",
      type: "mesh",
      path: "/Characters/PlayerCharacter.fbx",
      size: 2500000,
      createdAt: new Date(),
      modifiedAt: new Date(),
      starred: true,
    },
    {
      id: "7",
      name: "Grass_Albedo.png",
      type: "texture",
      path: "/Materials/Grass_Albedo.png",
      size: 1200000,
      createdAt: new Date(),
      modifiedAt: new Date(),
    },
    {
      id: "8",
      name: "M_Ground.material",
      type: "material",
      path: "/Materials/M_Ground.material",
      size: 5000,
      createdAt: new Date(),
      modifiedAt: new Date(),
    },
    {
      id: "9",
      name: "BP_Enemy.blueprint",
      type: "blueprint",
      path: "/Blueprints/BP_Enemy.blueprint",
      size: 15000,
      createdAt: new Date(),
      modifiedAt: new Date(),
      starred: true,
    },
    {
      id: "10",
      name: "Footsteps.wav",
      type: "audio",
      path: "/Audio/Footsteps.wav",
      size: 800000,
      createdAt: new Date(),
      modifiedAt: new Date(),
    },
    {
      id: "11",
      name: "MainLevel.level",
      type: "level",
      path: "/Environments/MainLevel.level",
      size: 5000000,
      createdAt: new Date(),
      modifiedAt: new Date(),
    },
    {
      id: "12",
      name: "Fire.vfx",
      type: "particle",
      path: "/Effects/Fire.vfx",
      size: 25000,
      createdAt: new Date(),
      modifiedAt: new Date(),
    },
  ]
}
