import { NextRequest, NextResponse } from 'next/server';

export async function GET(request: NextRequest) {
  const extensions = [
    {
      id: 'python-lsp',
      name: 'python-lsp',
      displayName: 'Python Language Server',
      description: 'Full Python language support with IntelliSense, debugging, and refactoring powered by Pylance',
      version: '1.0.0',
      publisher: 'Aethel',
      icon: '🐍',
      downloads: 150000,
      rating: 4.8,
      categories: ['languages', 'debuggers'],
      tags: ['python', 'lsp', 'intellisense', 'pylance'],
      repository: 'https://github.com/aethel/python-lsp',
      license: 'MIT',
      installed: false,
      size: '15.2 MB',
      lastUpdated: '2025-12-01'
    },
    {
      id: 'typescript-lsp',
      name: 'typescript-lsp',
      displayName: 'TypeScript Language Server',
      description: 'TypeScript and JavaScript language support with advanced IntelliSense, refactoring, and type checking',
      version: '2.1.0',
      publisher: 'Aethel',
      icon: '📘',
      downloads: 200000,
      rating: 4.9,
      categories: ['languages'],
      tags: ['typescript', 'javascript', 'lsp', 'tsserver'],
      repository: 'https://github.com/aethel/typescript-lsp',
      license: 'MIT',
      installed: false,
      size: '22.5 MB',
      lastUpdated: '2025-12-05'
    },
    {
      id: 'go-lsp',
      name: 'go-lsp',
      displayName: 'Go Language Server',
      description: 'Go language support powered by gopls with code completion, navigation, and refactoring',
      version: '1.5.0',
      publisher: 'Aethel',
      icon: '🐹',
      downloads: 80000,
      rating: 4.7,
      categories: ['languages', 'debuggers'],
      tags: ['go', 'golang', 'lsp', 'gopls'],
      repository: 'https://github.com/aethel/go-lsp',
      license: 'MIT',
      installed: false,
      size: '18.7 MB',
      lastUpdated: '2025-11-28'
    },
    {
      id: 'rust-analyzer',
      name: 'rust-analyzer',
      displayName: 'Rust Analyzer',
      description: 'Rust language support with rust-analyzer providing fast and accurate code intelligence',
      version: '0.3.0',
      publisher: 'Aethel',
      icon: '🦀',
      downloads: 60000,
      rating: 4.9,
      categories: ['languages', 'debuggers'],
      tags: ['rust', 'lsp', 'cargo', 'rust-analyzer'],
      repository: 'https://github.com/aethel/rust-analyzer',
      license: 'MIT',
      installed: false,
      size: '25.3 MB',
      lastUpdated: '2025-12-03'
    },
    {
      id: 'java-lsp',
      name: 'java-lsp',
      displayName: 'Java Language Server',
      description: 'Java language support powered by Eclipse JDT.LS with Maven and Gradle integration',
      version: '1.8.0',
      publisher: 'Aethel',
      icon: '☕',
      downloads: 120000,
      rating: 4.6,
      categories: ['languages', 'debuggers'],
      tags: ['java', 'lsp', 'maven', 'gradle'],
      repository: 'https://github.com/aethel/java-lsp',
      license: 'EPL-2.0',
      installed: false,
      size: '45.8 MB',
      lastUpdated: '2025-11-30'
    },
    {
      id: 'csharp-lsp',
      name: 'csharp-lsp',
      displayName: 'C# Language Server',
      description: 'C# language support with OmniSharp providing IntelliSense and debugging for .NET',
      version: '2.0.0',
      publisher: 'Aethel',
      icon: '🔷',
      downloads: 95000,
      rating: 4.7,
      categories: ['languages', 'debuggers'],
      tags: ['csharp', 'dotnet', 'lsp', 'omnisharp'],
      repository: 'https://github.com/aethel/csharp-lsp',
      license: 'MIT',
      installed: false,
      size: '32.1 MB',
      lastUpdated: '2025-12-02'
    },
    {
      id: 'cpp-lsp',
      name: 'cpp-lsp',
      displayName: 'C/C++ Language Server',
      description: 'C and C++ language support powered by clangd with code completion and navigation',
      version: '1.3.0',
      publisher: 'Aethel',
      icon: '⚙️',
      downloads: 110000,
      rating: 4.8,
      categories: ['languages', 'debuggers'],
      tags: ['cpp', 'c', 'lsp', 'clangd'],
      repository: 'https://github.com/aethel/cpp-lsp',
      license: 'MIT',
      installed: false,
      size: '28.9 MB',
      lastUpdated: '2025-11-29'
    },
    {
      id: 'php-lsp',
      name: 'php-lsp',
      displayName: 'PHP Language Server',
      description: 'PHP language support with Intelephense providing code intelligence and refactoring',
      version: '1.6.0',
      publisher: 'Aethel',
      icon: '🐘',
      downloads: 70000,
      rating: 4.5,
      categories: ['languages'],
      tags: ['php', 'lsp', 'intelephense'],
      repository: 'https://github.com/aethel/php-lsp',
      license: 'MIT',
      installed: false,
      size: '12.4 MB',
      lastUpdated: '2025-11-27'
    },
    {
      id: 'ai-code-assistant',
      name: 'ai-code-assistant',
      displayName: 'AI Code Assistant Pro',
      description: 'Advanced AI-powered code completion, generation, and refactoring with multi-model support',
      version: '3.0.0',
      publisher: 'Aethel',
      icon: '🤖',
      downloads: 300000,
      rating: 4.9,
      categories: ['ai-tools', 'productivity'],
      tags: ['ai', 'completion', 'generation', 'copilot'],
      repository: 'https://github.com/aethel/ai-code-assistant',
      license: 'MIT',
      installed: true,
      size: '8.5 MB',
      lastUpdated: '2025-12-08'
    },
    {
      id: 'theme-dracula',
      name: 'theme-dracula',
      displayName: 'Dracula Theme',
      description: 'Dark theme with vibrant colors inspired by the Dracula color scheme',
      version: '2.0.0',
      publisher: 'Dracula',
      icon: '🧛',
      downloads: 500000,
      rating: 4.8,
      categories: ['themes'],
      tags: ['theme', 'dark', 'dracula', 'color-scheme'],
      repository: 'https://github.com/dracula/dracula-theme',
      license: 'MIT',
      installed: false,
      size: '1.2 MB',
      lastUpdated: '2025-11-25'
    },
    {
      id: 'theme-nord',
      name: 'theme-nord',
      displayName: 'Nord Theme',
      description: 'Arctic, north-bluish color palette with clean and elegant design',
      version: '1.5.0',
      publisher: 'Nord',
      icon: '❄️',
      downloads: 350000,
      rating: 4.7,
      categories: ['themes'],
      tags: ['theme', 'dark', 'nord', 'minimal'],
      repository: 'https://github.com/nordtheme/nord',
      license: 'MIT',
      installed: false,
      size: '0.9 MB',
      lastUpdated: '2025-11-20'
    },
    {
      id: 'prettier-formatter',
      name: 'prettier-formatter',
      displayName: 'Prettier Code Formatter',
      description: 'Opinionated code formatter supporting JavaScript, TypeScript, CSS, HTML, and more',
      version: '5.0.0',
      publisher: 'Prettier',
      icon: '💅',
      downloads: 800000,
      rating: 4.7,
      categories: ['formatters'],
      tags: ['formatter', 'prettier', 'style', 'beautify'],
      repository: 'https://github.com/prettier/prettier',
      license: 'MIT',
      installed: false,
      size: '3.2 MB',
      lastUpdated: '2025-12-04'
    },
    {
      id: 'eslint-linter',
      name: 'eslint-linter',
      displayName: 'ESLint',
      description: 'JavaScript and TypeScript linter with configurable rules and auto-fix capabilities',
      version: '8.0.0',
      publisher: 'ESLint',
      icon: '🔍',
      downloads: 900000,
      rating: 4.6,
      categories: ['linters'],
      tags: ['linter', 'eslint', 'javascript', 'typescript'],
      repository: 'https://github.com/eslint/eslint',
      license: 'MIT',
      installed: false,
      size: '5.7 MB',
      lastUpdated: '2025-12-06'
    },
    {
      id: 'debugger-node',
      name: 'debugger-node',
      displayName: 'Node.js Debugger',
      description: 'Debug Node.js applications with breakpoints, stepping, and variable inspection',
      version: '1.2.0',
      publisher: 'Aethel',
      icon: '🐛',
      downloads: 180000,
      rating: 4.8,
      categories: ['debuggers'],
      tags: ['debugger', 'nodejs', 'dap', 'breakpoints'],
      repository: 'https://github.com/aethel/debugger-node',
      license: 'MIT',
      installed: false,
      size: '6.3 MB',
      lastUpdated: '2025-12-01'
    },
    {
      id: 'debugger-python',
      name: 'debugger-python',
      displayName: 'Python Debugger',
      description: 'Debug Python applications with debugpy supporting breakpoints and remote debugging',
      version: '1.4.0',
      publisher: 'Aethel',
      icon: '🐍',
      downloads: 140000,
      rating: 4.7,
      categories: ['debuggers'],
      tags: ['debugger', 'python', 'dap', 'debugpy'],
      repository: 'https://github.com/aethel/debugger-python',
      license: 'MIT',
      installed: false,
      size: '8.1 MB',
      lastUpdated: '2025-11-28'
    },
    {
      id: 'git-graph',
      name: 'git-graph',
      displayName: 'Git Graph',
      description: 'Visualize git repository history with interactive graph and commit details',
      version: '2.3.0',
      publisher: 'Aethel',
      icon: '🌳',
      downloads: 220000,
      rating: 4.9,
      categories: ['productivity', 'scm'],
      tags: ['git', 'graph', 'history', 'visualization'],
      repository: 'https://github.com/aethel/git-graph',
      license: 'MIT',
      installed: false,
      size: '4.5 MB',
      lastUpdated: '2025-12-07'
    },
    {
      id: 'vim-keybindings',
      name: 'vim-keybindings',
      displayName: 'Vim Keybindings',
      description: 'Vim emulation with modal editing and customizable key mappings',
      version: '3.1.0',
      publisher: 'Vim',
      icon: '⌨️',
      downloads: 250000,
      rating: 4.6,
      categories: ['keymaps'],
      tags: ['vim', 'keybindings', 'modal', 'editor'],
      repository: 'https://github.com/vim/vim-keybindings',
      license: 'MIT',
      installed: false,
      size: '2.8 MB',
      lastUpdated: '2025-11-26'
    },
    {
      id: 'live-share',
      name: 'live-share',
      displayName: 'Live Share',
      description: 'Real-time collaborative editing with shared terminals and debugging sessions',
      version: '1.7.0',
      publisher: 'Aethel',
      icon: '👥',
      downloads: 190000,
      rating: 4.8,
      categories: ['productivity', 'collaboration'],
      tags: ['collaboration', 'live-share', 'pair-programming'],
      repository: 'https://github.com/aethel/live-share',
      license: 'MIT',
      installed: false,
      size: '11.2 MB',
      lastUpdated: '2025-12-05'
    }
  ];

  return NextResponse.json({
    success: true,
    extensions,
    total: extensions.length
  });
}
