import { GameplayAbilitySpec, GameplayTag } from '../gameplay-ability-system';

/**
 * Habilidades predefinidas para uso rápido
 */
export const PRESET_ABILITIES = {
  /** Fireball - Dano de área com DOT */
  fireball: (): GameplayAbilitySpec => ({
    id: 'ability.fireball',
    name: 'Fireball',
    description: 'Lança uma bola de fogo que causa dano em área',
    icon: '🔥',
    activationType: 'triggered',
    targetingMode: 'aoe',
    costs: [{ attribute: 'mana', value: 30 }],
    cooldown: { duration: 5, tags: [GameplayTag.fromString('cooldown.fire')] },
    tags: {
      ability: [GameplayTag.fromString('ability.fire'), GameplayTag.fromString('ability.magic')],
      cancel: [],
      block: [GameplayTag.fromString('state.silenced')],
      activation: { required: [], blocked: [GameplayTag.fromString('state.stunned')] },
    },
    effects: [{
      id: 'effect.burn',
      name: 'Burning',
      description: 'Causa dano ao longo do tempo',
      durationType: 'duration',
      duration: 4,
      period: 1,
      modifiers: [],
      grantedTags: [GameplayTag.fromString('debuff.burning')],
      applicationTags: [],
      removalTags: [],
      requiredTags: [],
      blockedTags: [],
      stackingPolicy: 'refresh',
      maxStacks: 3,
    }],
    range: 20,
    aoeRadius: 5,
  }),

  /** Heal - Cura instantânea */
  heal: (): GameplayAbilitySpec => ({
    id: 'ability.heal',
    name: 'Heal',
    description: 'Restaura pontos de vida',
    icon: '💚',
    activationType: 'triggered',
    targetingMode: 'self',
    costs: [{ attribute: 'mana', value: 20 }],
    cooldown: { duration: 3, tags: [GameplayTag.fromString('cooldown.heal')] },
    tags: {
      ability: [GameplayTag.fromString('ability.heal'), GameplayTag.fromString('ability.magic')],
      cancel: [],
      block: [],
      activation: { required: [], blocked: [GameplayTag.fromString('state.stunned')] },
    },
    effects: [{
      id: 'effect.healing',
      name: 'Healing',
      description: 'Restaura vida instantaneamente',
      durationType: 'instant',
      modifiers: [{
        id: 'mod.heal',
        attribute: 'health',
        operation: 'add',
        value: 50,
      }],
      grantedTags: [],
      applicationTags: [],
      removalTags: [],
      requiredTags: [],
      blockedTags: [],
      stackingPolicy: 'none',
      maxStacks: 1,
    }],
  }),

  /** Sprint - Buff de velocidade temporário */
  sprint: (): GameplayAbilitySpec => ({
    id: 'ability.sprint',
    name: 'Sprint',
    description: 'Aumenta a velocidade de movimento temporariamente',
    icon: '⚡',
    activationType: 'triggered',
    targetingMode: 'self',
    costs: [{ attribute: 'stamina', value: 25 }],
    cooldown: { duration: 10, tags: [GameplayTag.fromString('cooldown.movement')] },
    tags: {
      ability: [GameplayTag.fromString('ability.movement')],
      cancel: [],
      block: [],
      activation: { required: [], blocked: [GameplayTag.fromString('state.rooted')] },
    },
    effects: [{
      id: 'effect.sprint',
      name: 'Sprinting',
      description: 'Velocidade aumentada em 50%',
      durationType: 'duration',
      duration: 5,
      modifiers: [{
        id: 'mod.speed',
        attribute: 'moveSpeed',
        operation: 'multiply',
        value: 1.5,
      }],
      grantedTags: [GameplayTag.fromString('buff.speed')],
      applicationTags: [],
      removalTags: [],
      requiredTags: [],
      blockedTags: [],
      stackingPolicy: 'refresh',
      maxStacks: 1,
    }],
  }),

  /** Shield - Escudo absorvedor de dano */
  shield: (): GameplayAbilitySpec => ({
    id: 'ability.shield',
    name: 'Shield',
    description: 'Cria um escudo que absorve dano',
    icon: '🛡️',
    activationType: 'triggered',
    targetingMode: 'self',
    costs: [{ attribute: 'mana', value: 40 }],
    cooldown: { duration: 15, tags: [GameplayTag.fromString('cooldown.defensive')] },
    tags: {
      ability: [GameplayTag.fromString('ability.defensive')],
      cancel: [],
      block: [],
      activation: { required: [], blocked: [] },
    },
    effects: [{
      id: 'effect.shield',
      name: 'Shielded',
      description: 'Absorve até 100 pontos de dano',
      durationType: 'duration',
      duration: 10,
      modifiers: [{
        id: 'mod.shield',
        attribute: 'defense',
        operation: 'add',
        value: 100,
      }],
      grantedTags: [GameplayTag.fromString('buff.shielded')],
      applicationTags: [],
      removalTags: [],
      requiredTags: [],
      blockedTags: [],
      stackingPolicy: 'override',
      maxStacks: 1,
    }],
  }),
};
