import type { PlanLimits, PlanTier } from './permissions.types'

export const PlanLimitsConfig: Record<PlanTier, PlanLimits> = {
  free: {
    maxProjects: 2,
    maxFilesPerProject: 50,
    maxStorageGB: 1,
    maxAssetsPerProject: 20,
    maxCollaborators: 0,
    aiTokensPerMonth: 10_000,
    aiRequestsPerMinute: 5,
    maxBuildMinutesPerMonth: 60,
    supportLevel: 'community',
    features: [
      'project:create',
      'project:read',
      'project:update',
      'ai:chat',
      'engine:blueprint',
      'marketplace:browse',
    ],
  },
  
  starter: {
    maxProjects: 5,
    maxFilesPerProject: 200,
    maxStorageGB: 5,
    maxAssetsPerProject: 100,
    maxCollaborators: 1,
    aiTokensPerMonth: 100_000,
    aiRequestsPerMinute: 20,
    maxBuildMinutesPerMonth: 300,
    supportLevel: 'email',
    features: [
      'project:create',
      'project:read',
      'project:update',
      'project:delete',
      'project:export',
      'ai:chat',
      'ai:stream',
      'engine:blueprint',
      'engine:vfx',
      'engine:terrain',
      'marketplace:browse',
      'marketplace:purchase',
    ],
  },
  
  basic: {
    maxProjects: 15,
    maxFilesPerProject: 500,
    maxStorageGB: 20,
    maxAssetsPerProject: 500,
    maxCollaborators: 3,
    aiTokensPerMonth: 500_000,
    aiRequestsPerMinute: 60,
    maxBuildMinutesPerMonth: 1000,
    supportLevel: 'email',
    features: [
      'project:create',
      'project:read',
      'project:update',
      'project:delete',
      'project:export',
      'project:share',
      'ai:chat',
      'ai:stream',
      'ai:advanced',
      'engine:blueprint',
      'engine:vfx',
      'engine:terrain',
      'engine:animation',
      'engine:physics',
      'collab:invite',
      'collab:comments',
      'marketplace:browse',
      'marketplace:purchase',
      'marketplace:review',
    ],
  },
  
  pro: {
    maxProjects: 50,
    maxFilesPerProject: 2000,
    maxStorageGB: 100,
    maxAssetsPerProject: 2000,
    maxCollaborators: 10,
    aiTokensPerMonth: 2_000_000,
    aiRequestsPerMinute: 120,
    maxBuildMinutesPerMonth: 5000,
    supportLevel: 'priority',
    features: [
      'project:create',
      'project:read',
      'project:update',
      'project:delete',
      'project:export',
      'project:share',
      'project:collaborate',
      'ai:chat',
      'ai:stream',
      'ai:advanced',
      'engine:blueprint',
      'engine:vfx',
      'engine:terrain',
      'engine:animation',
      'engine:physics',
      'engine:networking',
      'collab:invite',
      'collab:realtime',
      'collab:comments',
      'collab:review',
      'marketplace:browse',
      'marketplace:purchase',
      'marketplace:sell',
      'marketplace:review',
    ],
  },
  
  studio: {
    maxProjects: 200,
    maxFilesPerProject: 10000,
    maxStorageGB: 500,
    maxAssetsPerProject: 10000,
    maxCollaborators: 50,
    aiTokensPerMonth: 10_000_000,
    aiRequestsPerMinute: 300,
    maxBuildMinutesPerMonth: 20000,
    supportLevel: 'priority',
    features: [
      'project:create',
      'project:read',
      'project:update',
      'project:delete',
      'project:export',
      'project:share',
      'project:collaborate',
      'ai:chat',
      'ai:stream',
      'ai:advanced',
      'ai:training',
      'engine:blueprint',
      'engine:vfx',
      'engine:terrain',
      'engine:animation',
      'engine:physics',
      'engine:networking',
      'engine:raytracing',
      'collab:invite',
      'collab:realtime',
      'collab:comments',
      'collab:review',
      'marketplace:browse',
      'marketplace:purchase',
      'marketplace:sell',
      'marketplace:review',
    ],
  },
  
  enterprise: {
    maxProjects: -1, // Unlimited
    maxFilesPerProject: -1,
    maxStorageGB: -1,
    maxAssetsPerProject: -1,
    maxCollaborators: -1,
    aiTokensPerMonth: -1,
    aiRequestsPerMinute: -1,
    maxBuildMinutesPerMonth: -1,
    supportLevel: 'dedicated',
    features: [
      'project:create',
      'project:read',
      'project:update',
      'project:delete',
      'project:export',
      'project:share',
      'project:collaborate',
      'ai:chat',
      'ai:stream',
      'ai:advanced',
      'ai:training',
      'ai:custom_models',
      'engine:blueprint',
      'engine:vfx',
      'engine:terrain',
      'engine:animation',
      'engine:physics',
      'engine:networking',
      'engine:raytracing',
      'collab:invite',
      'collab:realtime',
      'collab:comments',
      'collab:review',
      'marketplace:browse',
      'marketplace:purchase',
      'marketplace:sell',
      'marketplace:review',
      'admin:users',
      'admin:analytics',
    ],
  },
};

