// @aethel-heavy-async-boundary

import { THREE } from './pbr-three-namespace';
import type { PostProcessSettings } from './post-process-volume.contracts';

export function createDefaultPostProcessSettings(): PostProcessSettings {
  return {
    bloomEnabled: true,
    bloomIntensity: 0.5,
    bloomThreshold: 0.8,
    bloomRadius: 0.4,
    colorGradingEnabled: true,
    exposure: 1.0,
    contrast: 1.0,
    saturation: 1.0,
    temperature: 0,
    tint: 0,
    shadows: new THREE.Color(1, 1, 1),
    midtones: new THREE.Color(1, 1, 1),
    highlights: new THREE.Color(1, 1, 1),
    tonemappingEnabled: true,
    tonemappingMode: 'aces',
    vignetteEnabled: false,
    vignetteIntensity: 0.3,
    vignetteSmoothness: 0.5,
    vignetteColor: new THREE.Color(0, 0, 0),
    chromaticAberrationEnabled: false,
    chromaticAberrationIntensity: 0.005,
    filmGrainEnabled: false,
    filmGrainIntensity: 0.1,
    filmGrainResponse: 0.8,
    dofEnabled: false,
    dofFocusDistance: 10,
    dofFocusRange: 3,
    dofBokehScale: 2,
    motionBlurEnabled: false,
    motionBlurIntensity: 0.5,
    motionBlurSamples: 8,
    aoEnabled: true,
    aoIntensity: 1.0,
    aoRadius: 0.5,
    aoBias: 0.025,
    fogEnabled: false,
    fogColor: new THREE.Color(0.5, 0.6, 0.7),
    fogDensity: 0.01,
    fogStart: 10,
    fogEnd: 100,
    fogHeightFalloff: 0.1,
  };
}

export const DEFAULT_POST_PROCESS_SETTINGS: PostProcessSettings = createDefaultPostProcessSettings();

export const POST_PROCESS_PRESETS: Record<string, Partial<PostProcessSettings>> = {
  cinematic: {
    bloomEnabled: true,
    bloomIntensity: 0.6,
    bloomThreshold: 0.7,
    colorGradingEnabled: true,
    exposure: 0.9,
    contrast: 1.1,
    saturation: 0.9,
    vignetteEnabled: true,
    vignetteIntensity: 0.4,
    filmGrainEnabled: true,
    filmGrainIntensity: 0.05,
    tonemappingMode: 'filmic',
  },
  horror: {
    colorGradingEnabled: true,
    exposure: 0.7,
    contrast: 1.3,
    saturation: 0.6,
    temperature: -0.1,
    vignetteEnabled: true,
    vignetteIntensity: 0.6,
    chromaticAberrationEnabled: true,
    chromaticAberrationIntensity: 0.01,
    filmGrainEnabled: true,
    filmGrainIntensity: 0.15,
    fogEnabled: true,
    fogDensity: 0.05,
  },
  vibrant: {
    bloomEnabled: true,
    bloomIntensity: 0.8,
    colorGradingEnabled: true,
    exposure: 1.1,
    saturation: 1.3,
    contrast: 1.1,
    tonemappingMode: 'aces',
  },
  noir: {
    colorGradingEnabled: true,
    saturation: 0,
    contrast: 1.4,
    vignetteEnabled: true,
    vignetteIntensity: 0.5,
    filmGrainEnabled: true,
    filmGrainIntensity: 0.2,
  },
  underwater: {
    colorGradingEnabled: true,
    temperature: -0.2,
    tint: 0.1,
    saturation: 0.8,
    fogEnabled: true,
    fogColor: new THREE.Color(0.1, 0.3, 0.4),
    fogDensity: 0.03,
    chromaticAberrationEnabled: true,
    chromaticAberrationIntensity: 0.008,
  },
  sunset: {
    bloomEnabled: true,
    bloomIntensity: 0.7,
    colorGradingEnabled: true,
    temperature: 0.3,
    exposure: 1.1,
    highlights: new THREE.Color(1.2, 0.9, 0.7),
    shadows: new THREE.Color(0.8, 0.7, 1.0),
  },
  dream: {
    bloomEnabled: true,
    bloomIntensity: 1.0,
    bloomThreshold: 0.5,
    bloomRadius: 0.6,
    colorGradingEnabled: true,
    saturation: 1.1,
    dofEnabled: true,
    dofFocusDistance: 5,
    dofFocusRange: 2,
    vignetteEnabled: true,
    vignetteIntensity: 0.3,
  },
};
