import type { AgentWorkLane, AgentWorkTool } from './parallel-agent-work-contract'
import type { AgentMode, AgentToolDefinition, AgentToolPermissions } from './agent-tool-bus'

const KB = 1024
const MB = KB * KB

const basePermissions: AgentToolPermissions = {
  readProject: true,
  writeProject: false,
  externalNetwork: false,
  browserControl: false,
  userAccount: false,
  secrets: false,
  financialAction: false,
  destructiveAction: false,
  deployment: false,
}

function permissions(patch: Partial<AgentToolPermissions> = {}): AgentToolPermissions {
  return { ...basePermissions, ...patch }
}

function tool(
  id: AgentWorkTool,
  patch: Omit<AgentToolDefinition, 'id'>
): AgentToolDefinition {
  return { id, ...patch }
}

export function getCanonicalAgentTools(): AgentToolDefinition[] {
  return [
    tool('project-brain', {
      label: 'Project Brain',
      lane: 'orchestration',
      allowedModes: ['Coordinator', 'Research', 'Builder', 'Creative', 'QA', 'Release'],
      runtimeTargets: ['local-worker', 'cloud-sandbox'],
      risk: 'low',
      approval: 'none',
      costClass: 'free',
      defaultTimeoutMs: 15_000,
      maxPayloadBytes: 1 * MB,
      permissions: permissions(),
      sandboxPolicy: 'read-only',
      rollbackStrategy: 'none',
      requiresReplay: false,
      requiresRollback: false,
      requiresIdempotencyKey: false,
      requiresReadReceipts: false,
      requiresScopeLock: false,
      requiredEvidence: ['brain read receipt'],
    }),
    tool('mission-ledger', {
      label: 'Mission Ledger',
      lane: 'orchestration',
      allowedModes: ['Coordinator', 'Research', 'Builder', 'Creative', 'QA', 'Browser Operator', 'Release'],
      runtimeTargets: ['local-worker', 'cloud-sandbox'],
      risk: 'low',
      approval: 'none',
      costClass: 'free',
      defaultTimeoutMs: 15_000,
      maxPayloadBytes: 512 * KB,
      permissions: permissions({ writeProject: true }),
      sandboxPolicy: 'write-scoped',
      rollbackStrategy: 'none',
      requiresReplay: false,
      requiresRollback: false,
      requiresIdempotencyKey: true,
      requiresReadReceipts: false,
      requiresScopeLock: false,
      requiredEvidence: ['ledger event'],
    }),
    tool('repository-cartography', {
      label: 'Repository Cartography',
      lane: 'orchestration',
      allowedModes: ['Coordinator', 'Research', 'Builder', 'Creative', 'QA', 'Release'],
      runtimeTargets: ['local-worker', 'local-sidecar', 'cloud-sandbox'],
      risk: 'medium',
      approval: 'review',
      costClass: 'metered-low',
      defaultTimeoutMs: 120_000,
      maxPayloadBytes: 50 * MB,
      permissions: permissions({ externalNetwork: true }),
      sandboxPolicy: 'network-allowed',
      rollbackStrategy: 'none',
      requiresReplay: false,
      requiresRollback: false,
      requiresIdempotencyKey: false,
      requiresReadReceipts: true,
      requiresScopeLock: false,
      requiredEvidence: ['cartography manifest', 'context budget'],
    }),
    tool('deep-spine-scan', {
      label: 'Deep Spine Scan',
      lane: 'orchestration',
      allowedModes: ['Coordinator', 'Research', 'Builder', 'Creative', 'QA', 'Release'],
      runtimeTargets: ['local-worker', 'local-sidecar', 'cloud-sandbox', 'human-held'],
      risk: 'medium',
      approval: 'review',
      costClass: 'metered-low',
      defaultTimeoutMs: 240_000,
      maxPayloadBytes: 64 * MB,
      permissions: permissions({ writeProject: true }),
      sandboxPolicy: 'write-scoped',
      rollbackStrategy: 'artifact-delete',
      requiresReplay: false,
      requiresRollback: false,
      requiresIdempotencyKey: true,
      requiresReadReceipts: true,
      requiresScopeLock: false,
      requiredEvidence: [
        'scan scope',
        'cartography manifest',
        'context budget',
        'metadata-first external sources',
        'no-auto-fix declaration',
      ],
    }),
    tool('context-budget', {
      label: 'Context Budget',
      lane: 'orchestration',
      allowedModes: ['Coordinator', 'Research', 'Builder', 'Creative', 'QA', 'Release'],
      runtimeTargets: ['local-worker', 'cloud-sandbox'],
      risk: 'low',
      approval: 'none',
      costClass: 'free',
      defaultTimeoutMs: 20_000,
      maxPayloadBytes: 5 * MB,
      permissions: permissions(),
      sandboxPolicy: 'read-only',
      rollbackStrategy: 'none',
      requiresReplay: false,
      requiresRollback: false,
      requiresIdempotencyKey: false,
      requiresReadReceipts: true,
      requiresScopeLock: false,
      requiredEvidence: ['retrieval plan'],
    }),
    tool('code-search', {
      label: 'Code Search',
      lane: 'software',
      allowedModes: ['Coordinator', 'Research', 'Builder', 'Creative', 'QA', 'Release'],
      runtimeTargets: ['local-worker', 'local-sidecar', 'cloud-sandbox'],
      risk: 'low',
      approval: 'none',
      costClass: 'free',
      defaultTimeoutMs: 30_000,
      maxPayloadBytes: 2 * MB,
      permissions: permissions(),
      sandboxPolicy: 'read-only',
      rollbackStrategy: 'none',
      requiresReplay: false,
      requiresRollback: false,
      requiresIdempotencyKey: false,
      requiresReadReceipts: true,
      requiresScopeLock: false,
      requiredEvidence: ['search query', 'result refs', 'context budget'],
    }),
    tool('file-read', {
      label: 'File Read',
      lane: 'software',
      allowedModes: ['Coordinator', 'Research', 'Builder', 'Creative', 'QA', 'Release'],
      runtimeTargets: ['local-worker', 'local-sidecar', 'cloud-sandbox'],
      risk: 'low',
      approval: 'none',
      costClass: 'free',
      defaultTimeoutMs: 20_000,
      maxPayloadBytes: 10 * MB,
      permissions: permissions(),
      sandboxPolicy: 'read-only',
      rollbackStrategy: 'none',
      requiresReplay: false,
      requiresRollback: false,
      requiresIdempotencyKey: false,
      requiresReadReceipts: true,
      requiresScopeLock: false,
      requiredEvidence: ['file read receipt'],
    }),
    tool('diff-proposal', {
      label: 'Diff Proposal',
      lane: 'software',
      allowedModes: ['Builder', 'Creative', 'Release'],
      runtimeTargets: ['local-worker', 'cloud-sandbox'],
      risk: 'medium',
      approval: 'review',
      costClass: 'metered-low',
      defaultTimeoutMs: 60_000,
      maxPayloadBytes: 5 * MB,
      permissions: permissions({ writeProject: true }),
      sandboxPolicy: 'write-scoped',
      rollbackStrategy: 'diff-revert',
      requiresReplay: false,
      requiresRollback: true,
      requiresIdempotencyKey: true,
      requiresReadReceipts: true,
      requiresScopeLock: true,
      requiredEvidence: ['diff', 'rollback plan', 'read receipts'],
    }),
    tool('test-runner', {
      label: 'Test Runner',
      lane: 'validation',
      allowedModes: ['Builder', 'QA', 'Release'],
      runtimeTargets: ['local-sidecar', 'cloud-sandbox'],
      risk: 'medium',
      approval: 'none',
      costClass: 'metered-low',
      defaultTimeoutMs: 180_000,
      maxPayloadBytes: 2 * MB,
      permissions: permissions(),
      sandboxPolicy: 'read-only',
      rollbackStrategy: 'none',
      requiresReplay: false,
      requiresRollback: false,
      requiresIdempotencyKey: true,
      requiresReadReceipts: false,
      requiresScopeLock: false,
      requiredEvidence: ['test output'],
    }),
    tool('cost-meter', {
      label: 'Cost Meter',
      lane: 'orchestration',
      allowedModes: ['Coordinator', 'Research', 'Builder', 'Creative', 'QA', 'Browser Operator', 'Release'],
      runtimeTargets: ['local-worker', 'cloud-sandbox'],
      risk: 'low',
      approval: 'none',
      costClass: 'free',
      defaultTimeoutMs: 15_000,
      maxPayloadBytes: 128 * KB,
      permissions: permissions(),
      sandboxPolicy: 'read-only',
      rollbackStrategy: 'none',
      requiresReplay: false,
      requiresRollback: false,
      requiresIdempotencyKey: false,
      requiresReadReceipts: false,
      requiresScopeLock: false,
      requiredEvidence: ['cost snapshot'],
    }),
    tool('deep-research', {
      label: 'Deep Research',
      lane: 'research',
      allowedModes: ['Coordinator', 'Research'],
      runtimeTargets: ['local-worker', 'cloud-sandbox'],
      risk: 'medium',
      approval: 'review',
      costClass: 'metered-medium',
      defaultTimeoutMs: 180_000,
      maxPayloadBytes: 10 * MB,
      permissions: permissions({ externalNetwork: true }),
      sandboxPolicy: 'network-allowed',
      rollbackStrategy: 'none',
      requiresReplay: false,
      requiresRollback: false,
      requiresIdempotencyKey: false,
      requiresReadReceipts: true,
      requiresScopeLock: false,
      requiredEvidence: ['source citations', 'research packet'],
    }),
    tool('source-citation', {
      label: 'Source Citation',
      lane: 'research',
      allowedModes: ['Coordinator', 'Research', 'Builder', 'Creative', 'QA', 'Browser Operator', 'Release'],
      runtimeTargets: ['local-worker', 'cloud-sandbox'],
      risk: 'low',
      approval: 'none',
      costClass: 'free',
      defaultTimeoutMs: 20_000,
      maxPayloadBytes: 1 * MB,
      permissions: permissions({ externalNetwork: true }),
      sandboxPolicy: 'network-allowed',
      rollbackStrategy: 'none',
      requiresReplay: false,
      requiresRollback: false,
      requiresIdempotencyKey: false,
      requiresReadReceipts: true,
      requiresScopeLock: false,
      requiredEvidence: ['source URL', 'retrieved-at timestamp', 'citation summary'],
    }),
    tool('github-mirror', {
      label: 'GitHub Mirror',
      lane: 'research',
      allowedModes: ['Research', 'Coordinator'],
      runtimeTargets: ['local-worker', 'cloud-sandbox'],
      risk: 'medium',
      approval: 'review',
      costClass: 'metered-low',
      defaultTimeoutMs: 120_000,
      maxPayloadBytes: 20 * MB,
      permissions: permissions({ externalNetwork: true }),
      sandboxPolicy: 'network-allowed',
      rollbackStrategy: 'none',
      requiresReplay: false,
      requiresRollback: false,
      requiresIdempotencyKey: false,
      requiresReadReceipts: true,
      requiresScopeLock: false,
      requiredEvidence: ['metadata manifest', 'license summary'],
    }),
    tool('huggingface-mirror', {
      label: 'Hugging Face Mirror',
      lane: 'asset',
      allowedModes: ['Research', 'Creative'],
      runtimeTargets: ['local-sidecar', 'cloud-sandbox'],
      risk: 'high',
      approval: 'review',
      costClass: 'metered-medium',
      defaultTimeoutMs: 240_000,
      maxPayloadBytes: 50 * MB,
      permissions: permissions({ externalNetwork: true }),
      sandboxPolicy: 'network-allowed',
      rollbackStrategy: 'none',
      requiresReplay: false,
      requiresRollback: false,
      requiresIdempotencyKey: false,
      requiresReadReceipts: true,
      requiresScopeLock: false,
      requiredEvidence: ['metadata-first scan', 'license summary', 'download budget'],
    }),
    tool('asset-metadata', {
      label: 'Asset Metadata',
      lane: 'asset',
      allowedModes: ['Research', 'Creative', 'QA'],
      runtimeTargets: ['local-worker', 'local-sidecar', 'cloud-sandbox'],
      risk: 'medium',
      approval: 'review',
      costClass: 'metered-low',
      defaultTimeoutMs: 90_000,
      maxPayloadBytes: 20 * MB,
      permissions: permissions({ externalNetwork: true }),
      sandboxPolicy: 'network-allowed',
      rollbackStrategy: 'none',
      requiresReplay: false,
      requiresRollback: false,
      requiresIdempotencyKey: false,
      requiresReadReceipts: true,
      requiresScopeLock: false,
      requiredEvidence: ['asset hash', 'asset dimensions', 'format metadata', 'provenance summary'],
    }),
    tool('license-check', {
      label: 'License Check',
      lane: 'validation',
      allowedModes: ['Research', 'Creative', 'QA', 'Release'],
      runtimeTargets: ['local-worker', 'cloud-sandbox'],
      risk: 'medium',
      approval: 'review',
      costClass: 'metered-low',
      defaultTimeoutMs: 60_000,
      maxPayloadBytes: 2 * MB,
      permissions: permissions({ externalNetwork: true }),
      sandboxPolicy: 'network-allowed',
      rollbackStrategy: 'none',
      requiresReplay: false,
      requiresRollback: false,
      requiresIdempotencyKey: false,
      requiresReadReceipts: true,
      requiresScopeLock: false,
      requiredEvidence: ['license summary', 'source URL', 'commercial-use decision'],
    }),
    tool('browser-operator', {
      label: 'Browser Operator',
      lane: 'browser-operator',
      allowedModes: ['Browser Operator'],
      runtimeTargets: ['browser-operator', 'human-held'],
      risk: 'critical',
      approval: 'explicit-human',
      costClass: 'metered-medium',
      defaultTimeoutMs: 180_000,
      maxPayloadBytes: 5 * MB,
      permissions: permissions({ externalNetwork: true, browserControl: true, userAccount: true, secrets: true }),
      sandboxPolicy: 'browser-held',
      rollbackStrategy: 'human-recovery',
      requiresReplay: true,
      requiresRollback: true,
      requiresIdempotencyKey: true,
      requiresReadReceipts: false,
      requiresScopeLock: false,
      requiredEvidence: ['browser replay', 'screenshot', 'DOM snapshot', 'approval record'],
    }),
    tool('browser-replay', {
      label: 'Browser Replay Review',
      lane: 'browser-operator',
      allowedModes: ['Browser Operator', 'QA', 'Release'],
      runtimeTargets: ['local-worker', 'cloud-sandbox', 'human-held'],
      risk: 'high',
      approval: 'review',
      costClass: 'metered-low',
      defaultTimeoutMs: 60_000,
      maxPayloadBytes: 10 * MB,
      permissions: permissions({ externalNetwork: true, browserControl: true }),
      sandboxPolicy: 'browser-held',
      rollbackStrategy: 'human-recovery',
      requiresReplay: true,
      requiresRollback: false,
      requiresIdempotencyKey: true,
      requiresReadReceipts: false,
      requiresScopeLock: false,
      requiredEvidence: ['browser replay', 'screenshot', 'DOM snapshot', 'pause/takeover status'],
    }),
    tool('viewport-capture', {
      label: 'Viewport Capture',
      lane: 'creative',
      allowedModes: ['Creative', 'QA'],
      runtimeTargets: ['local-sidecar', 'cloud-sandbox'],
      risk: 'medium',
      approval: 'none',
      costClass: 'metered-low',
      defaultTimeoutMs: 60_000,
      maxPayloadBytes: 10 * MB,
      permissions: permissions({ writeProject: true }),
      sandboxPolicy: 'write-scoped',
      rollbackStrategy: 'artifact-delete',
      requiresReplay: false,
      requiresRollback: true,
      requiresIdempotencyKey: true,
      requiresReadReceipts: true,
      requiresScopeLock: true,
      requiredEvidence: ['viewport state', 'screenshot artifact', 'artifact ownership validation', 'rollback plan'],
    }),
    tool('playtest-runner', {
      label: 'Playtest Runner',
      lane: 'validation',
      allowedModes: ['Creative', 'QA'],
      runtimeTargets: ['local-sidecar', 'cloud-sandbox'],
      risk: 'high',
      approval: 'review',
      costClass: 'metered-medium',
      defaultTimeoutMs: 300_000,
      maxPayloadBytes: 5 * MB,
      permissions: permissions({ writeProject: true }),
      sandboxPolicy: 'write-scoped',
      rollbackStrategy: 'artifact-delete',
      requiresReplay: true,
      requiresRollback: true,
      requiresIdempotencyKey: true,
      requiresReadReceipts: true,
      requiresScopeLock: true,
      requiredEvidence: ['playtest plan', 'input replay', 'performance report', 'failure summary', 'rollback plan'],
    }),
    tool('runtime-router', {
      label: 'Runtime Router',
      lane: 'performance',
      allowedModes: ['Coordinator', 'Builder', 'Creative', 'QA', 'Release'],
      runtimeTargets: ['local-worker', 'local-sidecar', 'cloud-sandbox', 'human-held'],
      risk: 'medium',
      approval: 'none',
      costClass: 'free',
      defaultTimeoutMs: 30_000,
      maxPayloadBytes: 1 * MB,
      permissions: permissions(),
      sandboxPolicy: 'read-only',
      rollbackStrategy: 'none',
      requiresReplay: false,
      requiresRollback: false,
      requiresIdempotencyKey: true,
      requiresReadReceipts: false,
      requiresScopeLock: false,
      requiredEvidence: ['runtime capability report', 'runtime budget', 'lane decision'],
    }),
    tool('render-queue', {
      label: 'Render Queue',
      lane: 'creative',
      allowedModes: ['Creative', 'QA'],
      runtimeTargets: ['local-sidecar', 'cloud-sandbox'],
      risk: 'high',
      approval: 'review',
      costClass: 'metered-high',
      defaultTimeoutMs: 300_000,
      maxPayloadBytes: 20 * MB,
      permissions: permissions({ writeProject: true }),
      sandboxPolicy: 'write-scoped',
      rollbackStrategy: 'artifact-delete',
      requiresReplay: false,
      requiresRollback: true,
      requiresIdempotencyKey: true,
      requiresReadReceipts: true,
      requiresScopeLock: true,
      requiredEvidence: ['render contract', 'artifact links', 'performance report', 'rollback plan'],
    }),
    tool('renderer-probe', {
      label: 'Renderer Probe',
      lane: 'performance',
      allowedModes: ['Coordinator', 'Creative', 'QA', 'Release'],
      runtimeTargets: ['local-worker', 'local-sidecar', 'cloud-sandbox'],
      risk: 'medium',
      approval: 'none',
      costClass: 'free',
      defaultTimeoutMs: 30_000,
      maxPayloadBytes: 1 * MB,
      permissions: permissions(),
      sandboxPolicy: 'read-only',
      rollbackStrategy: 'none',
      requiresReplay: false,
      requiresRollback: false,
      requiresIdempotencyKey: true,
      requiresReadReceipts: false,
      requiresScopeLock: false,
      requiredEvidence: ['runtime capability report', 'toolchain registry', 'backend health'],
    }),
    tool('asset-optimize', {
      label: 'Asset Optimize',
      lane: 'asset',
      allowedModes: ['Creative', 'QA'],
      runtimeTargets: ['local-sidecar', 'cloud-sandbox'],
      risk: 'high',
      approval: 'review',
      costClass: 'metered-medium',
      defaultTimeoutMs: 300_000,
      maxPayloadBytes: 100 * MB,
      permissions: permissions({ writeProject: true }),
      sandboxPolicy: 'write-scoped',
      rollbackStrategy: 'artifact-delete',
      requiresReplay: false,
      requiresRollback: true,
      requiresIdempotencyKey: true,
      requiresReadReceipts: true,
      requiresScopeLock: true,
      requiredEvidence: ['asset metadata', 'license summary', 'optimization budget', 'proxy/LOD artifact', 'rollback plan'],
    }),
    tool('shader-compile', {
      label: 'Shader Compile',
      lane: 'performance',
      allowedModes: ['Builder', 'Creative', 'QA'],
      runtimeTargets: ['local-sidecar', 'cloud-sandbox'],
      risk: 'high',
      approval: 'review',
      costClass: 'metered-low',
      defaultTimeoutMs: 120_000,
      maxPayloadBytes: 5 * MB,
      permissions: permissions({ writeProject: true }),
      sandboxPolicy: 'write-scoped',
      rollbackStrategy: 'artifact-delete',
      requiresReplay: false,
      requiresRollback: true,
      requiresIdempotencyKey: true,
      requiresReadReceipts: true,
      requiresScopeLock: true,
      requiredEvidence: ['shader source hash', 'compile log', 'fallback material', 'rollback plan'],
    }),
    tool('render-submit', {
      label: 'Render Submit',
      lane: 'creative',
      allowedModes: ['Creative', 'Release'],
      runtimeTargets: ['local-sidecar', 'cloud-sandbox', 'human-held'],
      risk: 'high',
      approval: 'review',
      costClass: 'metered-high',
      defaultTimeoutMs: 600_000,
      maxPayloadBytes: 20 * MB,
      permissions: permissions({ writeProject: true }),
      sandboxPolicy: 'write-scoped',
      rollbackStrategy: 'artifact-delete',
      requiresReplay: false,
      requiresRollback: true,
      requiresIdempotencyKey: true,
      requiresReadReceipts: true,
      requiresScopeLock: true,
      requiredEvidence: ['render backend contract', 'runtime budget', 'asset graph', 'validation graph', 'rollback plan'],
    }),
    tool('render-validate', {
      label: 'Render Validate',
      lane: 'validation',
      allowedModes: ['Creative', 'QA', 'Release'],
      runtimeTargets: ['local-worker', 'cloud-sandbox'],
      risk: 'medium',
      approval: 'none',
      costClass: 'metered-low',
      defaultTimeoutMs: 120_000,
      maxPayloadBytes: 10 * MB,
      permissions: permissions(),
      sandboxPolicy: 'read-only',
      rollbackStrategy: 'none',
      requiresReplay: false,
      requiresRollback: false,
      requiresIdempotencyKey: true,
      requiresReadReceipts: true,
      requiresScopeLock: false,
      requiredEvidence: ['render evidence', 'performance report', 'artifact ownership validation'],
    }),
    tool('deployment', {
      label: 'Deployment',
      lane: 'release',
      allowedModes: ['Release'],
      runtimeTargets: ['cloud-sandbox', 'human-held'],
      risk: 'critical',
      approval: 'explicit-human',
      costClass: 'metered-low',
      defaultTimeoutMs: 240_000,
      maxPayloadBytes: 5 * MB,
      permissions: permissions({ externalNetwork: true, deployment: true, writeProject: true }),
      sandboxPolicy: 'release-held',
      rollbackStrategy: 'deployment-rollback',
      requiresReplay: true,
      requiresRollback: true,
      requiresIdempotencyKey: true,
      requiresReadReceipts: true,
      requiresScopeLock: true,
      requiredEvidence: ['build result', 'deploy preview', 'approval record', 'rollback plan'],
    }),
    tool('human-approval', {
      label: 'Human Approval',
      lane: 'orchestration',
      allowedModes: ['Coordinator', 'Browser Operator', 'Release'],
      runtimeTargets: ['human-held'],
      risk: 'low',
      approval: 'none',
      costClass: 'free',
      defaultTimeoutMs: 86_400_000,
      maxPayloadBytes: 128 * KB,
      permissions: permissions(),
      sandboxPolicy: 'read-only',
      rollbackStrategy: 'none',
      requiresReplay: false,
      requiresRollback: false,
      requiresIdempotencyKey: true,
      requiresReadReceipts: false,
      requiresScopeLock: false,
      requiredEvidence: ['approval record'],
    }),
  ]
}
