import type { EngineModuleAdapter } from './engine-module-adapters';

export const ENGINE_MODULE_ADAPTERS: EngineModuleAdapter[] = [
  {
    modulePath: 'lib/sequencer-cinematics.ts',
    ownerSurface: '/studio/film',
    contractKind: 'shot-sequence-summary',
    runtimeBoundary: 'summary-adapter',
    exportedContracts: ['SequenceConfig', 'TrackType', 'Easings'],
    evidenceSignals: ['shot-id', 'sequence-duration', 'render-evidence-link'],
  },
  {
    modulePath: 'lib/postprocessing/post-processing-system.ts',
    ownerSurface: '/studio/level',
    contractKind: 'viewport-quality-preset',
    runtimeBoundary: 'render-gated',
    exportedContracts: ['PostProcessingSettings', 'BloomSettings', 'ColorGradingSettings'],
    evidenceSignals: ['quality-preset', 'render-readiness', 'postfx-cost-class'],
  },
  {
    modulePath: 'lib/particles/advanced-particle-system.ts',
    ownerSurface: '/studio/vfx',
    contractKind: 'vfx-particle-preset',
    runtimeBoundary: 'summary-adapter',
    exportedContracts: ['ParticleSystemSettings', 'EmitterSettings', 'CollisionSettings'],
    evidenceSignals: ['emitter-shape', 'max-particles', 'collision-enabled'],
  },
  {
    modulePath: 'lib/particle-system-real.ts',
    ownerSurface: '/studio/vfx',
    contractKind: 'gpu-particle-runtime',
    runtimeBoundary: 'render-gated',
    exportedContracts: ['ParticleEmitterConfig', 'ParticleForce', 'ParticleCollider'],
    evidenceSignals: ['gpu-runtime', 'blend-mode', 'world-space'],
  },
  {
    modulePath: 'lib/ai/behavior-tree-system.tsx',
    ownerSurface: '/studio/level',
    contractKind: 'gameplay-validation-graph',
    runtimeBoundary: 'type-contract',
    exportedContracts: ['BehaviorTree', 'AIAgent', 'BehaviorNode'],
    evidenceSignals: ['npc-decision-path', 'playtest-failure-link', 'agent-scope-lock'],
  },
  {
    modulePath: 'lib/world/world-streaming.tsx',
    ownerSurface: '/studio/level',
    contractKind: 'world-partition-summary',
    runtimeBoundary: 'summary-adapter',
    exportedContracts: ['StreamingConfig', 'WorldChunk', 'WorldStreamingSystem'],
    evidenceSignals: ['chunk-budget', 'loaded-chunks', 'memory-budget-mb'],
  },
  {
    modulePath: 'lib/control-rig-system.ts',
    ownerSurface: '/studio/animation',
    contractKind: 'character-rig-validation',
    runtimeBoundary: 'type-contract',
    exportedContracts: ['ControlRigConfig', 'RigHierarchy', 'RigControl'],
    evidenceSignals: ['ik-targets', 'constraint-count', 'rig-review-packet'],
  },
  {
    modulePath: 'lib/facial-animation-system.ts',
    ownerSurface: '/studio/animation',
    contractKind: 'facial-animation-review',
    runtimeBoundary: 'type-contract',
    exportedContracts: ['FacialConfig', 'FACSPose', 'LipSyncData'],
    evidenceSignals: ['facs-pose', 'lip-sync-evidence', 'emotion-state'],
  },
  {
    modulePath: 'lib/ray-tracing.ts',
    ownerSurface: '/studio/level',
    contractKind: 'ray-tracing-readiness',
    runtimeBoundary: 'render-gated',
    exportedContracts: ['RayTracingConfig', 'BVHNode', 'RTMaterial'],
    evidenceSignals: ['p95-frame-ms', 'denoiser-enabled', 'human-render-review'],
  },
  {
    modulePath: 'lib/nanite-virtualized-geometry.ts',
    ownerSurface: '/studio/level',
    contractKind: 'virtualized-geometry-summary',
    runtimeBoundary: 'render-gated',
    exportedContracts: ['NaniteConfig', 'VirtualizedMesh', 'CullingStats'],
    evidenceSignals: ['visible-meshlets', 'triangles-rendered', 'memory-budget-mb'],
  },
  {
    modulePath: 'lib/assets/asset-importer.ts',
    ownerSurface: '/studio/level',
    contractKind: 'asset-import-intake',
    runtimeBoundary: 'worker-held',
    exportedContracts: ['AssetType', 'ImportOptions', 'ImportedAsset'],
    evidenceSignals: ['license-report', 'checksum', 'lod-pbr-collision-evidence'],
  },
  {
    modulePath: 'lib/engine/audio-manager.ts',
    ownerSurface: '/studio/film',
    contractKind: 'audio-mix-summary',
    runtimeBoundary: 'summary-adapter',
    exportedContracts: ['AudioSourceConfig', 'AudioGroupConfig', 'AudioSnapshot'],
    evidenceSignals: ['mix-snapshot', 'peak-levels', 'human-audio-review'],
  },
  {
    modulePath: 'lib/audio/spatial-audio-system.ts',
    ownerSurface: '/studio/film',
    contractKind: 'spatial-audio-review',
    runtimeBoundary: 'summary-adapter',
    exportedContracts: ['AudioSettings', 'SoundSettings', 'ReverbSettings'],
    evidenceSignals: ['listener-position', 'reverb-zone', 'headphone-review'],
  },
  {
    modulePath: 'lib/physics/physics-system.ts',
    ownerSurface: '/studio/level',
    contractKind: 'physics-readiness-summary',
    runtimeBoundary: 'type-contract',
    exportedContracts: ['PhysicsSettings', 'RigidBodyConfig', 'ColliderShape'],
    evidenceSignals: ['fixed-timestep', 'collision-budget', 'playtest-physics-report'],
  },
  {
    modulePath: 'lib/terrain/terrain-system.ts',
    ownerSurface: '/studio/level',
    contractKind: 'terrain-world-summary',
    runtimeBoundary: 'worker-held',
    exportedContracts: ['TerrainSettings', 'NoiseSettings', 'BrushSettings'],
    evidenceSignals: ['heightmap-resolution', 'lod-levels', 'terrain-collider-evidence'],
  },
  {
    modulePath: 'lib/volumetric-clouds.ts',
    ownerSurface: '/studio/level',
    contractKind: 'volumetric-atmosphere-summary',
    runtimeBoundary: 'render-gated',
    exportedContracts: ['CloudConfig', 'VolumetricCloudRenderer', 'CloudShadowMap'],
    evidenceSignals: ['cloud-raymarch-budget', 'shadow-map-budget', 'performance-trace'],
  },
  {
    modulePath: 'lib/dialogue/dialogue-system.tsx',
    ownerSurface: '/studio/film',
    contractKind: 'dialogue-runtime-review',
    runtimeBoundary: 'summary-adapter',
    exportedContracts: ['DialogueConversation', 'DialogueState', 'DialogueEvent'],
    evidenceSignals: ['branch-coverage', 'voice-consent', 'localization-review'],
  },
  {
    modulePath: 'lib/webxr-vr-system.ts',
    ownerSurface: '/studio/level',
    contractKind: 'immersive-xr-readiness',
    runtimeBoundary: 'worker-held',
    exportedContracts: ['XRConfig', 'XRControllerState', 'XRFeature'],
    evidenceSignals: ['device-capability', 'comfort-review', 'input-latency-trace'],
  },
  {
    modulePath: 'lib/motion-matching-system.ts',
    ownerSurface: '/studio/animation',
    contractKind: 'motion-matching-readiness',
    runtimeBoundary: 'worker-held',
    exportedContracts: ['MotionMatchingConfig', 'MotionDatabase', 'MotionMatchResult'],
    evidenceSignals: ['pose-database-size', 'foot-lock-review', 'animation-playtest'],
  },
  {
    modulePath: 'lib/input/haptics-system.tsx',
    ownerSurface: '/studio/level',
    contractKind: 'haptics-feedback-review',
    runtimeBoundary: 'type-contract',
    exportedContracts: ['HapticsConfig', 'HapticType', 'HapticMotor'],
    evidenceSignals: ['gamepad-support', 'intensity-profile', 'accessibility-toggle'],
  },
  {
    modulePath: 'lib/environment/weather-system.tsx',
    ownerSurface: '/studio/level',
    contractKind: 'weather-state-summary',
    runtimeBoundary: 'summary-adapter',
    exportedContracts: ['WeatherConfig', 'WeatherState', 'WeatherType'],
    evidenceSignals: ['transition-duration', 'wind-state', 'lighting-impact'],
  },
  {
    modulePath: 'lib/camera/camera-system.tsx',
    ownerSurface: '/studio/level',
    contractKind: 'camera-runtime-review',
    runtimeBoundary: 'summary-adapter',
    exportedContracts: ['CameraConfig', 'FollowSettings', 'ShakeSettings'],
    evidenceSignals: ['camera-mode', 'motion-sickness-review', 'shot-continuity'],
  },
  {
    modulePath: 'lib/engine/physics-engine.ts',
    ownerSurface: '/studio/level',
    contractKind: 'legacy-physics-engine-boundary',
    runtimeBoundary: 'type-contract',
    exportedContracts: ['PhysicsWorld', 'RigidBody', 'ColliderConfig'],
    evidenceSignals: ['deterministic-step', 'collision-replay', 'migration-target'],
  },
  {
    modulePath: 'lib/quest-mission-system.ts',
    ownerSurface: '/studio/quest',
    contractKind: 'quest-mission-governance',
    runtimeBoundary: 'summary-adapter',
    exportedContracts: ['QuestManager', 'QuestUIRenderer', 'QuestMarkerRenderer'],
    evidenceSignals: ['branch-coverage', 'reward-balance', 'localization-review'],
  },
  {
    modulePath: 'lib/ecs-dots-system.ts',
    ownerSurface: '/studio/level',
    contractKind: 'dots-ecs-scheduler-boundary',
    runtimeBoundary: 'worker-held',
    exportedContracts: ['World', 'SystemScheduler', 'JobSystem'],
    evidenceSignals: ['system-order', 'component-count', 'worker-trace'],
  },
  {
    modulePath: 'lib/streaming/level-streaming-system.tsx',
    ownerSurface: '/studio/level',
    contractKind: 'level-streaming-readiness',
    runtimeBoundary: 'worker-held',
    exportedContracts: ['LevelStreamingManager', 'StreamingConfig', 'StreamingMetrics'],
    evidenceSignals: ['loaded-levels', 'memory-pressure', 'transition-trace'],
  },
  {
    modulePath: 'lib/networking-multiplayer.ts',
    ownerSurface: '/studio/level',
    contractKind: 'multiplayer-netcode-readiness',
    runtimeBoundary: 'worker-held',
    exportedContracts: ['NetworkManager', 'RollbackNetcode', 'Matchmaker'],
    evidenceSignals: ['latency-budget', 'rollback-state', 'authority-model'],
  },
  {
    modulePath: 'lib/foliage-system.ts',
    ownerSurface: '/studio/level',
    contractKind: 'foliage-density-readiness',
    runtimeBoundary: 'render-gated',
    exportedContracts: ['FoliagePainter', 'FoliageClusterManager', 'GrassGenerator'],
    evidenceSignals: ['instance-count', 'lod-culling', 'frame-trace'],
  },
  {
    modulePath: 'lib/virtual-texture-system.ts',
    ownerSurface: '/studio/level',
    contractKind: 'virtual-texture-readiness',
    runtimeBoundary: 'worker-held',
    exportedContracts: ['VirtualTextureSystem', 'TileCache', 'FeedbackBuffer'],
    evidenceSignals: ['tile-cache-hit-rate', 'feedback-buffer', 'texture-memory-budget'],
  },
  {
    modulePath: 'lib/ai-audio-engine.ts',
    ownerSurface: '/studio/film',
    contractKind: 'ai-audio-emotion-review',
    runtimeBoundary: 'summary-adapter',
    exportedContracts: ['AIEmotionalAudioSystem', 'EmotionAnalyzer', 'ContextTracker'],
    evidenceSignals: ['emotion-map', 'context-window', 'human-audio-review'],
  },
  {
    modulePath: 'lib/environment/day-night-cycle.tsx',
    ownerSurface: '/studio/level',
    contractKind: 'day-night-cycle-readiness',
    runtimeBoundary: 'summary-adapter',
    exportedContracts: ['DayNightCycle', 'TimeState', 'SkyState'],
    evidenceSignals: ['time-state', 'sun-direction', 'lighting-transition'],
  },
  {
    modulePath: 'lib/asset-import-pipeline.ts',
    ownerSurface: '/studio/level',
    contractKind: 'asset-import-pipeline-readiness',
    runtimeBoundary: 'worker-held',
    exportedContracts: ['AssetImportPipeline', 'ImportedAsset', 'ImportOptions'],
    evidenceSignals: ['format-support', 'license-checksum', 'optimization-report'],
  },
  {
    modulePath: 'lib/audio-engine.ts',
    ownerSurface: '/studio/film',
    contractKind: 'browser-audio-engine-boundary',
    runtimeBoundary: 'summary-adapter',
    exportedContracts: ['AethelAudioEngine', 'AudioTrack', 'ChannelConfig'],
    evidenceSignals: ['channel-mix', 'peak-levels', 'autoplay-safe'],
  },
  {
    modulePath: 'lib/post-process-volume.ts',
    ownerSurface: '/studio/level',
    contractKind: 'post-process-volume-readiness',
    runtimeBoundary: 'render-gated',
    exportedContracts: ['PostProcessVolume', 'PostProcessSettings', 'PostProcessVolumeManager'],
    evidenceSignals: ['volume-priority', 'blend-distance', 'shot-performance-trace'],
  },
  {
    modulePath: 'lib/aaa-material-system.ts',
    ownerSurface: '/studio/level',
    contractKind: 'material-system-readiness',
    runtimeBoundary: 'render-gated',
    exportedContracts: ['AdvancedPBRMaterial', 'MaterialLibrary', 'ShaderGraphCompiler'],
    evidenceSignals: ['pbr-completeness', 'shader-preview', 'texture-license'],
  },
];
