/**
 * Cook & Build Pipeline — Stage 2 (Logic Transpiler).
 *
 * Turns every `.aethelgraph` (general Visual Scripting) and `.abilitygraph`
 * (GAS) asset attached to a project into plain generated source text. This
 * module runs server-side inside the Publish worker (Node, build time) and
 * is allowed to depend on the heavy editor packages — `@aethel/visual-scripting`
 * (React Flow, framer-motion, Yjs) and `@aethel/gameplay` — because none of
 * that ever ships; only the STRING OUTPUT of `transpileProjectScripts` is
 * written into the exported game, and `verifyRuntimeBundleIsolation` from
 * `publish-pipeline-orchestrator.ts` scans exactly that output before
 * packaging is allowed to run.
 *
 * Law VII honesty: VS→TS string transpile is real; VS→WASM bytecode ship stays HELD.
 */

import { createHash } from 'node:crypto'

import { VisualScriptCompiler } from '@aethel/visual-scripting/VisualScriptRuntime'
import type { VisualScript } from '@aethel/visual-scripting/VisualScriptEditor'
import { AbilityGraphCompiler, type AbilityGraph, type CompiledAbility } from '@aethel/gameplay/ability-graph-compiler'

/** VS→WASM bytecode / Worker gameplay shield product — HELD until M.3 + Law VII cook. */
export const VS_WASM_BYTECODE_SHIP_READY = false as const
export const VS_TO_WASM_MARKETING_ALLOWED = false as const

export type TranspileSourceKind = 'visual-script' | 'ability-graph'

export interface TranspileSourceAsset {
  assetId: string
  assetName: string
  kind: TranspileSourceKind
  /** Raw persisted graph JSON — `VisualScript` shape for `visual-script`, `AbilityGraph` shape for `ability-graph`. */
  graph: unknown
}

export interface GeneratedSourceFile {
  /** Relative path inside the generated bundle, e.g. `generated/scripts/PlayerMovement.ts`. */
  path: string
  content: string
  exportedClassName: string
  sourceAssetId: string
}

export interface TranspileWarning {
  sourceAssetId: string
  sourceAssetName: string
  message: string
  /** Ability graphs surface balance heuristics (DPS/resource cost) — flagged separately so a human reviews game-design issues, not just codegen gaps. */
  severity: 'codegen-gap' | 'balance-review'
}

export interface TranspileStageResult {
  files: GeneratedSourceFile[]
  warnings: TranspileWarning[]
  /** True when every source asset produced at least one file — a Publish job with unrecognized graph shapes should hold for review, not silently ship an empty script. */
  allSourcesCompiled: boolean
}

export type VisualScriptBytecodeShipReceipt = {
  version: 1
  vsToTsTranspileReady: boolean
  generatedFileCount: number
  contentFingerprint: string
  wasmBytecodeShipReady: false
  vsToWasmMarketingAllowed: false
  shipStatus: 'PARTIAL' | 'HELD'
}

function extractClassName(code: string): string {
  const match = /export class (\w+)/.exec(code)
  return match?.[1] ?? 'GeneratedScript'
}

function isVisualScript(graph: unknown): graph is VisualScript {
  return Boolean(graph) && typeof graph === 'object' && Array.isArray((graph as VisualScript).nodes) && Array.isArray((graph as VisualScript).edges)
}

function isAbilityGraph(graph: unknown): graph is AbilityGraph {
  return Boolean(graph) && typeof graph === 'object' && Array.isArray((graph as AbilityGraph).nodes) && Array.isArray((graph as AbilityGraph).edges)
}

function compileAbilityGraphSource(ability: CompiledAbility): string {
  return [
    `// AUTO-GENERATED by the Aethel Logic Transpiler (Cook & Build Pipeline, Stage 2).`,
    `// Source ability graph: ${ability.name} (${ability.id})`,
    `// Balance: resourceCost=${ability.meta.resourceCost} cooldownSec=${ability.meta.cooldownSec} estimatedDPS=${ability.meta.estimatedDPS.toFixed(1)}`,
    `export const ${sanitizeIdentifier(ability.name)}Ability = {`,
    `  id: ${JSON.stringify(ability.id)},`,
    `  name: ${JSON.stringify(ability.name)},`,
    `  executor: ${ability.generatorSource},`,
    `};`,
    '',
  ].join('\n')
}

function sanitizeIdentifier(name: string): string {
  const cleaned = name.replace(/[^a-zA-Z0-9_]+/g, ' ').trim()
  const pascal = cleaned
    .split(/\s+/)
    .filter(Boolean)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
  return pascal || 'Generated'
}

export function transpileProjectScripts(sources: TranspileSourceAsset[]): TranspileStageResult {
  const files: GeneratedSourceFile[] = []
  const warnings: TranspileWarning[] = []
  let allSourcesCompiled = true

  for (const source of sources) {
    if (source.kind === 'visual-script' && isVisualScript(source.graph)) {
      const { code, warnings: compileWarnings } = VisualScriptCompiler.compile(source.graph)
      const exportedClassName = extractClassName(code)
      files.push({
        path: `generated/scripts/${exportedClassName}.ts`,
        content: code,
        exportedClassName,
        sourceAssetId: source.assetId,
      })
      for (const message of compileWarnings) {
        warnings.push({ sourceAssetId: source.assetId, sourceAssetName: source.assetName, message, severity: 'codegen-gap' })
      }
      continue
    }

    if (source.kind === 'ability-graph' && isAbilityGraph(source.graph)) {
      const compiled = new AbilityGraphCompiler(source.graph).compile()
      const identifier = sanitizeIdentifier(compiled.name)
      files.push({
        path: `generated/abilities/${identifier}Ability.ts`,
        content: compileAbilityGraphSource(compiled),
        exportedClassName: `${identifier}Ability`,
        sourceAssetId: source.assetId,
      })
      if (compiled.meta.hasCycle) {
        warnings.push({
          sourceAssetId: source.assetId,
          sourceAssetName: source.assetName,
          message: 'Ability graph has a cycle — compiled to a no-op blocked executor. Fix the graph and republish.',
          severity: 'balance-review',
        })
      }
      for (const message of compiled.meta.balanceWarnings) {
        warnings.push({ sourceAssetId: source.assetId, sourceAssetName: source.assetName, message, severity: 'balance-review' })
      }
      continue
    }

    allSourcesCompiled = false
    warnings.push({
      sourceAssetId: source.assetId,
      sourceAssetName: source.assetName,
      message: `Asset kind "${source.kind}" graph payload did not match the expected shape — skipped, no file generated.`,
      severity: 'codegen-gap',
    })
  }

  return { files, warnings, allSourcesCompiled }
}

/**
 * Fail-closed VS→WASM ship receipt — TS string transpile may be ready; bytecode/WASM ship never auto-flips.
 */
export function sealVisualScriptBytecodeShipReceipt(
  result: TranspileStageResult,
): VisualScriptBytecodeShipReceipt {
  const hash = createHash('sha256')
  for (const file of result.files) {
    hash.update(file.path)
    hash.update('\0')
    hash.update(file.content)
    hash.update('\0')
  }
  const contentFingerprint = hash.digest('hex').slice(0, 16)
  const vsToTsTranspileReady = result.allSourcesCompiled && result.files.length > 0

  if (VS_WASM_BYTECODE_SHIP_READY || VS_TO_WASM_MARKETING_ALLOWED) {
    throw new Error('VS→WASM product/marketing flags must remain false')
  }

  return {
    version: 1,
    vsToTsTranspileReady,
    generatedFileCount: result.files.length,
    contentFingerprint,
    wasmBytecodeShipReady: false,
    vsToWasmMarketingAllowed: false,
    shipStatus: vsToTsTranspileReady ? 'PARTIAL' : 'HELD',
  }
}

/**
 * Publish refuse — claiming VS→WASM bytecode ship without Law VII cook.
 */
export function refusePackWithoutVsWasmBytecodeEvidence(input: {
  claimWasmBytecodeShipReady?: boolean
  transpile?: TranspileStageResult
}):
  | { ok: true; receipt: VisualScriptBytecodeShipReceipt; wasmBytecodeShipReady: false }
  | { ok: false; code: 'product_claim_held'; message: string } {
  if (input.claimWasmBytecodeShipReady === true) {
    return {
      ok: false,
      code: 'product_claim_held',
      message: 'VS→WASM bytecode ship claim refused — Law VII Worker bytecode HELD',
    }
  }
  const transpile = input.transpile ?? { files: [], warnings: [], allSourcesCompiled: true }
  return {
    ok: true,
    receipt: sealVisualScriptBytecodeShipReceipt(transpile),
    wasmBytecodeShipReady: false,
  }
}
