import path from 'node:path';
import { existsSync } from 'node:fs';
import type AdmZip from 'adm-zip';
import { addWebTemplate } from './build-queue-worker-web-template';
import type { BuildQueueMessage } from './build-queue-worker-contracts';
import { nowIso } from './build-queue-worker.utils';

interface PackageProjectSnapshot {
  id: string;
  name: string;
  userId: string;
  settings: unknown;
  createdAt: Date;
  updatedAt: Date;
}

interface PackageScaffoldOptions {
  msg: BuildQueueMessage;
  project: PackageProjectSnapshot;
  platform: string;
  templatesDir: string;
}

export function addPackageScaffold(zip: AdmZip, options: PackageScaffoldOptions): string[] {
  const { msg, project, platform, templatesDir } = options;
  const platformWarnings: string[] = [];

  if (['windows', 'linux', 'macos'].includes(platform)) {
    const templatePath = path.join(templatesDir, platform);
    if (existsSync(templatePath)) {
      zip.addLocalFolder(templatePath, '');
    } else {
      zip.addFile('README_PLATFORM.txt', Buffer.from(`Missing runtime template for ${platform}`, 'utf8'));
      platformWarnings.push(`Missing runtime template for ${platform}. Export contains source and assets only.`);
    }
  } else if (platform === 'web') {
    addWebTemplate(zip, project.name || 'Aethel Project');
    platformWarnings.push('Web runtime is minimal. Use your build pipeline to finalize Web export.');
  } else if (platform === 'ios' || platform === 'android') {
    zip.addFile('README_MOBILE.txt', Buffer.from(`Mobile export (${platform}) - use source and assets to build native project.`, 'utf8'));
    platformWarnings.push(`Mobile export (${platform}) requires native toolchain (Xcode/Android Studio).`);
  } else if (platform === 'source') {
    platformWarnings.push('Source export includes project files and assets only.');
  }

  zip.addFile(
    'export.json',
    Buffer.from(
      JSON.stringify(
        {
          exportId: msg.exportId,
          projectId: msg.projectId,
          userId: msg.userId,
          platform: msg.platform,
          configuration: msg.configuration,
          options: msg.options || null,
          createdAt: nowIso(),
        },
        null,
        2,
      ),
      'utf8',
    ),
  );
  zip.addFile(
    'project.json',
    Buffer.from(
      JSON.stringify(
        {
          id: project.id,
          name: project.name,
          ownerId: project.userId,
          settings: project.settings,
          createdAt: project.createdAt,
          updatedAt: project.updatedAt,
        },
        null,
        2,
      ),
      'utf8',
    ),
  );
  zip.addFile('README.txt', Buffer.from('Aethel Export\n\nArtifact generated by the internal worker.\n', 'utf8'));

  return platformWarnings;
}
