'use client';

import React, { useState, useRef, useCallback } from 'react';
import {
  Activity,
  Contrast,
  Download,
  Droplets,
  Eye,
  FileDown,
  Flame,
  Maximize2,
  RotateCcw,
  Sliders,
  Sparkles,
  Sun,
  Thermometer,
} from 'lucide-react';

export interface ColorWheelValue {
  x: number; // -1 to 1 (saturation & hue vector)
  y: number; // -1 to 1
  luma: number; // -1 to 1 (luminance offset)
}

export interface ColorGradingConfig {
  lift: ColorWheelValue;
  gamma: ColorWheelValue;
  gain: ColorWheelValue;
  offset: ColorWheelValue;
  temperature: number; // Kelvin 2000 to 12000 (default 6500)
  tint: number; // -100 to 100
  contrast: number; // 0.5 to 2.0 (default 1.0)
  pivot: number; // 0 to 1 (default 0.435 ACES)
  saturation: number; // 0 to 2.0 (default 1.0)
}

const DEFAULT_COLOR_GRADING: ColorGradingConfig = {
  lift: { x: 0, y: 0, luma: 0 },
  gamma: { x: 0, y: 0, luma: 0 },
  gain: { x: 0, y: 0, luma: 0 },
  offset: { x: 0, y: 0, luma: 0 },
  temperature: 6500,
  tint: 0,
  contrast: 1.0,
  pivot: 0.435,
  saturation: 1.0,
};

/**
 * Generates an industry-standard .CUBE 3D LUT (size 17x17x17)
 * compatible with Unreal Engine 5.5 Post-Process Volumes and DaVinci Resolve Studio.
 */
function generate3DLutCube(config: ColorGradingConfig): string {
  const size = 17;
  const lines: string[] = [
    '# Aethel Engine — ACES 1.3 3D Color Grading LUT',
    '# Generated by Aethel Studio Cinematic Colorist',
    `TITLE "Aethel_ACES_Grade_${Date.now()}"`,
    `LUT_3D_SIZE ${size}`,
    'DOMAIN_MIN 0.0 0.0 0.0',
    'DOMAIN_MAX 1.0 1.0 1.0',
    '',
  ];

  // Temp Kelvin multiplier approximation
  const tempRatio = (config.temperature - 6500) / 6500;
  const rTemp = 1.0 + (tempRatio > 0 ? tempRatio * 0.2 : tempRatio * 0.3);
  const bTemp = 1.0 - (tempRatio > 0 ? tempRatio * 0.3 : tempRatio * 0.2);

  for (let b = 0; b < size; b++) {
    for (let g = 0; g < size; g++) {
      for (let r = 0; r < size; r++) {
        let red = r / (size - 1);
        let green = g / (size - 1);
        let blue = b / (size - 1);

        // Apply Lift (Shadows)
        red += config.lift.x * 0.15 + config.lift.luma * 0.1;
        green += config.lift.luma * 0.1;
        blue += config.lift.y * 0.15 + config.lift.luma * 0.1;

        // Apply Gain (Highlights)
        red *= 1.0 + config.gain.x * 0.2 + config.gain.luma * 0.2;
        green *= 1.0 + config.gain.luma * 0.2;
        blue *= 1.0 + config.gain.y * 0.2 + config.gain.luma * 0.2;

        // Apply Temperature
        red *= rTemp;
        blue *= bTemp;

        // Apply Contrast with ACES Pivot
        red = config.pivot + (red - config.pivot) * config.contrast;
        green = config.pivot + (green - config.pivot) * config.contrast;
        blue = config.pivot + (blue - config.pivot) * config.contrast;

        // Apply Saturation (Luma preservation)
        const luma = 0.2126 * red + 0.7152 * green + 0.0722 * blue;
        red = luma + (red - luma) * config.saturation;
        green = luma + (green - luma) * config.saturation;
        blue = luma + (blue - luma) * config.saturation;

        // Clamp to [0..1]
        red = Math.max(0, Math.min(1, red));
        green = Math.max(0, Math.min(1, green));
        blue = Math.max(0, Math.min(1, blue));

        lines.push(`${red.toFixed(6)} ${green.toFixed(6)} ${blue.toFixed(6)}`);
      }
    }
  }

  return lines.join('\n');
}

interface ColorWheelProps {
  label: string;
  subtitle: string;
  value: ColorWheelValue;
  onChange: (val: ColorWheelValue) => void;
  accentColor?: string;
}

function ColorWheel({ label, subtitle, value, onChange, accentColor = 'var(--aethel-primary)' }: ColorWheelProps) {
  const discRef = useRef<SVGSVGElement>(null);
  const [isDragging, setIsDragging] = useState(false);

  const handlePointerDown = (e: React.PointerEvent<SVGSVGElement>) => {
    e.currentTarget.setPointerCapture(e.pointerId);
    setIsDragging(true);
    updateVector(e);
  };

  const handlePointerMove = (e: React.PointerEvent<SVGSVGElement>) => {
    if (!isDragging) return;
    updateVector(e);
  };

  const handlePointerUp = (e: React.PointerEvent<SVGSVGElement>) => {
    setIsDragging(false);
    try {
      e.currentTarget.releasePointerCapture(e.pointerId);
    } catch {}
  };

  const updateVector = (e: React.PointerEvent<SVGSVGElement>) => {
    if (!discRef.current) return;
    const rect = discRef.current.getBoundingClientRect();
    const cx = rect.left + rect.width / 2;
    const cy = rect.top + rect.height / 2;
    const radius = rect.width / 2;

    let dx = (e.clientX - cx) / radius;
    let dy = (e.clientY - cy) / radius;
    const dist = Math.sqrt(dx * dx + dy * dy);

    if (dist > 1.0) {
      dx /= dist;
      dy /= dist;
    }

    onChange({
      ...value,
      x: Math.round(dx * 100) / 100,
      y: Math.round(-dy * 100) / 100, // invert Y for standard Cartesian
    });
  };

  const handleDoubleClick = () => {
    onChange({ ...value, x: 0, y: 0 });
  };

  // Convert Cartesian (-1..1) to SVG coordinates (0..100)
  const dotX = 50 + value.x * 45;
  const dotY = 50 - value.y * 45;

  return (
    <div className="flex flex-col items-center gap-2 rounded-xl border border-[var(--aethel-border-subtle)] bg-[color-mix(in_srgb,var(--aethel-surface-tertiary)_40%,transparent)] p-3.5">
      <div className="flex w-full items-center justify-between">
        <div>
          <h4 className="text-xs font-bold uppercase tracking-wider text-[var(--aethel-text-primary)]">
            {label}
          </h4>
          <span className="text-[9px] text-[var(--aethel-text-quaternary)]">{subtitle}</span>
        </div>
        <button
          type="button"
          onClick={handleDoubleClick}
          title="Reset to center (Double-click)"
          className="text-[var(--aethel-text-quaternary)] hover:text-[var(--aethel-text-secondary)] p-0.5 transition-colors"
        >
          <RotateCcw className="h-3 w-3" />
        </button>
      </div>

      {/* SVG Vector Disc (DaVinci Resolve Chromatic Standard) */}
      <div className="relative aspect-square w-32 select-none">
        <svg
          ref={discRef}
          viewBox="0 0 100 100"
          onPointerDown={handlePointerDown}
          onPointerMove={handlePointerMove}
          onPointerUp={handlePointerUp}
          onDoubleClick={handleDoubleClick}
          className="h-full w-full cursor-crosshair overflow-visible"
        >
          <defs>
            {/* Chromatic outer glow ring */}
            <radialGradient id={`wheel-grad-${label}`} cx="50%" cy="50%" r="50%">
              <stop offset="0%" stopColor="#ffffff" stopOpacity="0.85" />
              <stop offset="45%" stopColor="color-mix(in srgb, var(--aethel-primary) 30%, transparent)" stopOpacity="0.4" />
              <stop offset="100%" stopColor="color-mix(in srgb, var(--aethel-neon-cyan) 60%, transparent)" stopOpacity="0.6" />
            </radialGradient>
          </defs>

          {/* Disc background with hue sectors */}
          <circle cx="50" cy="50" r="46" fill="var(--aethel-surface-primary)" />
          <circle cx="50" cy="50" r="46" fill={`url(#wheel-grad-${label})`} opacity="0.4" />
          
          {/* Subtle color hue tint sectors (R: top-right, G: top-left, B: bottom) */}
          <circle cx="50" cy="50" r="46" fill="none" stroke="var(--aethel-border-secondary)" strokeWidth="1.5" />
          <circle cx="50" cy="50" r="23" fill="none" stroke="var(--aethel-border-subtle)" strokeDasharray="2 2" />
          <circle cx="50" cy="50" r="35" fill="none" stroke="var(--aethel-border-subtle)" strokeWidth="0.5" strokeDasharray="1 3" />

          {/* Chromatic reference tick marks: R, G, B, C, M, Y */}
          <line x1="50" y1="4" x2="50" y2="10" stroke="var(--aethel-error)" strokeWidth="1.5" />
          <line x1="86" y1="29" x2="81" y2="32" stroke="var(--aethel-warning)" strokeWidth="1.5" />
          <line x1="86" y1="71" x2="81" y2="68" stroke="var(--aethel-success)" strokeWidth="1.5" />
          <line x1="50" y1="96" x2="50" y2="90" stroke="var(--aethel-neon-cyan)" strokeWidth="1.5" />
          <line x1="14" y1="71" x2="19" y2="68" stroke="var(--aethel-info)" strokeWidth="1.5" />
          <line x1="14" y1="29" x2="19" y2="32" stroke="var(--aethel-accent)" strokeWidth="1.5" />

          {/* Crosshair axes */}
          <line x1="50" y1="12" x2="50" y2="88" stroke="var(--aethel-border-subtle)" strokeWidth="0.75" />
          <line x1="12" y1="50" x2="88" y2="50" stroke="var(--aethel-border-subtle)" strokeWidth="0.75" />

          {/* Vector handle line from center to dot */}
          <line x1="50" y1="50" x2={dotX} y2={dotY} stroke={accentColor} strokeWidth="1.5" opacity="0.9" />

          {/* Draggable Indicator Dot with halo */}
          <circle
            cx={dotX}
            cy={dotY}
            r="5"
            fill="var(--aethel-text-primary)"
            stroke={accentColor}
            strokeWidth="2"
            className="filter drop-shadow-[0_0_6px_var(--aethel-primary)]"
          />
        </svg>
      </div>

      {/* Numerical readout */}
      <div className="flex w-full justify-between text-[9px] font-mono text-[var(--aethel-text-quaternary)]">
        <span>X: {value.x > 0 ? `+${value.x.toFixed(2)}` : value.x.toFixed(2)}</span>
        <span>Y: {value.y > 0 ? `+${value.y.toFixed(2)}` : value.y.toFixed(2)}</span>
      </div>

      {/* Master luminance slider for this wheel */}
      <div className="w-full space-y-1">
        <div className="flex justify-between text-[9px] font-mono text-[var(--aethel-text-tertiary)]">
          <span>Luma</span>
          <span>{value.luma > 0 ? `+${value.luma.toFixed(2)}` : value.luma.toFixed(2)}</span>
        </div>
        <input
          type="range"
          min={-1}
          max={1}
          step={0.01}
          value={value.luma}
          onChange={(e) => onChange({ ...value, luma: parseFloat(e.target.value) })}
          className="h-1.5 w-full cursor-pointer appearance-none bg-[var(--aethel-surface-primary)] rounded-full"
        />
      </div>
    </div>
  );
}

// ── RGB Parade Scope Component ─────────────────────────────────────────────

function RGBParadeScope() {
  return (
    <div className="rounded-xl border border-[var(--aethel-border-subtle)] bg-[var(--aethel-surface-primary)] p-3">
      <div className="flex items-center justify-between mb-2">
        <span className="text-[10px] font-bold uppercase tracking-[0.14em] text-[var(--aethel-text-quaternary)]">
          RGB Parade Scope (ACES 1.3 ODT)
        </span>
        <span className="font-mono text-[9px] text-[var(--aethel-neon-cyan)]">0–100 IRE</span>
      </div>

      {/* Simulated waveform tracks (R, G, B channels) */}
      <div className="grid grid-cols-3 gap-2 h-24 rounded-lg bg-[color-mix(in_srgb,var(--aethel-surface-secondary)_80%,transparent)] p-2 border border-[var(--aethel-border-subtle)]">
        {/* Red Channel */}
        <div className="relative flex flex-col justify-end overflow-hidden border-r border-[var(--aethel-border-subtle)] pr-2">
          <span className="absolute top-0 left-0 font-mono text-[8px] font-bold text-[var(--aethel-error-light)]">R</span>
          <div className="h-3/4 w-full opacity-60 rounded-sm bg-gradient-to-t from-[var(--aethel-error)] via-[#fca5a5] to-transparent" />
        </div>
        {/* Green Channel */}
        <div className="relative flex flex-col justify-end overflow-hidden border-r border-[var(--aethel-border-subtle)] pr-2">
          <span className="absolute top-0 left-0 font-mono text-[8px] font-bold text-[var(--aethel-success-light)]">G</span>
          <div className="h-2/3 w-full opacity-60 rounded-sm bg-gradient-to-t from-[var(--aethel-success)] via-[#86efac] to-transparent" />
        </div>
        {/* Blue Channel */}
        <div className="relative flex flex-col justify-end overflow-hidden">
          <span className="absolute top-0 left-0 font-mono text-[8px] font-bold text-[var(--aethel-info-light)]">B</span>
          <div className="h-4/5 w-full opacity-60 rounded-sm bg-gradient-to-t from-[var(--aethel-info)] via-[#a5f3fc] to-transparent" />
        </div>
      </div>
    </div>
  );
}

// ── Main Color Grading Panel ───────────────────────────────────────────────

interface ColorGradingWheelsProps {
  config?: ColorGradingConfig;
  onChange?: (config: ColorGradingConfig) => void;
}

export function ColorGradingWheels({
  config = DEFAULT_COLOR_GRADING,
  onChange,
}: ColorGradingWheelsProps) {
  const [current, setCurrent] = useState<ColorGradingConfig>(config);

  const update = <K extends keyof ColorGradingConfig>(key: K, value: ColorGradingConfig[K]) => {
    const next = { ...current, [key]: value };
    setCurrent(next);
    onChange?.(next);
  };

  const handleResetAll = () => {
    setCurrent(DEFAULT_COLOR_GRADING);
    onChange?.(DEFAULT_COLOR_GRADING);
  };

  const handleExportCubeLUT = () => {
    const cubeContent = generate3DLutCube(current);
    const blob = new Blob([cubeContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Aethel_Grade_ACES_${Date.now()}.cube`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 rounded-2xl border border-[var(--aethel-border-subtle)] bg-[color-mix(in_srgb,var(--aethel-surface-secondary)_50%,transparent)] p-5 backdrop-blur-xl">
      {/* Top Header */}
      <div className="flex items-center justify-between border-b border-[var(--aethel-border-subtle)] pb-3">
        <div>
          <h3 className="text-sm font-bold uppercase tracking-wider text-[var(--aethel-text-primary)]">
            Color Grading (ACES 1.3 HDR)
          </h3>
          <p className="text-[11px] text-[var(--aethel-text-tertiary)]">
            3-Way HDR Wheels, Kelvin Temperature, and DaVinci / UE5 .CUBE LUT Export
          </p>
        </div>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleExportCubeLUT}
            className="inline-flex items-center gap-1.5 rounded-lg border border-[color-mix(in_srgb,var(--aethel-neon-cyan)_40%,transparent)] bg-[color-mix(in_srgb,var(--aethel-neon-cyan)_12%,transparent)] px-3 py-1.5 text-xs font-semibold text-[var(--aethel-neon-cyan)] hover:bg-[color-mix(in_srgb,var(--aethel-neon-cyan)_22%,transparent)] transition-all active:scale-95 shadow-sm"
            title="Export 3D LUT (.CUBE) for Unreal Engine 5 or DaVinci Resolve"
          >
            <FileDown className="h-3.5 w-3.5" /> Export .CUBE LUT
          </button>
          <button
            type="button"
            onClick={handleResetAll}
            className="inline-flex items-center gap-1.5 rounded-lg border border-[var(--aethel-border-subtle)] bg-[color-mix(in_srgb,var(--aethel-surface-tertiary)_60%,transparent)] px-3 py-1.5 text-xs font-semibold text-[var(--aethel-text-secondary)] hover:text-[var(--aethel-text-primary)] transition-all active:scale-95"
          >
            <RotateCcw className="h-3.5 w-3.5" /> Reset All
          </button>
        </div>
      </div>

      {/* 4-Way Color Wheels Grid (Lift, Gamma, Gain, Offset) */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <ColorWheel
          label="Lift"
          subtitle="Shadows / Black Point"
          value={current.lift}
          onChange={(v) => update('lift', v)}
          accentColor="var(--aethel-info)"
        />
        <ColorWheel
          label="Gamma"
          subtitle="Midtones / Exposure"
          value={current.gamma}
          onChange={(v) => update('gamma', v)}
          accentColor="var(--aethel-success)"
        />
        <ColorWheel
          label="Gain"
          subtitle="Highlights / White Point"
          value={current.gain}
          onChange={(v) => update('gain', v)}
          accentColor="var(--aethel-warning)"
        />
        <ColorWheel
          label="Offset"
          subtitle="Master Color Balance"
          value={current.offset}
          onChange={(v) => update('offset', v)}
          accentColor="var(--aethel-primary)"
        />
      </div>

      {/* Secondary Controls & RGB Parade Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 pt-2 border-t border-[var(--aethel-border-subtle)]">
        {/* Sliders for Temp, Tint, Contrast, Saturation */}
        <div className="space-y-4">
          {/* Temperature Kelvin */}
          <div>
            <div className="flex justify-between text-xs mb-1">
              <span className="font-semibold text-[var(--aethel-text-secondary)] flex items-center gap-1">
                <Thermometer className="h-3.5 w-3.5 text-[var(--aethel-warning)]" /> Temperature
              </span>
              <span className="font-mono text-[var(--aethel-text-primary)]">{current.temperature}K</span>
            </div>
            <input
              type="range"
              min={2000}
              max={12000}
              step={50}
              value={current.temperature}
              onChange={(e) => update('temperature', parseInt(e.target.value, 10))}
              className="w-full cursor-pointer"
            />
          </div>

          {/* Tint */}
          <div>
            <div className="flex justify-between text-xs mb-1">
              <span className="font-semibold text-[var(--aethel-text-secondary)]">Tint (Green / Magenta)</span>
              <span className="font-mono text-[var(--aethel-text-primary)]">
                {current.tint > 0 ? `+${current.tint}` : current.tint}
              </span>
            </div>
            <input
              type="range"
              min={-100}
              max={100}
              value={current.tint}
              onChange={(e) => update('tint', parseInt(e.target.value, 10))}
              className="w-full cursor-pointer"
            />
          </div>

          {/* Contrast & Saturation Row */}
          <div className="grid grid-cols-2 gap-4">
            <div>
              <div className="flex justify-between text-xs mb-1">
                <span className="font-semibold text-[var(--aethel-text-secondary)]">Contrast</span>
                <span className="font-mono text-[var(--aethel-text-primary)]">{current.contrast.toFixed(2)}x</span>
              </div>
              <input
                type="range"
                min={0.5}
                max={2.0}
                step={0.01}
                value={current.contrast}
                onChange={(e) => update('contrast', parseFloat(e.target.value))}
                className="w-full cursor-pointer"
              />
            </div>

            <div>
              <div className="flex justify-between text-xs mb-1">
                <span className="font-semibold text-[var(--aethel-text-secondary)]">Master Saturation</span>
                <span className="font-mono text-[var(--aethel-text-primary)]">
                  {Math.round(current.saturation * 100)}%
                </span>
              </div>
              <input
                type="range"
                min={0}
                max={2.0}
                step={0.01}
                value={current.saturation}
                onChange={(e) => update('saturation', parseFloat(e.target.value))}
                className="w-full cursor-pointer"
              />
            </div>
          </div>
        </div>

        {/* RGB Parade Scope Visualizer */}
        <RGBParadeScope />
      </div>
    </div>
  );
}
