import type { SettingItem } from './SettingsPage.types'

export const ENGINE_SETTING_ITEMS: SettingItem[] = [
  {
    id: 'engine.physics.enabled',
    label: 'Enable Physics',
    description: 'Enable physics simulation',
    type: 'toggle',
    value: true,
    defaultValue: true,
    category: 'engine',
    subcategory: 'physics',
  },
  {
    id: 'engine.physics.gravity',
    label: 'Gravity',
    description: 'World gravity value',
    type: 'number',
    value: -9.81,
    defaultValue: -9.81,
    min: -20,
    max: 0,
    step: 0.1,
    category: 'engine',
    subcategory: 'physics',
  },
  {
    id: 'engine.shadows.quality',
    label: 'Shadow Quality',
    description: 'Quality of shadow rendering',
    type: 'select',
    value: 'high',
    defaultValue: 'high',
    options: [
      { label: 'Off', value: 'off' },
      { label: 'Low', value: 'low' },
      { label: 'Medium', value: 'medium' },
      { label: 'High', value: 'high' },
      { label: 'Ultra', value: 'ultra' },
    ],
    category: 'engine',
    subcategory: 'rendering',
  },
  {
    id: 'engine.particles.quality',
    label: 'Particle Quality',
    description: 'Quality of particle effects',
    type: 'select',
    value: 'high',
    defaultValue: 'high',
    options: [
      { label: 'Low', value: 'low' },
      { label: 'Medium', value: 'medium' },
      { label: 'High', value: 'high' },
    ],
    category: 'engine',
    subcategory: 'particles',
  },
  {
    id: 'engine.raytracing.enabled',
    label: 'Ray Tracing',
    description: 'Enable ray tracing (requires compatible hardware)',
    type: 'toggle',
    value: false,
    defaultValue: false,
    category: 'engine',
    subcategory: 'rendering',
    requiresReload: true,
  },
  {
    id: 'engine.nanite.viewport',
    label: 'Nanite-style meshlets (viewport)',
    description: 'Enable virtualized geometry path in the browser viewport when hardware allows',
    type: 'toggle',
    value: false,
    defaultValue: false,
    category: 'engine',
    subcategory: 'rendering',
    requiresReload: true,
  },
  {
    id: 'engine.vsync',
    label: 'VSync',
    description: 'Enable vertical sync',
    type: 'toggle',
    value: true,
    defaultValue: true,
    category: 'engine',
    subcategory: 'performance',
  },
  {
    id: 'engine.targetFPS',
    label: 'Target FPS',
    description: 'Target frame rate',
    type: 'select',
    value: 60,
    defaultValue: 60,
    options: [
      { label: '30 FPS', value: 30 },
      { label: '60 FPS', value: 60 },
      { label: '120 FPS', value: 120 },
      { label: '144 FPS', value: 144 },
      { label: 'Unlimited', value: 0 },
    ],
    category: 'engine',
    subcategory: 'performance',
  },
]
