import type { SettingItem } from './SettingsPage.types'

export const TERMINAL_AND_GIT_SETTING_ITEMS: SettingItem[] = [
  {
    id: 'terminal.fontSize',
    label: 'Font Size',
    description: 'Controls the font size in the terminal',
    type: 'number',
    value: 13,
    defaultValue: 13,
    min: 8,
    max: 24,
    category: 'terminal',
  },
  {
    id: 'terminal.cursorStyle',
    label: 'Cursor Style',
    description: 'Controls the cursor style',
    type: 'select',
    value: 'block',
    defaultValue: 'block',
    options: [
      { label: 'Block', value: 'block' },
      { label: 'Line', value: 'line' },
      { label: 'Underline', value: 'underline' },
    ],
    category: 'terminal',
  },
  {
    id: 'terminal.scrollback',
    label: 'Scrollback',
    description: 'Number of lines to keep in scrollback',
    type: 'number',
    value: 10000,
    defaultValue: 10000,
    min: 1000,
    max: 100000,
    category: 'terminal',
  },
  {
    id: 'git.enabled',
    label: 'Enable Git',
    description: 'Enable Git integration',
    type: 'toggle',
    value: true,
    defaultValue: true,
    category: 'git',
  },
  {
    id: 'git.autoFetch',
    label: 'Auto Fetch',
    description: 'Automatically fetch from remotes',
    type: 'toggle',
    value: true,
    defaultValue: true,
    category: 'git',
  },
  {
    id: 'git.confirmSync',
    label: 'Confirm Sync',
    description: 'Confirm before syncing changes',
    type: 'toggle',
    value: true,
    defaultValue: true,
    category: 'git',
  },
  {
    id: 'git.showInlineBlame',
    label: 'Inline Blame',
    description: 'Show blame info inline',
    type: 'toggle',
    value: false,
    defaultValue: false,
    category: 'git',
  },
]
