import { DEFAULT_OPENROUTER_MODEL_ID } from '@/lib/ai/openrouter-models'

import type { SettingsState } from './SettingsPage.types'

export const DEFAULT_SETTINGS: SettingsState = {
  'editor.fontSize': 14,
  'editor.fontFamily': 'JetBrains Mono, Fira Code, monospace',
  'editor.tabSize': 2,
  'editor.wordWrap': 'on',
  'editor.minimap': true,
  'editor.lineNumbers': 'on',
  'editor.renderWhitespace': 'selection',
  'editor.formatOnSave': true,
  'editor.formatOnPaste': false,
  'editor.autoSave': 'afterDelay',
  'editor.autoSaveDelay': 1000,
  'editor.cursorBlinking': 'blink',
  'editor.cursorStyle': 'line',
  'editor.smoothScrolling': true,
  'editor.bracketPairColorization': true,
  'editor.guides.indentation': true,
  'editor.stickyScroll.enabled': true,
  'editor.inlineSuggest.enabled': true,

  'ai.enabled': true,
  'ai.provider': 'openai',
  'ai.model': DEFAULT_OPENROUTER_MODEL_ID,
  'ai.inlineCompletion': true,
  'ai.completionDelay': 300,
  'ai.maxTokens': 2048,
  'ai.temperature': 0.7,
  'ai.chatPosition': 'right',
  'ai.showTokenCount': true,
  'ai.streamResponses': true,
  'ai.codeContext.enabled': true,
  'ai.codeContext.maxFiles': 10,
  'ai.codeContext.maxLines': 500,
  'ai.byok.enabled': false,
  'ai.byok.openaiKey': '',
  'ai.byok.anthropicKey': '',
  'ai.byok.googleKey': '',
  'ai.byok.openrouterKey': '',

  'terminal.fontSize': 13,
  'terminal.fontFamily': 'JetBrains Mono, monospace',
  'terminal.cursorStyle': 'block',
  'terminal.cursorBlink': true,
  'terminal.scrollback': 10000,
  'terminal.shell.windows': 'powershell',
  'terminal.shell.linux': 'bash',
  'terminal.shell.osx': 'zsh',
  'terminal.copyOnSelect': true,
  'terminal.rightClickBehavior': 'paste',

  'git.enabled': true,
  'git.autoFetch': true,
  'git.autoFetchPeriod': 180,
  'git.confirmSync': true,
  'git.enableSmartCommit': true,
  'git.autofetch': true,
  'git.pruneOnFetch': true,
  'git.defaultBranchName': 'main',
  'git.showInlineBlame': false,

  'engine.physics.enabled': true,
  'engine.physics.gravity': -9.81,
  'engine.physics.timeStep': 0.016,
  'engine.particles.quality': 'high',
  'engine.particles.maxCount': 100000,
  'engine.shadows.enabled': true,
  'engine.shadows.quality': 'high',
  'engine.shadows.cascades': 4,
  'engine.viewport.fidelity': 'balanced',
  'engine.antialiasing': 'msaa',
  'engine.antialiasing.samples': 4,
  'engine.vsync': true,
  'engine.targetFPS': 60,
  'engine.lod.enabled': true,
  'engine.lod.bias': 1.0,

  'appearance.theme': 'dark',
  'appearance.colorScheme': 'default',
  'appearance.iconTheme': 'default',
  'appearance.sidebarPosition': 'left',
  'appearance.activityBarPosition': 'side',
  'appearance.menuBarVisibility': 'visible',
  'appearance.statusBarVisible': true,
  'appearance.breadcrumbs': true,
  'appearance.tabsMultipleRows': false,
  'appearance.compactFolders': true,

  'notifications.enabled': true,
  'notifications.sound': false,
  'notifications.showInStatusBar': true,
  'notifications.doNotDisturb': false,

  'privacy.telemetry': 'all',
  'privacy.crashReports': true,
  'security.workspace.trust.enabled': true,
  'security.workspace.trust.untrustedFiles': 'prompt',

  'sync.enabled': false,
  'sync.settings': true,
  'sync.keybindings': true,
  'sync.extensions': true,
  'sync.snippets': true,

  // ── Simulation Defaults ───────────────────────────────────────────────
  'simulation.timeDilation': 1.0,
  'simulation.targetPhysicsFPS': 60,
  'simulation.godMode': false,
  'simulation.infiniteResources': false,
  'simulation.noClip': false,
  'simulation.showColliders': false,
  'simulation.showNavmesh': false,
  'simulation.showSkeletons': false,
  'simulation.showFPSCounter': false,
  'simulation.showBoundingBoxes': false,

  // ── Controls Defaults ──────────────────────────────────────────────────
  'controls.action.moveForward': 'KeyW',
  'controls.action.moveBackward': 'KeyS',
  'controls.action.moveLeft': 'KeyA',
  'controls.action.moveRight': 'KeyD',
  'controls.action.jump': 'Space',
  'controls.action.sprint': 'ShiftLeft',
  'controls.action.crouch': 'ControlLeft',
  'controls.action.shoot': 'MouseButton0',
  'controls.action.aim': 'MouseButton2',
  'controls.action.interact': 'KeyE',
  'controls.action.reload': 'KeyR',
  'controls.action.openInventory': 'Escape',
  'controls.mouse.sensitivity': 50,
  'controls.mouse.invertY': false,
  'controls.mouse.smoothing': false,
  'controls.gamepad.deadzone': 12,
  'controls.gamepad.sensitivity': 50,
  'controls.gamepad.vibration': true,

  // ── Audio Defaults ─────────────────────────────────────────────────────
  'audio.masterVolume': 80,
  'audio.sfxVolume': 75,
  'audio.musicVolume': 60,
  'audio.voiceVolume': 90,
  'audio.uiClicksEnabled': true,
  'audio.compilationSounds': true,
  'audio.outputDevice': 'default',
  'audio.spatialAudio': true,

  // ── VR Defaults ────────────────────────────────────────────────────────
  'vr.enabled': false,
  'vr.trackingType': 'local-floor',
  'vr.renderScale': 1.0,
  'vr.comfortVignette': true,
  'vr.vignetteIntensity': 60,
  'vr.snapTurn': 45,
  'vr.handTracking': false,
  'vr.haptics': true,
}
