import type { SettingItem } from './SettingsPage.types'

export const VR_SETTING_ITEMS: SettingItem[] = [
  {
    id: 'vr.enabled',
    label: 'Enable VR / XR Mode',
    description: 'Launch the viewport in WebXR immersive-vr mode when a headset is detected.',
    type: 'toggle',
    value: false,
    defaultValue: false,
    category: 'vr',
    subcategory: 'general',
    requiresReload: true,
  },
  {
    id: 'vr.trackingType',
    label: 'Tracking Mode',
    description: 'Select the XR reference space that best matches your setup.',
    type: 'select',
    value: 'local-floor',
    defaultValue: 'local-floor',
    options: [
      { label: 'Seated (local)', value: 'local' },
      { label: 'Room-Scale (local-floor)', value: 'local-floor' },
      { label: 'Unbounded (large space)', value: 'unbounded' },
    ],
    category: 'vr',
    subcategory: 'general',
  },
  {
    id: 'vr.renderScale',
    label: 'Render Scale',
    description: 'Resolution multiplier for VR rendering. Lower values improve performance on mobile headsets.',
    type: 'slider',
    value: 1.0,
    defaultValue: 1.0,
    min: 0.5,
    max: 2.0,
    step: 0.1,
    category: 'vr',
    subcategory: 'rendering',
  },
  {
    id: 'vr.comfortVignette',
    label: 'Comfort Vignette',
    description: 'Apply a dynamic vignette during locomotion to reduce motion sickness.',
    type: 'toggle',
    value: true,
    defaultValue: true,
    category: 'vr',
    subcategory: 'comfort',
  },
  {
    id: 'vr.vignetteIntensity',
    label: 'Vignette Intensity',
    description: 'How strongly the comfort vignette darkens the edges during movement.',
    type: 'slider',
    value: 60,
    defaultValue: 60,
    min: 10,
    max: 100,
    step: 5,
    category: 'vr',
    subcategory: 'comfort',
  },
  {
    id: 'vr.snapTurn',
    label: 'Snap Turn (degrees)',
    description: 'Rotation step size for snap-turn locomotion. Set to 0 for smooth turn.',
    type: 'select',
    value: 45,
    defaultValue: 45,
    options: [
      { label: 'Smooth', value: 0 },
      { label: '15°', value: 15 },
      { label: '30°', value: 30 },
      { label: '45°', value: 45 },
      { label: '90°', value: 90 },
    ],
    category: 'vr',
    subcategory: 'comfort',
  },
  {
    id: 'vr.handTracking',
    label: 'Hand Tracking',
    description: 'Enable controller-free hand tracking when the headset supports it.',
    type: 'toggle',
    value: false,
    defaultValue: false,
    category: 'vr',
    subcategory: 'input',
  },
  {
    id: 'vr.haptics',
    label: 'Controller Haptics',
    description: 'Enable vibration haptics for XR controller interactions.',
    type: 'toggle',
    value: true,
    defaultValue: true,
    category: 'vr',
    subcategory: 'input',
  },
]
