import type { SettingItem } from './SettingsPage.types'

export const SYSTEM_SETTING_ITEMS: SettingItem[] = [
  {
    id: 'notifications.enabled',
    label: 'Enable Notifications',
    description: 'Show notifications',
    type: 'toggle',
    value: true,
    defaultValue: true,
    category: 'notifications',
  },
  {
    id: 'notifications.sound',
    label: 'Sound',
    description: 'Play sound with notifications',
    type: 'toggle',
    value: false,
    defaultValue: false,
    category: 'notifications',
  },
  {
    id: 'notifications.doNotDisturb',
    label: 'Do Not Disturb',
    description: 'Mute all notifications',
    type: 'toggle',
    value: false,
    defaultValue: false,
    category: 'notifications',
  },
  {
    id: 'privacy.telemetry',
    label: 'Telemetry',
    description: 'Send usage data to improve the product',
    type: 'select',
    value: 'all',
    defaultValue: 'all',
    options: [
      { label: 'All', value: 'all' },
      { label: 'Error only', value: 'error' },
      { label: 'Off', value: 'off' },
    ],
    category: 'privacy',
  },
  {
    id: 'privacy.crashReports',
    label: 'Crash Reports',
    description: 'Send crash reports',
    type: 'toggle',
    value: true,
    defaultValue: true,
    category: 'privacy',
  },
  {
    id: 'sync.enabled',
    label: 'Settings Sync',
    description: 'Sync settings across devices',
    type: 'toggle',
    value: false,
    defaultValue: false,
    category: 'sync',
  },
  {
    id: 'sync.settings',
    label: 'Sync Settings',
    description: 'Include settings in sync',
    type: 'toggle',
    value: true,
    defaultValue: true,
    category: 'sync',
  },
  {
    id: 'sync.keybindings',
    label: 'Sync Keybindings',
    description: 'Include keybindings in sync',
    type: 'toggle',
    value: true,
    defaultValue: true,
    category: 'sync',
  },
  {
    id: 'sync.extensions',
    label: 'Sync Extensions',
    description: 'Include extensions in sync',
    type: 'toggle',
    value: true,
    defaultValue: true,
    category: 'sync',
  },
]
