import { DEFAULT_OPENROUTER_MODEL_ID } from '@/lib/ai/openrouter-models'

import type { SettingsState } from './SettingsPage.types'

export const DEFAULT_SETTINGS: SettingsState = {
  'editor.fontSize': 14,
  'editor.fontFamily': 'JetBrains Mono, Fira Code, monospace',
  'editor.tabSize': 2,
  'editor.wordWrap': 'on',
  'editor.minimap': true,
  'editor.lineNumbers': 'on',
  'editor.renderWhitespace': 'selection',
  'editor.formatOnSave': true,
  'editor.formatOnPaste': false,
  'editor.autoSave': 'afterDelay',
  'editor.autoSaveDelay': 1000,
  'editor.cursorBlinking': 'blink',
  'editor.cursorStyle': 'line',
  'editor.smoothScrolling': true,
  'editor.bracketPairColorization': true,
  'editor.guides.indentation': true,
  'editor.stickyScroll.enabled': true,
  'editor.inlineSuggest.enabled': true,

  'ai.enabled': true,
  'ai.provider': 'openai',
  'ai.model': DEFAULT_OPENROUTER_MODEL_ID,
  'ai.inlineCompletion': true,
  'ai.completionDelay': 300,
  'ai.maxTokens': 2048,
  'ai.temperature': 0.7,
  'ai.chatPosition': 'right',
  'ai.showTokenCount': true,
  'ai.streamResponses': true,
  'ai.codeContext.enabled': true,
  'ai.codeContext.maxFiles': 10,
  'ai.codeContext.maxLines': 500,

  'terminal.fontSize': 13,
  'terminal.fontFamily': 'JetBrains Mono, monospace',
  'terminal.cursorStyle': 'block',
  'terminal.cursorBlink': true,
  'terminal.scrollback': 10000,
  'terminal.shell.windows': 'powershell',
  'terminal.shell.linux': 'bash',
  'terminal.shell.osx': 'zsh',
  'terminal.copyOnSelect': true,
  'terminal.rightClickBehavior': 'paste',

  'git.enabled': true,
  'git.autoFetch': true,
  'git.autoFetchPeriod': 180,
  'git.confirmSync': true,
  'git.enableSmartCommit': true,
  'git.autofetch': true,
  'git.pruneOnFetch': true,
  'git.defaultBranchName': 'main',
  'git.showInlineBlame': false,

  'engine.physics.enabled': true,
  'engine.physics.gravity': -9.81,
  'engine.physics.timeStep': 0.016,
  'engine.particles.quality': 'high',
  'engine.particles.maxCount': 100000,
  'engine.shadows.enabled': true,
  'engine.shadows.quality': 'high',
  'engine.shadows.cascades': 4,
  'engine.raytracing.enabled': false,
  'engine.antialiasing': 'msaa',
  'engine.antialiasing.samples': 4,
  'engine.vsync': true,
  'engine.targetFPS': 60,
  'engine.lod.enabled': true,
  'engine.lod.bias': 1.0,

  'appearance.theme': 'dark',
  'appearance.colorScheme': 'default',
  'appearance.iconTheme': 'default',
  'appearance.sidebarPosition': 'left',
  'appearance.activityBarPosition': 'side',
  'appearance.menuBarVisibility': 'visible',
  'appearance.statusBarVisible': true,
  'appearance.breadcrumbs': true,
  'appearance.tabsMultipleRows': false,
  'appearance.compactFolders': true,

  'notifications.enabled': true,
  'notifications.sound': false,
  'notifications.showInStatusBar': true,
  'notifications.doNotDisturb': false,

  'privacy.telemetry': 'all',
  'privacy.crashReports': true,
  'security.workspace.trust.enabled': true,
  'security.workspace.trust.untrustedFiles': 'prompt',

  'sync.enabled': false,
  'sync.settings': true,
  'sync.keybindings': true,
  'sync.extensions': true,
  'sync.snippets': true,
}
