import type { SettingItem } from './SettingsPage.types'

export const APPEARANCE_SETTING_ITEMS: SettingItem[] = [
  {
    id: 'appearance.theme',
    label: 'Theme',
    description: 'Select the color theme',
    type: 'select',
    value: 'dark',
    defaultValue: 'dark',
    options: [
      { label: 'Dark', value: 'dark' },
      { label: 'Light', value: 'light' },
      { label: 'System', value: 'system' },
    ],
    category: 'appearance',
    subcategory: 'theme',
  },
  {
    id: 'appearance.colorScheme',
    label: 'Color Scheme',
    description: 'Select the color scheme',
    type: 'select',
    value: 'default',
    defaultValue: 'default',
    options: [
      { label: 'Default', value: 'default' },
      { label: 'Dracula', value: 'dracula' },
      { label: 'One Dark Pro', value: 'one-dark-pro' },
      { label: 'GitHub Dark', value: 'github-dark' },
      { label: 'Nord', value: 'nord' },
      { label: 'Solarized Dark', value: 'solarized-dark' },
    ],
    category: 'appearance',
    subcategory: 'theme',
  },
  {
    id: 'appearance.sidebarPosition',
    label: 'Sidebar Position',
    description: 'Position of the sidebar',
    type: 'select',
    value: 'left',
    defaultValue: 'left',
    options: [
      { label: 'Left', value: 'left' },
      { label: 'Right', value: 'right' },
    ],
    category: 'appearance',
    subcategory: 'layout',
  },
  {
    id: 'appearance.statusBarVisible',
    label: 'Status Bar',
    description: 'Show the status bar',
    type: 'toggle',
    value: true,
    defaultValue: true,
    category: 'appearance',
    subcategory: 'layout',
  },
  {
    id: 'appearance.breadcrumbs',
    label: 'Breadcrumbs',
    description: 'Show breadcrumb navigation',
    type: 'toggle',
    value: true,
    defaultValue: true,
    category: 'appearance',
    subcategory: 'layout',
  },
]
