import type { SettingItem } from './SettingsPage.types'

export const AUDIO_SETTING_ITEMS: SettingItem[] = [
  {
    id: 'audio.masterVolume',
    label: 'Master Volume',
    description: 'Overall volume level for all audio output.',
    type: 'slider',
    value: 80,
    defaultValue: 80,
    min: 0,
    max: 100,
    step: 1,
    category: 'audio',
    subcategory: 'volumes',
  },
  {
    id: 'audio.sfxVolume',
    label: 'Sound Effects',
    description: 'Volume for in-game sound effects (footsteps, explosions, UI clicks).',
    type: 'slider',
    value: 75,
    defaultValue: 75,
    min: 0,
    max: 100,
    step: 1,
    category: 'audio',
    subcategory: 'volumes',
  },
  {
    id: 'audio.musicVolume',
    label: 'Music',
    description: 'Volume for background music and ambient soundscapes.',
    type: 'slider',
    value: 60,
    defaultValue: 60,
    min: 0,
    max: 100,
    step: 1,
    category: 'audio',
    subcategory: 'volumes',
  },
  {
    id: 'audio.voiceVolume',
    label: 'Voice / Dialogue',
    description: 'Volume for character voice lines and cutscene dialogue.',
    type: 'slider',
    value: 90,
    defaultValue: 90,
    min: 0,
    max: 100,
    step: 1,
    category: 'audio',
    subcategory: 'volumes',
  },
  {
    id: 'audio.uiClicksEnabled',
    label: 'UI Interaction Sounds',
    description: 'Play subtle click/hover sounds for editor UI interactions.',
    type: 'toggle',
    value: true,
    defaultValue: true,
    category: 'audio',
    subcategory: 'editor',
  },
  {
    id: 'audio.compilationSounds',
    label: 'Compilation Audio Feedback',
    description: 'Play success / error tones when the sandbox compilation completes.',
    type: 'toggle',
    value: true,
    defaultValue: true,
    category: 'audio',
    subcategory: 'editor',
  },
  {
    id: 'audio.outputDevice',
    label: 'Output Device',
    description: 'Select the audio output device to use.',
    type: 'select',
    value: 'default',
    defaultValue: 'default',
    options: [
      { label: 'System Default', value: 'default' },
      { label: 'Headphones', value: 'headphones' },
      { label: 'Speakers', value: 'speakers' },
    ],
    category: 'audio',
    subcategory: 'device',
  },
  {
    id: 'audio.spatialAudio',
    label: 'Spatial / 3D Audio',
    description: 'Enable 3D positional audio for scene objects (requires stereo output).',
    type: 'toggle',
    value: true,
    defaultValue: true,
    category: 'audio',
    subcategory: 'device',
  },
]
