import {
  DEFAULT_OPENROUTER_MODEL_ID,
  OPENROUTER_MODEL_OPTIONS,
} from '@/lib/ai/openrouter-models'

import type { SettingItem } from './SettingsPage.types'

export const AI_SETTING_ITEMS: SettingItem[] = [
  {
    id: 'ai.enabled',
    label: 'Enable AI Features',
    description: 'Enable or disable all AI features',
    type: 'toggle',
    value: true,
    defaultValue: true,
    category: 'ai',
    subcategory: 'general',
  },
  {
    id: 'ai.provider',
    label: 'AI Provider',
    description: 'Select the AI provider to use',
    type: 'select',
    value: 'openrouter',
    defaultValue: 'openrouter',
    options: [
      { label: 'OpenRouter', value: 'openrouter' },
      { label: 'OpenAI', value: 'openai' },
      { label: 'Anthropic (Claude)', value: 'anthropic' },
      { label: 'Google (Gemini)', value: 'google' },
      { label: 'DeepSeek', value: 'deepseek' },
      { label: 'Groq', value: 'groq' },
      { label: 'Ollama (Local)', value: 'ollama' },
    ],
    category: 'ai',
    subcategory: 'general',
  },
  {
    id: 'ai.model',
    label: 'AI Model',
    description: 'Select the AI model to use',
    type: 'select',
    value: DEFAULT_OPENROUTER_MODEL_ID,
    defaultValue: DEFAULT_OPENROUTER_MODEL_ID,
    options: OPENROUTER_MODEL_OPTIONS.map((option) => ({
      label: option.label,
      value: option.value,
    })),
    category: 'ai',
    subcategory: 'general',
  },
  {
    id: 'ai.inlineCompletion',
    label: 'Inline Completion',
    description: 'Show AI suggestions inline as you type',
    type: 'toggle',
    value: true,
    defaultValue: true,
    category: 'ai',
    subcategory: 'completion',
  },
  {
    id: 'ai.completionDelay',
    label: 'Completion Delay',
    description: 'Delay in ms before showing completions',
    type: 'slider',
    value: 300,
    defaultValue: 300,
    min: 100,
    max: 1000,
    step: 50,
    category: 'ai',
    subcategory: 'completion',
  },
  {
    id: 'ai.temperature',
    label: 'Temperature',
    description:
      'Controls randomness of AI responses (0 = deterministic, 1 = creative)',
    type: 'slider',
    value: 0.7,
    defaultValue: 0.7,
    min: 0,
    max: 1,
    step: 0.1,
    category: 'ai',
    subcategory: 'general',
  },
  {
    id: 'ai.chatPosition',
    label: 'Chat Position',
    description: 'Position of the AI chat panel',
    type: 'select',
    value: 'right',
    defaultValue: 'right',
    options: [
      { label: 'Right', value: 'right' },
      { label: 'Bottom', value: 'bottom' },
      { label: 'Floating', value: 'floating' },
    ],
    category: 'ai',
    subcategory: 'chat',
  },
  {
    id: 'ai.streamResponses',
    label: 'Stream Responses',
    description: 'Stream AI responses in real-time',
    type: 'toggle',
    value: true,
    defaultValue: true,
    category: 'ai',
    subcategory: 'chat',
  },
  {
    id: 'ai.byok.enabled',
    label: 'Bring Your Own Key (BYOK)',
    description: 'Enable Bring Your Own Key to use your own custom API keys. Bypasses Aethel daily/monthly billing quotas.',
    type: 'toggle',
    value: false,
    defaultValue: false,
    category: 'ai',
    subcategory: 'byok',
  },
  {
    id: 'ai.byok.openaiKey',
    label: 'OpenAI API Key',
    description: 'Your custom OpenAI API key (skips platform quota)',
    type: 'password',
    value: '',
    defaultValue: '',
    category: 'ai',
    subcategory: 'byok',
  },
  {
    id: 'ai.byok.anthropicKey',
    label: 'Anthropic API Key',
    description: 'Your custom Anthropic API key (skips platform quota)',
    type: 'password',
    value: '',
    defaultValue: '',
    category: 'ai',
    subcategory: 'byok',
  },
  {
    id: 'ai.byok.googleKey',
    label: 'Google Gemini API Key',
    description: 'Your custom Google Gemini API key (skips platform quota)',
    type: 'password',
    value: '',
    defaultValue: '',
    category: 'ai',
    subcategory: 'byok',
  },
  {
    id: 'ai.byok.openrouterKey',
    label: 'OpenRouter API Key',
    description: 'Your custom OpenRouter API key (skips platform quota)',
    type: 'password',
    value: '',
    defaultValue: '',
    category: 'ai',
    subcategory: 'byok',
  },
]
