import type { SettingItem } from './SettingsPage.types'

/**
 * Controls & Rebinding settings.
 * Keybinding items use type:'keybinding' and their value is a key-combo string
 * (e.g. "KeyW", "Space", "MouseButton1").
 * The settings UI renders these as "click to capture" rebind rows.
 */
export const CONTROLS_SETTING_ITEMS: SettingItem[] = [
  // ── Gameplay Actions (Rebindable) ──────────────────────────────────────
  {
    id: 'controls.action.moveForward',
    label: 'Move Forward',
    description: 'Move the player character forward.',
    type: 'keybinding',
    value: 'KeyW',
    defaultValue: 'KeyW',
    category: 'controls',
    subcategory: 'gameplay',
    tags: ['movement'],
  },
  {
    id: 'controls.action.moveBackward',
    label: 'Move Backward',
    description: 'Move the player character backward.',
    type: 'keybinding',
    value: 'KeyS',
    defaultValue: 'KeyS',
    category: 'controls',
    subcategory: 'gameplay',
    tags: ['movement'],
  },
  {
    id: 'controls.action.moveLeft',
    label: 'Move Left (Strafe)',
    description: 'Strafe the player character to the left.',
    type: 'keybinding',
    value: 'KeyA',
    defaultValue: 'KeyA',
    category: 'controls',
    subcategory: 'gameplay',
    tags: ['movement'],
  },
  {
    id: 'controls.action.moveRight',
    label: 'Move Right (Strafe)',
    description: 'Strafe the player character to the right.',
    type: 'keybinding',
    value: 'KeyD',
    defaultValue: 'KeyD',
    category: 'controls',
    subcategory: 'gameplay',
    tags: ['movement'],
  },
  {
    id: 'controls.action.jump',
    label: 'Jump',
    description: 'Make the player character jump.',
    type: 'keybinding',
    value: 'Space',
    defaultValue: 'Space',
    category: 'controls',
    subcategory: 'gameplay',
    tags: ['movement'],
  },
  {
    id: 'controls.action.sprint',
    label: 'Sprint',
    description: 'Hold to run faster.',
    type: 'keybinding',
    value: 'ShiftLeft',
    defaultValue: 'ShiftLeft',
    category: 'controls',
    subcategory: 'gameplay',
    tags: ['movement'],
  },
  {
    id: 'controls.action.crouch',
    label: 'Crouch / Slide',
    description: 'Crouch or slide.',
    type: 'keybinding',
    value: 'ControlLeft',
    defaultValue: 'ControlLeft',
    category: 'controls',
    subcategory: 'gameplay',
    tags: ['movement'],
  },
  {
    id: 'controls.action.shoot',
    label: 'Primary Attack / Shoot',
    description: 'Fire the primary weapon or trigger the primary action.',
    type: 'keybinding',
    value: 'MouseButton0',
    defaultValue: 'MouseButton0',
    category: 'controls',
    subcategory: 'gameplay',
    tags: ['combat'],
  },
  {
    id: 'controls.action.aim',
    label: 'Aim / Secondary Attack',
    description: 'Aim down sights or trigger secondary action.',
    type: 'keybinding',
    value: 'MouseButton2',
    defaultValue: 'MouseButton2',
    category: 'controls',
    subcategory: 'gameplay',
    tags: ['combat'],
  },
  {
    id: 'controls.action.interact',
    label: 'Interact',
    description: 'Interact with objects in the game world.',
    type: 'keybinding',
    value: 'KeyE',
    defaultValue: 'KeyE',
    category: 'controls',
    subcategory: 'gameplay',
    tags: ['interaction'],
  },
  {
    id: 'controls.action.reload',
    label: 'Reload',
    description: 'Reload the current weapon.',
    type: 'keybinding',
    value: 'KeyR',
    defaultValue: 'KeyR',
    category: 'controls',
    subcategory: 'gameplay',
    tags: ['combat'],
  },
  {
    id: 'controls.action.openInventory',
    label: 'Open Inventory / Pause Menu',
    description: 'Open the inventory or pause the game.',
    type: 'keybinding',
    value: 'Escape',
    defaultValue: 'Escape',
    category: 'controls',
    subcategory: 'gameplay',
    tags: ['ui'],
  },

  // ── Mouse Settings ─────────────────────────────────────────────────────
  {
    id: 'controls.mouse.sensitivity',
    label: 'Mouse Sensitivity',
    description: 'How fast the camera rotates in response to mouse movement.',
    type: 'slider',
    value: 50,
    defaultValue: 50,
    min: 1,
    max: 100,
    step: 1,
    category: 'controls',
    subcategory: 'mouse',
  },
  {
    id: 'controls.mouse.invertY',
    label: 'Invert Y Axis',
    description: 'Invert the vertical mouse axis (pitch).',
    type: 'toggle',
    value: false,
    defaultValue: false,
    category: 'controls',
    subcategory: 'mouse',
  },
  {
    id: 'controls.mouse.smoothing',
    label: 'Mouse Smoothing',
    description: 'Apply smoothing to mouse input for a more fluid feel.',
    type: 'toggle',
    value: false,
    defaultValue: false,
    category: 'controls',
    subcategory: 'mouse',
  },

  // ── Gamepad Settings ───────────────────────────────────────────────────
  {
    id: 'controls.gamepad.deadzone',
    label: 'Stick Deadzone',
    description: 'Minimum stick displacement before movement is registered. Higher values reduce drift.',
    type: 'slider',
    value: 12,
    defaultValue: 12,
    min: 0,
    max: 40,
    step: 1,
    category: 'controls',
    subcategory: 'gamepad',
  },
  {
    id: 'controls.gamepad.sensitivity',
    label: 'Stick Sensitivity',
    description: 'Analog stick camera sensitivity multiplier.',
    type: 'slider',
    value: 50,
    defaultValue: 50,
    min: 1,
    max: 100,
    step: 1,
    category: 'controls',
    subcategory: 'gamepad',
  },
  {
    id: 'controls.gamepad.vibration',
    label: 'Haptic Feedback / Rumble',
    description: 'Enable gamepad vibration for impacts and events.',
    type: 'toggle',
    value: true,
    defaultValue: true,
    category: 'controls',
    subcategory: 'gamepad',
  },
]
