import type { SettingItem } from './SettingsPage.types'

export const EDITOR_SETTING_ITEMS: SettingItem[] = [
  {
    id: 'editor.fontSize',
    label: 'Font Size',
    description: 'Controls the font size in pixels',
    type: 'number',
    value: 14,
    defaultValue: 14,
    min: 8,
    max: 32,
    category: 'editor',
    subcategory: 'font',
  },
  {
    id: 'editor.fontFamily',
    label: 'Font Family',
    description: 'Controls the font family',
    type: 'text',
    value: 'JetBrains Mono, Fira Code, monospace',
    defaultValue: 'JetBrains Mono, Fira Code, monospace',
    category: 'editor',
    subcategory: 'font',
  },
  {
    id: 'editor.tabSize',
    label: 'Tab Size',
    description: 'The number of spaces a tab is equal to',
    type: 'select',
    value: 2,
    defaultValue: 2,
    options: [
      { label: '2 spaces', value: 2 },
      { label: '4 spaces', value: 4 },
      { label: '8 spaces', value: 8 },
    ],
    category: 'editor',
    subcategory: 'formatting',
  },
  {
    id: 'editor.wordWrap',
    label: 'Word Wrap',
    description: 'Controls how lines should wrap',
    type: 'select',
    value: 'on',
    defaultValue: 'on',
    options: [
      { label: 'Off', value: 'off' },
      { label: 'On', value: 'on' },
      { label: 'Word Wrap Column', value: 'wordWrapColumn' },
      { label: 'Bounded', value: 'bounded' },
    ],
    category: 'editor',
    subcategory: 'formatting',
  },
  {
    id: 'editor.minimap',
    label: 'Minimap',
    description: 'Controls whether the minimap is shown',
    type: 'toggle',
    value: true,
    defaultValue: true,
    category: 'editor',
  },
  {
    id: 'editor.lineNumbers',
    label: 'Line Numbers',
    description: 'Controls the display of line numbers',
    type: 'select',
    value: 'on',
    defaultValue: 'on',
    options: [
      { label: 'Off', value: 'off' },
      { label: 'On', value: 'on' },
      { label: 'Relative', value: 'relative' },
    ],
    category: 'editor',
  },
  {
    id: 'editor.formatOnSave',
    label: 'Format On Save',
    description: 'Format a file on save',
    type: 'toggle',
    value: true,
    defaultValue: true,
    category: 'editor',
    subcategory: 'formatting',
  },
  {
    id: 'editor.cursorStyle',
    label: 'Cursor Style',
    description: 'Controls the cursor style',
    type: 'select',
    value: 'line',
    defaultValue: 'line',
    options: [
      { label: 'Line', value: 'line' },
      { label: 'Block', value: 'block' },
      { label: 'Underline', value: 'underline' },
      { label: 'Line Thin', value: 'line-thin' },
      { label: 'Block Outline', value: 'block-outline' },
      { label: 'Underline Thin', value: 'underline-thin' },
    ],
    category: 'editor',
    subcategory: 'cursor',
  },
  {
    id: 'editor.smoothScrolling',
    label: 'Smooth Scrolling',
    description: 'Controls whether the editor scrolls using an animation',
    type: 'toggle',
    value: true,
    defaultValue: true,
    category: 'editor',
  },
  {
    id: 'editor.bracketPairColorization',
    label: 'Bracket Pair Colorization',
    description: 'Controls whether bracket pair colorization is enabled',
    type: 'toggle',
    value: true,
    defaultValue: true,
    category: 'editor',
  },
  {
    id: 'editor.stickyScroll.enabled',
    label: 'Sticky Scroll',
    description: 'Shows nested current scopes during scroll',
    type: 'toggle',
    value: true,
    defaultValue: true,
    category: 'editor',
  },
]
